In [30]:
import pandas as pd
from pathlib import Path

# Project folders
RAW_DIR = Path("../data/raw")
VALIDATION_DIR = Path("../validation")

VALIDATION_DIR.mkdir(parents=True, exist_ok=True)

print("Raw data folder:", RAW_DIR.resolve())
print("Validation folder:", VALIDATION_DIR.resolve())

Raw data folder: C:\Users\nanda\OneDrive\Desktop\EduVision_DV\Milestone_01\Module_01\data\raw
Validation folder: C:\Users\nanda\OneDrive\Desktop\EduVision_DV\Milestone_01\Module_01\validation

In [31]:
# ============================================================
# LOAD ALL FOUR DATA SOURCES
# ============================================================

# QS 2025
qs_df = pd.read_csv(
    RAW_DIR / "qs_2025_raw.csv"
)

# THE 2024
the_df = pd.read_csv(
    RAW_DIR / "the_2024_raw.csv"
)

# WUR 2023
wur_df = pd.read_csv(
    RAW_DIR / "World University Rankings 2023.csv"
)

# World Bank Education Statistics
wb_country_series_df = pd.read_csv(
    RAW_DIR / "EdStatsCountry-Series.csv"
)

wb_country_df = pd.read_csv(
    RAW_DIR / "EdStatsCountry.csv"
)

wb_footnote_df = pd.read_csv(
    RAW_DIR / "EdStatsFootNote.csv"
)

wb_series_df = pd.read_csv(
    RAW_DIR / "EdStatsSeries.csv"
)

# World Bank Excel workbook
wb_excel = pd.ExcelFile(
    RAW_DIR / "EdStatsEXCEL.xlsx"
)

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [32]:
print("QS 2025:", qs_df.shape)
print("THE 2024:", the_df.shape)
print("WUR 2023:", wur_df.shape)

print("World Bank Country-Series:", wb_country_series_df.shape)
print("World Bank Country:", wb_country_df.shape)
print("World Bank FootNote:", wb_footnote_df.shape)
print("World Bank Series:", wb_series_df.shape)

print("World Bank Excel sheets:", wb_excel.sheet_names)

QS 2025: (1503, 16)
THE 2024: (2673, 29)
WUR 2023: (2341, 13)
World Bank Country-Series: (613, 4)
World Bank Country: (241, 32)
World Bank FootNote: (643638, 5)
World Bank Series: (3665, 21)
World Bank Excel sheets: ['Data', 'Country', 'Series', 'Country-Series', 'FootNote']

In [33]:
# ============================================================
# DATASET OVERVIEW
# ============================================================

datasets = {
    "QS 2025": qs_df,
    "THE 2024": the_df,
    "WUR 2023": wur_df,
    "World Bank - Country-Series": wb_country_series_df,
    "World Bank - Country": wb_country_df,
    "World Bank - FootNote": wb_footnote_df,
    "World Bank - Series": wb_series_df
}

for name, df in datasets.items():
    print(
        f"{name}: "
        f"{df.shape[0]:,} rows × "
        f"{df.shape[1]} columns"
    )

QS 2025: 1,503 rows × 16 columns
THE 2024: 2,673 rows × 29 columns
WUR 2023: 2,341 rows × 13 columns
World Bank - Country-Series: 613 rows × 4 columns
World Bank - Country: 241 rows × 32 columns
World Bank - FootNote: 643,638 rows × 5 columns
World Bank - Series: 3,665 rows × 21 columns

In [34]:
# ============================================================
# COLUMN VALIDATION
# ============================================================

for name, df in datasets.items():
    print("\n" + "=" * 80)
    print(name)
    print("=" * 80)

    print(df.columns.tolist())

================================================================================
QS 2025
================================================================================
['2025 Rank', '2024 Rank', 'Institution Name', 'Location', 'Location Full', 'Size', 'Academic Reputation', 'Employer Reputation', 'Faculty Student', 'Citations per Faculty', 'International Faculty', 'International Students', 'International Research Network', 'Employment Outcomes', 'Sustainability', 'QS Overall Score']

================================================================================
THE 2024
================================================================================
['rank', 'name', 'scores_overall', 'scores_overall_rank', 'scores_teaching', 'scores_teaching_rank', 'scores_research', 'scores_research_rank', 'scores_citations', 'scores_citations_rank', 'scores_industry_income', 'scores_industry_income_rank', 'scores_international_outlook', 'scores_international_outlook_rank', 'record_type', 'member_level', 'url', 'nid', 'location', 'stats_number_students', 'stats_student_staff_ratio', 'stats_pc_intl_students', 'stats_female_male_ratio', 'aliases', 'subjects_offered', 'closed', 'unaccredited', 'disabled', 'website_url']

================================================================================
WUR 2023
================================================================================
['University Rank', 'Name of University', 'Location', 'No of student', 'No of student per staff', 'International Student', 'Female:Male Ratio', 'OverAll Score', 'Teaching Score', 'Research Score', 'Citations Score', 'Industry Income Score', 'International Outlook Score']

================================================================================
World Bank - Country-Series
================================================================================
['CountryCode', 'SeriesCode', 'DESCRIPTION', 'Unnamed: 3']

================================================================================
World Bank - Country
================================================================================
['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code', 'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code', 'National accounts base year', 'National accounts reference year', 'SNA price valuation', 'Lending category', 'Other groups', 'System of National Accounts', 'Alternative conversion factor', 'PPP survey year', 'Balance of Payments Manual in use', 'External debt Reporting status', 'System of trade', 'Government Accounting concept', 'IMF data dissemination standard', 'Latest population census', 'Latest household survey', 'Source of most recent Income and expenditure data', 'Vital registration complete', 'Latest agricultural census', 'Latest industrial data', 'Latest trade data', 'Latest water withdrawal data', 'Unnamed: 31']

================================================================================
World Bank - FootNote
================================================================================
['CountryCode', 'SeriesCode', 'Year', 'DESCRIPTION', 'Unnamed: 4']

================================================================================
World Bank - Series
================================================================================
['Series Code', 'Topic', 'Indicator Name', 'Short definition', 'Long definition', 'Unit of measure', 'Periodicity', 'Base Period', 'Other notes', 'Aggregation method', 'Limitations and exceptions', 'Notes from original source', 'General comments', 'Source', 'Statistical concept and methodology', 'Development relevance', 'Related source links', 'Other web links', 'Related indicators', 'License Type', 'Unnamed: 20']

In [35]:
# ============================================================
# DATA TYPE VALIDATION
# ============================================================

for name, df in datasets.items():
    print("\n" + "=" * 80)
    print(name)
    print("=" * 80)

    print(df.dtypes)

================================================================================
QS 2025
================================================================================
2025 Rank                             str
2024 Rank                             str
Institution Name                      str
Location                              str
Location Full                         str
Size                                  str
Academic Reputation               float64
Employer Reputation               float64
Faculty Student                   float64
Citations per Faculty             float64
International Faculty             float64
International Students            float64
International Research Network    float64
Employment Outcomes               float64
Sustainability                    float64
QS Overall Score                      str
dtype: object

================================================================================
THE 2024
================================================================================
rank                                     str
name                                     str
scores_overall                           str
scores_overall_rank                    int64
scores_teaching                      float64
scores_teaching_rank                   int64
scores_research                      float64
scores_research_rank                   int64
scores_citations                     float64
scores_citations_rank                  int64
scores_industry_income               float64
scores_industry_income_rank            int64
scores_international_outlook         float64
scores_international_outlook_rank      int64
record_type                              str
member_level                           int64
url                                      str
nid                                    int64
location                                 str
stats_number_students                    str
stats_student_staff_ratio            float64
stats_pc_intl_students                   str
stats_female_male_ratio                  str
aliases                                  str
subjects_offered                         str
closed                                  bool
unaccredited                            bool
disabled                                bool
website_url                              str
dtype: object

================================================================================
WUR 2023
================================================================================
University Rank                    str
Name of University                 str
Location                           str
No of student                      str
No of student per staff        float64
International Student              str
Female:Male Ratio                  str
OverAll Score                      str
Teaching Score                 float64
Research Score                 float64
Citations Score                float64
Industry Income Score          float64
International Outlook Score    float64
dtype: object

================================================================================
World Bank - Country-Series
================================================================================
CountryCode        str
SeriesCode         str
DESCRIPTION        str
Unnamed: 3     float64
dtype: object

================================================================================
World Bank - Country
================================================================================
Country Code                                             str
Short Name                                               str
Table Name                                               str
Long Name                                                str
2-alpha code                                             str
Currency Unit                                            str
Special Notes                                            str
Region                                                   str
Income Group                                             str
WB-2 code                                                str
National accounts base year                              str
National accounts reference year                     float64
SNA price valuation                                      str
Lending category                                         str
Other groups                                             str
System of National Accounts                              str
Alternative conversion factor                            str
PPP survey year                                          str
Balance of Payments Manual in use                        str
External debt Reporting status                           str
System of trade                                          str
Government Accounting concept                            str
IMF data dissemination standard                          str
Latest population census                                 str
Latest household survey                                  str
Source of most recent Income and expenditure data        str
Vital registration complete                              str
Latest agricultural census                               str
Latest industrial data                               float64
Latest trade data                                    float64
Latest water withdrawal data                             str
Unnamed: 31                                          float64
dtype: object

================================================================================
World Bank - FootNote
================================================================================
CountryCode        str
SeriesCode         str
Year               str
DESCRIPTION        str
Unnamed: 4     float64
dtype: object

================================================================================
World Bank - Series
================================================================================
Series Code                                str
Topic                                      str
Indicator Name                             str
Short definition                           str
Long definition                            str
Unit of measure                        float64
Periodicity                                str
Base Period                                str
Other notes                                str
Aggregation method                         str
Limitations and exceptions                 str
Notes from original source             float64
General comments                           str
Source                                     str
Statistical concept and methodology        str
Development relevance                      str
Related source links                       str
Other web links                        float64
Related indicators                     float64
License Type                           float64
Unnamed: 20                            float64
dtype: object

In [36]:
# ============================================================
# DATA TYPE VALIDATION
# ============================================================

for name, df in datasets.items():
    print("\n" + "=" * 80)
    print(name)
    print("=" * 80)

    print(df.dtypes)

================================================================================
QS 2025
================================================================================
2025 Rank                             str
2024 Rank                             str
Institution Name                      str
Location                              str
Location Full                         str
Size                                  str
Academic Reputation               float64
Employer Reputation               float64
Faculty Student                   float64
Citations per Faculty             float64
International Faculty             float64
International Students            float64
International Research Network    float64
Employment Outcomes               float64
Sustainability                    float64
QS Overall Score                      str
dtype: object

================================================================================
THE 2024
================================================================================
rank                                     str
name                                     str
scores_overall                           str
scores_overall_rank                    int64
scores_teaching                      float64
scores_teaching_rank                   int64
scores_research                      float64
scores_research_rank                   int64
scores_citations                     float64
scores_citations_rank                  int64
scores_industry_income               float64
scores_industry_income_rank            int64
scores_international_outlook         float64
scores_international_outlook_rank      int64
record_type                              str
member_level                           int64
url                                      str
nid                                    int64
location                                 str
stats_number_students                    str
stats_student_staff_ratio            float64
stats_pc_intl_students                   str
stats_female_male_ratio                  str
aliases                                  str
subjects_offered                         str
closed                                  bool
unaccredited                            bool
disabled                                bool
website_url                              str
dtype: object

================================================================================
WUR 2023
================================================================================
University Rank                    str
Name of University                 str
Location                           str
No of student                      str
No of student per staff        float64
International Student              str
Female:Male Ratio                  str
OverAll Score                      str
Teaching Score                 float64
Research Score                 float64
Citations Score                float64
Industry Income Score          float64
International Outlook Score    float64
dtype: object

================================================================================
World Bank - Country-Series
================================================================================
CountryCode        str
SeriesCode         str
DESCRIPTION        str
Unnamed: 3     float64
dtype: object

================================================================================
World Bank - Country
================================================================================
Country Code                                             str
Short Name                                               str
Table Name                                               str
Long Name                                                str
2-alpha code                                             str
Currency Unit                                            str
Special Notes                                            str
Region                                                   str
Income Group                                             str
WB-2 code                                                str
National accounts base year                              str
National accounts reference year                     float64
SNA price valuation                                      str
Lending category                                         str
Other groups                                             str
System of National Accounts                              str
Alternative conversion factor                            str
PPP survey year                                          str
Balance of Payments Manual in use                        str
External debt Reporting status                           str
System of trade                                          str
Government Accounting concept                            str
IMF data dissemination standard                          str
Latest population census                                 str
Latest household survey                                  str
Source of most recent Income and expenditure data        str
Vital registration complete                              str
Latest agricultural census                               str
Latest industrial data                               float64
Latest trade data                                    float64
Latest water withdrawal data                             str
Unnamed: 31                                          float64
dtype: object

================================================================================
World Bank - FootNote
================================================================================
CountryCode        str
SeriesCode         str
Year               str
DESCRIPTION        str
Unnamed: 4     float64
dtype: object

================================================================================
World Bank - Series
================================================================================
Series Code                                str
Topic                                      str
Indicator Name                             str
Short definition                           str
Long definition                            str
Unit of measure                        float64
Periodicity                                str
Base Period                                str
Other notes                                str
Aggregation method                         str
Limitations and exceptions                 str
Notes from original source             float64
General comments                           str
Source                                     str
Statistical concept and methodology        str
Development relevance                      str
Related source links                       str
Other web links                        float64
Related indicators                     float64
License Type                           float64
Unnamed: 20                            float64
dtype: object

In [37]:
# ============================================================
# DUPLICATE ROW VALIDATION
# ============================================================

for name, df in datasets.items():
    print(
        f"{name}: "
        f"{df.duplicated().sum():,} duplicate rows"
    )

QS 2025: 0 duplicate rows
THE 2024: 0 duplicate rows
WUR 2023: 29 duplicate rows
World Bank - Country-Series: 0 duplicate rows
World Bank - Country: 0 duplicate rows
World Bank - FootNote: 0 duplicate rows
World Bank - Series: 0 duplicate rows

In [39]:
# ============================================================
# DUPLICATE UNIVERSITY NAME VALIDATION
# ============================================================

print("QS 2025:")
print(
    qs_df["Institution Name"].duplicated().sum(),
    "duplicate university names"
)

print("\nTHE 2024:")
print(
    the_df["name"].duplicated().sum(),
    "duplicate university names"
)

print("\nWUR 2023:")
print(
    wur_df["Name of University"].duplicated().sum(),
    "duplicate university names"
)

QS 2025:
0 duplicate university names

THE 2024:
0 duplicate university names

WUR 2023:
107 duplicate university names

In [40]:
# ============================================================
# LOCATION VALIDATION
# ============================================================

print("QS 2025 unique locations:")
print(qs_df["Location"].nunique())

print("\nTHE 2024 unique locations:")
print(the_df["location"].nunique())

print("\nWUR 2023 unique locations:")
print(wur_df["Location"].nunique())

QS 2025 unique locations:
106

THE 2024 unique locations:
127

WUR 2023 unique locations:
116

In [41]:
# ============================================================
# RANKING FIELD VALIDATION
# ============================================================

print("QS 2025 rank:")
print(qs_df["2025 Rank"].head(10))

print("\nTHE 2024 rank:")
print(the_df["rank"].head(10))

print("\nWUR 2023 rank:")
print(wur_df["University Rank"].head(10))

QS 2025 rank:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: 2025 Rank, dtype: str

THE 2024 rank:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: rank, dtype: str

WUR 2023 rank:
0     1
1     2
2     3
3     3
4     5
5     6
6     7
7     8
8     9
9    10
Name: University Rank, dtype: str

In [42]:
# ============================================================
# WUR 2023 VALIDATION
# ============================================================

print("WUR 2023 VALIDATION")
print("=" * 80)

print("Rows:", wur_df.shape[0])
print("Columns:", wur_df.shape[1])

print(
    "Unique universities:",
    wur_df["Name of University"].nunique()
)

print(
    "Unique locations:",
    wur_df["Location"].nunique()
)

print(
    "Duplicate rows:",
    wur_df.duplicated().sum()
)

print(
    "Duplicate university names:",
    wur_df["Name of University"].duplicated().sum()
)

print(
    "Missing university names:",
    wur_df["Name of University"].isnull().sum()
)

print(
    "Missing locations:",
    wur_df["Location"].isnull().sum()
)

display(wur_df.head())

WUR 2023 VALIDATION
================================================================================
Rows: 2341
Columns: 13
Unique universities: 2233
Unique locations: 116
Duplicate rows: 29
Duplicate university names: 107
Missing university names: 108
Missing locations: 294

,University Rank,Name of University,Location,No of student,No of student per staff,International Student,Female:Male Ratio,OverAll Score,Teaching Score,Research Score,Citations Score,Industry Income Score,International Outlook Score
0,1,University of Oxford,United Kingdom,"20,965",10.6,42%,48 : 52,96.4,92.3,99.7,99.0,74.9,96.2
1,2,Harvard University,United States,"21,887",9.6,25%,50 : 50,95.2,94.8,99.0,99.3,49.5,80.5
2,3,University of Cambridge,United Kingdom,"20,185",11.3,39%,47 : 53,94.8,90.9,99.5,97.0,54.2,95.8
3,3,Stanford University,United States,"16,164",7.1,24%,46 : 54,94.8,94.2,96.7,99.8,65.0,79.8
4,5,Massachusetts Institute of Technology,United States,"11,415",8.2,33%,40 : 60,94.2,90.7,93.6,99.8,90.9,89.3

In [43]:
# ============================================================
# WUR 2023 VALIDATION
# ============================================================

print("WUR 2023 VALIDATION")
print("=" * 80)

print("Rows:", wur_df.shape[0])
print("Columns:", wur_df.shape[1])

print(
    "Unique universities:",
    wur_df["Name of University"].nunique()
)

print(
    "Unique locations:",
    wur_df["Location"].nunique()
)

print(
    "Duplicate rows:",
    wur_df.duplicated().sum()
)

print(
    "Duplicate university names:",
    wur_df["Name of University"].duplicated().sum()
)

print(
    "Missing university names:",
    wur_df["Name of University"].isnull().sum()
)

print(
    "Missing locations:",
    wur_df["Location"].isnull().sum()
)

display(wur_df.head())

WUR 2023 VALIDATION
================================================================================
Rows: 2341
Columns: 13
Unique universities: 2233
Unique locations: 116
Duplicate rows: 29
Duplicate university names: 107
Missing university names: 108
Missing locations: 294

,University Rank,Name of University,Location,No of student,No of student per staff,International Student,Female:Male Ratio,OverAll Score,Teaching Score,Research Score,Citations Score,Industry Income Score,International Outlook Score
0,1,University of Oxford,United Kingdom,"20,965",10.6,42%,48 : 52,96.4,92.3,99.7,99.0,74.9,96.2
1,2,Harvard University,United States,"21,887",9.6,25%,50 : 50,95.2,94.8,99.0,99.3,49.5,80.5
2,3,University of Cambridge,United Kingdom,"20,185",11.3,39%,47 : 53,94.8,90.9,99.5,97.0,54.2,95.8
3,3,Stanford University,United States,"16,164",7.1,24%,46 : 54,94.8,94.2,96.7,99.8,65.0,79.8
4,5,Massachusetts Institute of Technology,United States,"11,415",8.2,33%,40 : 60,94.2,90.7,93.6,99.8,90.9,89.3

In [44]:
# ============================================================
# WORLD BANK SERIES VALIDATION
# ============================================================

print("WORLD BANK - EDSTATS SERIES")
print("=" * 80)

print("Rows:", wb_series_df.shape[0])
print("Columns:", wb_series_df.shape[1])

print(
    "Unique series codes:",
    wb_series_df["Series Code"].nunique()
)

print(
    "Duplicate series codes:",
    wb_series_df["Series Code"].duplicated().sum()
)

print(
    "Missing series codes:",
    wb_series_df["Series Code"].isnull().sum()
)

print(
    "Missing indicator names:",
    wb_series_df["Indicator Name"].isnull().sum()
)

display(
    wb_series_df[
        [
            "Series Code",
            "Indicator Name",
            "Topic",
            "Unit of measure"
        ]
    ].head(10)
)

WORLD BANK - EDSTATS SERIES
================================================================================
Rows: 3665
Columns: 21
Unique series codes: 3665
Duplicate series codes: 0
Missing series codes: 0
Missing indicator names: 0

,Series Code,Indicator Name,Topic,Unit of measure
0,BAR.NOED.1519.FE.ZS,Barro-Lee: Percentage of female population age...,Attainment,NaN
1,BAR.NOED.1519.ZS,Barro-Lee: Percentage of population age 15-19 ...,Attainment,NaN
2,BAR.NOED.15UP.FE.ZS,Barro-Lee: Percentage of female population age...,Attainment,NaN
3,BAR.NOED.15UP.ZS,Barro-Lee: Percentage of population age 15+ wi...,Attainment,NaN
4,BAR.NOED.2024.FE.ZS,Barro-Lee: Percentage of female population age...,Attainment,NaN
5,BAR.NOED.2024.ZS,Barro-Lee: Percentage of population age 20-24 ...,Attainment,NaN
6,BAR.NOED.2529.FE.ZS,Barro-Lee: Percentage of female population age...,Attainment,NaN
7,BAR.NOED.2529.ZS,Barro-Lee: Percentage of population age 25-29 ...,Attainment,NaN
8,BAR.NOED.25UP.FE.ZS,Barro-Lee: Percentage of female population age...,Attainment,NaN
9,BAR.NOED.25UP.ZS,Barro-Lee: Percentage of population age 25+ wi...,Attainment,NaN

In [45]:
# ============================================================
# WORLD BANK COUNTRY-SERIES VALIDATION
# ============================================================

print("WORLD BANK - EDSTATS COUNTRY-SERIES")
print("=" * 80)

print("Rows:", wb_country_series_df.shape[0])
print("Columns:", wb_country_series_df.shape[1])

print(
    "Unique countries:",
    wb_country_series_df["CountryCode"].nunique()
)

print(
    "Unique series:",
    wb_country_series_df["SeriesCode"].nunique()
)

print(
    "Duplicate country-series combinations:",
    wb_country_series_df[
        ["CountryCode", "SeriesCode"]
    ].duplicated().sum()
)

print(
    "Missing country codes:",
    wb_country_series_df["CountryCode"].isnull().sum()
)

print(
    "Missing series codes:",
    wb_country_series_df["SeriesCode"].isnull().sum()
)

display(wb_country_series_df.head(10))

WORLD BANK - EDSTATS COUNTRY-SERIES
================================================================================
Rows: 613
Columns: 4
Unique countries: 211
Unique series: 21
Duplicate country-series combinations: 0
Missing country codes: 0
Missing series codes: 0

,CountryCode,SeriesCode,DESCRIPTION,Unnamed: 3
0,ABW,SP.POP.TOTL,Data sources : United Nations World Population...,NaN
1,ABW,SP.POP.GROW,Data sources: United Nations World Population ...,NaN
2,AFG,SP.POP.GROW,Data sources: United Nations World Population ...,NaN
3,AFG,NY.GDP.PCAP.PP.CD,Estimates are based on regression.,NaN
4,AFG,SP.POP.TOTL,Data sources : United Nations World Population...,NaN
5,AFG,NY.GDP.MKTP.PP.KD,Estimates are based on regression.,NaN
6,AFG,NY.GNP.MKTP.PP.CD,Estimates are based on regression.,NaN
7,AFG,NY.GDP.MKTP.PP.CD,Estimates are based on regression.,NaN
8,AFG,NY.GDP.PCAP.PP.KD,Estimates are based on regression.,NaN
9,AFG,NY.GNP.PCAP.PP.CD,Estimates are based on regression.,NaN

In [46]:
# ============================================================
# WORLD BANK FOOTNOTE VALIDATION
# ============================================================

print("WORLD BANK - EDSTATS FOOTNOTE")
print("=" * 80)

print("Rows:", wb_footnote_df.shape[0])
print("Columns:", wb_footnote_df.shape[1])

print(
    "Duplicate rows:",
    wb_footnote_df.duplicated().sum()
)

print("\nMissing values:")
print(wb_footnote_df.isnull().sum())

display(wb_footnote_df.head(10))

WORLD BANK - EDSTATS FOOTNOTE
================================================================================
Rows: 643638
Columns: 5
Duplicate rows: 0

Missing values:
CountryCode         0
SeriesCode          0
Year                0
DESCRIPTION         0
Unnamed: 4     643638
dtype: int64

  CountryCode         SeriesCode    Year          DESCRIPTION  Unnamed: 4
0         ABW     SE.PRE.ENRL.FE  YR2001  Country estimation.         NaN
1         ABW     SE.TER.TCHR.FE  YR2005  Country estimation.         NaN
2         ABW     SE.PRE.TCHR.FE  YR2000  Country estimation.         NaN
3         ABW     SE.SEC.ENRL.GC  YR2004  Country estimation.         NaN
4         ABW        SE.PRE.TCHR  YR2006  Country estimation.         NaN
5         ABW        SE.PRE.NENR  YR2000  Country estimation.         NaN
6         ABW  SE.SEC.ENRL.VO.FE  YR2005  Country estimation.         NaN
7         ABW     SE.SEC.ENRL.GC  YR2003  Country estimation.         NaN
8         ABW     SE.PRM.TCHR.FE  YR1999  Country estimation.         NaN
9         ABW  SE.PRE.TCHR.FE.ZS  YR2008  Country estimation.         NaN

In [47]:
# ============================================================
# WORLD BANK EXCEL WORKBOOK VALIDATION
# ============================================================

print("WORLD BANK - EDSTATS EXCEL")
print("=" * 80)

print("Number of worksheets:", len(wb_excel.sheet_names))

print("\nWorksheet names:")

for sheet in wb_excel.sheet_names:
    print("-", sheet)

WORLD BANK - EDSTATS EXCEL
================================================================================
Number of worksheets: 5

Worksheet names:
- Data
- Country
- Series
- Country-Series
- FootNote

In [48]:
# ============================================================
# UNIVERSITY DATASET SUMMARY
# ============================================================

university_summary = pd.DataFrame({
    "Dataset": [
        "QS 2025",
        "THE 2024",
        "WUR 2023"
    ],

    "Rows": [
        qs_df.shape[0],
        the_df.shape[0],
        wur_df.shape[0]
    ],

    "Columns": [
        qs_df.shape[1],
        the_df.shape[1],
        wur_df.shape[1]
    ],

    "Duplicate_Rows": [
        qs_df.duplicated().sum(),
        the_df.duplicated().sum(),
        wur_df.duplicated().sum()
    ],

    "Duplicate_University_Names": [
        qs_df["Institution Name"].duplicated().sum(),
        the_df["name"].duplicated().sum(),
        wur_df["Name of University"].duplicated().sum()
    ],

    "Unique_Locations": [
        qs_df["Location"].nunique(),
        the_df["location"].nunique(),
        wur_df["Location"].nunique()
    ]
})

display(university_summary)

,Dataset,Rows,Columns,Duplicate_Rows,Duplicate_University_Names,Unique_Locations
0,QS 2025,1503,16,0,0,106
1,THE 2024,2673,29,0,0,127
2,WUR 2023,2341,13,29,107,116

In [49]:
# ============================================================
# WORLD BANK DATASET SUMMARY
# ============================================================

world_bank_summary = pd.DataFrame({
    "File": [
        "EdStatsCountry-Series.csv",
        "EdStatsCountry.csv",
        "EdStatsFootNote.csv",
        "EdStatsSeries.csv"
    ],

    "Rows": [
        wb_country_series_df.shape[0],
        wb_country_df.shape[0],
        wb_footnote_df.shape[0],
        wb_series_df.shape[0]
    ],

    "Columns": [
        wb_country_series_df.shape[1],
        wb_country_df.shape[1],
        wb_footnote_df.shape[1],
        wb_series_df.shape[1]
    ],

    "Duplicate_Rows": [
        wb_country_series_df.duplicated().sum(),
        wb_country_df.duplicated().sum(),
        wb_footnote_df.duplicated().sum(),
        wb_series_df.duplicated().sum()
    ]
})

display(world_bank_summary)

                        File    Rows  Columns  Duplicate_Rows
0  EdStatsCountry-Series.csv     613        4               0
1         EdStatsCountry.csv     241       32               0
2        EdStatsFootNote.csv  643638        5               0
3          EdStatsSeries.csv    3665       21               0

In [50]:
# ============================================================
# CREATE FINAL VALIDATION REPORT
# ============================================================

validation_report = pd.DataFrame({
    "Dataset": [
        "QS 2025",
        "THE 2024",
        "WUR 2023",
        "World Bank - EdStatsCountry-Series",
        "World Bank - EdStatsCountry",
        "World Bank - EdStatsFootNote",
        "World Bank - EdStatsSeries"
    ],

    "Rows": [
        qs_df.shape[0],
        the_df.shape[0],
        wur_df.shape[0],
        wb_country_series_df.shape[0],
        wb_country_df.shape[0],
        wb_footnote_df.shape[0],
        wb_series_df.shape[0]
    ],

    "Columns": [
        qs_df.shape[1],
        the_df.shape[1],
        wur_df.shape[1],
        wb_country_series_df.shape[1],
        wb_country_df.shape[1],
        wb_footnote_df.shape[1],
        wb_series_df.shape[1]
    ],

    "Duplicate_Rows": [
        qs_df.duplicated().sum(),
        the_df.duplicated().sum(),
        wur_df.duplicated().sum(),
        wb_country_series_df.duplicated().sum(),
        wb_country_df.duplicated().sum(),
        wb_footnote_df.duplicated().sum(),
        wb_series_df.duplicated().sum()
    ],

    "Duplicate_University_Names": [
        qs_df["Institution Name"].duplicated().sum(),
        the_df["name"].duplicated().sum(),
        wur_df["Name of University"].duplicated().sum(),
        None,
        None,
        None,
        None
    ],

    "Unique_Locations": [
        qs_df["Location"].nunique(),
        the_df["location"].nunique(),
        wur_df["Location"].nunique(),
        None,
        None,
        None,
        None
    ]
})

display(validation_report)

,Dataset,Rows,Columns,Duplicate_Rows,Duplicate_University_Names,Unique_Locations
0,QS 2025,1503,16,0,0.0,106.0
1,THE 2024,2673,29,0,0.0,127.0
2,WUR 2023,2341,13,29,107.0,116.0
3,World Bank - EdStatsCountry-Series,613,4,0,NaN,NaN
4,World Bank - EdStatsCountry,241,32,0,NaN,NaN
5,World Bank - EdStatsFootNote,643638,5,0,NaN,NaN
6,World Bank - EdStatsSeries,3665,21,0,NaN,NaN

In [51]:
# ============================================================
# SAVE VALIDATION REPORT
# ============================================================

report_path = VALIDATION_DIR / "validation_report.csv"

validation_report.to_csv(
    report_path,
    index=False
)

print("Validation report created successfully!")
print("Saved to:")
print(report_path.resolve())

Validation report created successfully!
Saved to:
C:\Users\nanda\OneDrive\Desktop\EduVision_DV\Milestone_01\Module_01\validation\validation_report.csv

In [52]:
# ============================================================
# VERIFY SAVED REPORT
# ============================================================

final_report = pd.read_csv(
    VALIDATION_DIR / "validation_report.csv"
)

display(final_report)

print("\nNumber of records:", len(final_report))
print("Validation report verified successfully!")

,Dataset,Rows,Columns,Duplicate_Rows,Duplicate_University_Names,Unique_Locations
0,QS 2025,1503,16,0,0.0,106.0
1,THE 2024,2673,29,0,0.0,127.0
2,WUR 2023,2341,13,29,107.0,116.0
3,World Bank - EdStatsCountry-Series,613,4,0,NaN,NaN
4,World Bank - EdStatsCountry,241,32,0,NaN,NaN
5,World Bank - EdStatsFootNote,643638,5,0,NaN,NaN
6,World Bank - EdStatsSeries,3665,21,0,NaN,NaN

Number of records: 7
Validation report verified successfully!

In [53]:
from pathlib import Path
import pandas as pd

RAW_DIR = Path("../data/raw")

print("RAW DATA FILES")
print("=" * 60)

for file in RAW_DIR.rglob("*"):
    if file.is_file():
        print(file.relative_to(RAW_DIR))

RAW DATA FILES
============================================================
EdStatsCountry-Series.csv
EdStatsCountry.csv
EdStatsEXCEL.xlsx
EdStatsFootNote.csv
EdStatsSeries.csv
qs_2025_raw.csv
the_2024_raw.csv
World University Rankings 2023.csv

In [54]:
print("\nDATASET COLUMNS")
print("=" * 60)

for file in RAW_DIR.rglob("*"):

    if not file.is_file():
        continue

    try:

        if file.suffix.lower() == ".csv":
            df = pd.read_csv(file, nrows=5)

        elif file.suffix.lower() in [".xlsx", ".xls"]:
            # Only inspect the workbook structure; don't load the whole thing
            excel = pd.ExcelFile(file)
            print(f"\n{file.name}")
            print("Excel sheets:", excel.sheet_names)
            continue

        else:
            continue

        print(f"\n{file.name}")
        print("Rows sampled:", len(df))
        print("Columns:")
        print(list(df.columns))

    except Exception as e:
        print(f"\nCould not inspect {file.name}: {e}")

DATASET COLUMNS
============================================================

EdStatsCountry-Series.csv
Rows sampled: 5
Columns:
['CountryCode', 'SeriesCode', 'DESCRIPTION', 'Unnamed: 3']

EdStatsCountry.csv
Rows sampled: 5
Columns:
['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code', 'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code', 'National accounts base year', 'National accounts reference year', 'SNA price valuation', 'Lending category', 'Other groups', 'System of National Accounts', 'Alternative conversion factor', 'PPP survey year', 'Balance of Payments Manual in use', 'External debt Reporting status', 'System of trade', 'Government Accounting concept', 'IMF data dissemination standard', 'Latest population census', 'Latest household survey', 'Source of most recent Income and expenditure data', 'Vital registration complete', 'Latest agricultural census', 'Latest industrial data', 'Latest trade data', 'Latest water withdrawal data', 'Unnamed: 31']

EdStatsEXCEL.xlsx
Excel sheets: ['Data', 'Country', 'Series', 'Country-Series', 'FootNote']

EdStatsFootNote.csv
Rows sampled: 5
Columns:
['CountryCode', 'SeriesCode', 'Year', 'DESCRIPTION', 'Unnamed: 4']

EdStatsSeries.csv
Rows sampled: 5
Columns:
['Series Code', 'Topic', 'Indicator Name', 'Short definition', 'Long definition', 'Unit of measure', 'Periodicity', 'Base Period', 'Other notes', 'Aggregation method', 'Limitations and exceptions', 'Notes from original source', 'General comments', 'Source', 'Statistical concept and methodology', 'Development relevance', 'Related source links', 'Other web links', 'Related indicators', 'License Type', 'Unnamed: 20']

qs_2025_raw.csv
Rows sampled: 5
Columns:
['2025 Rank', '2024 Rank', 'Institution Name', 'Location', 'Location Full', 'Size', 'Academic Reputation', 'Employer Reputation', 'Faculty Student', 'Citations per Faculty', 'International Faculty', 'International Students', 'International Research Network', 'Employment Outcomes', 'Sustainability', 'QS Overall Score']

the_2024_raw.csv
Rows sampled: 5
Columns:
['rank', 'name', 'scores_overall', 'scores_overall_rank', 'scores_teaching', 'scores_teaching_rank', 'scores_research', 'scores_research_rank', 'scores_citations', 'scores_citations_rank', 'scores_industry_income', 'scores_industry_income_rank', 'scores_international_outlook', 'scores_international_outlook_rank', 'record_type', 'member_level', 'url', 'nid', 'location', 'stats_number_students', 'stats_student_staff_ratio', 'stats_pc_intl_students', 'stats_female_male_ratio', 'aliases', 'subjects_offered', 'closed', 'unaccredited', 'disabled', 'website_url']

World University Rankings 2023.csv
Rows sampled: 5
Columns:
['University Rank', 'Name of University', 'Location', 'No of student', 'No of student per staff', 'International Student', 'Female:Male Ratio', 'OverAll Score', 'Teaching Score', 'Research Score', 'Citations Score', 'Industry Income Score', 'International Outlook Score']