In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/springboardmentor1234r/Higher-Education-Intelligence-System-for-Institutional-Performance-and-Academic-Excellence-Analysis/refs/heads/module-2-data-cleaning/data/processed/university_raw_data.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 2517
Columns: 24

In [ ]:
df.head()

,University,Country,QS_Rank,QS_Overall_Score,QS_Academic_Reputation,QS_Employer_Reputation,QS_Faculty_Student,QS_Citations_Per_Faculty,QS_International_Faculty,QS_International_Students,...,THE_Overall_Score,THE_Teaching,THE_Research,THE_Citations,THE_Industry_Income,THE_International_Outlook,THE_Number_Students,THE_Student_Staff_Ratio,THE_International_Students,THE_Female_Male_Ratio
0,Aalborg University,DK,306,35.7,19.9,20.8,25.5,53.2,77.3,14.9,...,55.9–58.6,33.7,45.0,83.0,80.6,72.4,"17,275",14.9,12%,NaN
1,Aalto University,FI,113,57.9,45.7,40.6,33.2,73.6,95.2,40.1,...,55.9–58.6,42.0,43.1,79.7,87.2,81.8,"14,427",20.4,23%,39 : 61
2,Aarhus University,DK,144,53.3,54.7,27.6,30.8,63.8,89.8,11.9,...,65.9,44.9,59.0,86.3,98.7,76.3,"26,996",13.5,9%,56 : 44
3,Abai Kazakh National Pedagogical University,KZ,671-680,-,26.5,22.8,53.8,1.1,37.8,3.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abdelmalek Essaâdi University,Morocco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.7–22.7,21.6,9.7,30.1,17.2,29.4,"122,962",91.8,1%,52 : 48

In [ ]:
df.columns.tolist()

['University',
 'Country',
 'QS_Rank',
 'QS_Overall_Score',
 'QS_Academic_Reputation',
 'QS_Employer_Reputation',
 'QS_Faculty_Student',
 'QS_Citations_Per_Faculty',
 'QS_International_Faculty',
 'QS_International_Students',
 'QS_International_Research_Network',
 'QS_Employment_Outcomes',
 'QS_Sustainability',
 'THE_Rank',
 'THE_Overall_Score',
 'THE_Teaching',
 'THE_Research',
 'THE_Citations',
 'THE_Industry_Income',
 'THE_International_Outlook',
 'THE_Number_Students',
 'THE_Student_Staff_Ratio',
 'THE_International_Students',
 'THE_Female_Male_Ratio']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   University                         2517 non-null   object
 1   Country                            2517 non-null   object
 2   QS_Rank                            1503 non-null   object
 3   QS_Overall_Score                   1503 non-null   object
 4   QS_Academic_Reputation             1503 non-null   float64
 5   QS_Employer_Reputation             1503 non-null   float64
 6   QS_Faculty_Student                 1503 non-null   float64
 7   QS_Citations_Per_Faculty           1503 non-null   float64
 8   QS_International_Faculty           1403 non-null   float64
 9   QS_International_Students          1445 non-null   float64
 10  QS_International_Research_Network  1502 non-null   float64
 11  QS_Employment_Outcomes             1503 non-null   float64
 12  QS_Sustainability                  1484 non-null   float64
 13  THE_Rank                           1904 non-null   object
 14  THE_Overall_Score                  1904 non-null   object
 15  THE_Teaching                       1904 non-null   float64
 16  THE_Research                       1904 non-null   float64
 17  THE_Citations                      1904 non-null   float64
 18  THE_Industry_Income                1904 non-null   float64
 19  THE_International_Outlook          1904 non-null   float64
 20  THE_Number_Students                1904 non-null   object
 21  THE_Student_Staff_Ratio            1904 non-null   float64
 22  THE_International_Students         1904 non-null   object
 23  THE_Female_Male_Ratio              1827 non-null   object
dtypes: float64(15), object(9)
memory usage: 472.1+ KB

In [ ]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

missing = missing.sort_values(
    by="Missing_Percentage",
    ascending=False
)

missing

                                   Missing_Count  Missing_Percentage
QS_International_Faculty                    1114           44.259039
QS_International_Students                   1072           42.590385
QS_Sustainability                           1033           41.040922
QS_International_Research_Network           1015           40.325785
QS_Overall_Score                            1014           40.286055
QS_Rank                                     1014           40.286055
QS_Employer_Reputation                      1014           40.286055
QS_Academic_Reputation                      1014           40.286055
QS_Employment_Outcomes                      1014           40.286055
QS_Faculty_Student                          1014           40.286055
QS_Citations_Per_Faculty                    1014           40.286055
THE_Female_Male_Ratio                        690           27.413588
THE_Teaching                                 613           24.354390
THE_Research                                 613           24.354390
THE_Overall_Score                            613           24.354390
THE_Rank                                     613           24.354390
THE_International_Outlook                    613           24.354390
THE_Number_Students                          613           24.354390
THE_Industry_Income                          613           24.354390
THE_Citations                                613           24.354390
THE_Student_Staff_Ratio                      613           24.354390
THE_International_Students                   613           24.354390
Country                                        0            0.000000
University                                     0            0.000000

In [ ]:
print("Total duplicate rows:", df.duplicated().sum())

Total duplicate rows: 0

In [ ]:
print("Duplicate university names:", df["University"].duplicated().sum())

Duplicate university names: 0

In [ ]:
print("Total universities:", df["University"].nunique())
print("Total countries:", df["Country"].nunique())

Total universities: 2517
Total countries: 192

In [ ]:
df["Country"].value_counts().head(20)

Country
US                    197
UK                     90
Japan                  73
CN                     71
India                  67
Iran                   65
Turkey                 61
JP                     49
DE                     48
Spain                  47
RU                     47
Brazil                 47
IN                     46
Russian Federation     46
United States          45
China                  44
KR                     43
IT                     42
Germany                39
AU                     38
Name: count, dtype: int64

In [ ]:
countries = sorted(df["Country"].dropna().unique())

print("Total unique country values:", len(countries))

for country in countries:
    print(country)

Total unique country values: 192
AE
AM
AR
AT
AU
AZ
Algeria
Argentina
Australia
Austria
BA
BD
BE
BG
BH
BN
BO
BR
BY
Bangladesh
Belgium
Botswana
Brazil
Bulgaria
CA
CH
CL
CN
CO
CR
CU
CY
CZ
Canada
Chile
China
Colombia
Costa Rica
Cuba
Cyprus
Czech Republic
DE
DK
DO
Denmark
EC
EE
EG
ES
ET
Ecuador
Egypt
Ethiopia
FI
FR
Fiji
Finland
France
GE
GH
GR
GT
Georgia
Germany
Ghana
Greece
HK
HN
HR
HU
Hungary
ID
IE
IL
IN
IQ
IR
IS
IT
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
JO
JP
Jamaica
Japan
KE
KG
KR
KW
KZ
Kazakhstan
Kosovo
LB
LK
LT
LU
LV
Latvia
Lebanon
Lithuania
MA
MO
MT
MX
MY
Malaysia
Mauritius
Mexico
Montenegro
Morocco
Mozambique
NCY
NG
NL
NO
NZ
Namibia
Nepal
Netherlands
New Zealand
Nigeria
North Macedonia
Northern Cyprus
Norway
OM
PA
PE
PH
PK
PL
PR
PS
PT
PY
Pakistan
Peru
Poland
Portugal
Puerto Rico
QA
RO
RS
RU
Romania
Russian Federation
SA
SD
SE
SG
SI
SK
SY
Saudi Arabia
Slovakia
South Africa
South Korea
Spain
Sri Lanka
Sweden
Switzerland
TH
TN
TR
TW
Taiwan
Tanzania
Thailand
Tunisia
Turkey
UA
UG
UK
US
UY
UZ
Ukraine
United Arab Emirates
United Kingdom
United States
VE
VN
Venezuela
Vietnam
ZA
Zambia
Zimbabwe

In [ ]:
for country in countries:
    print(country)

AE
AM
AR
AT
AU
AZ
Algeria
Argentina
Australia
Austria
BA
BD
BE
BG
BH
BN
BO
BR
BY
Bangladesh
Belgium
Botswana
Brazil
Bulgaria
CA
CH
CL
CN
CO
CR
CU
CY
CZ
Canada
Chile
China
Colombia
Costa Rica
Cuba
Cyprus
Czech Republic
DE
DK
DO
Denmark
EC
EE
EG
ES
ET
Ecuador
Egypt
Ethiopia
FI
FR
Fiji
Finland
France
GE
GH
GR
GT
Georgia
Germany
Ghana
Greece
HK
HN
HR
HU
Hungary
ID
IE
IL
IN
IQ
IR
IS
IT
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
JO
JP
Jamaica
Japan
KE
KG
KR
KW
KZ
Kazakhstan
Kosovo
LB
LK
LT
LU
LV
Latvia
Lebanon
Lithuania
MA
MO
MT
MX
MY
Malaysia
Mauritius
Mexico
Montenegro
Morocco
Mozambique
NCY
NG
NL
NO
NZ
Namibia
Nepal
Netherlands
New Zealand
Nigeria
North Macedonia
Northern Cyprus
Norway
OM
PA
PE
PH
PK
PL
PR
PS
PT
PY
Pakistan
Peru
Poland
Portugal
Puerto Rico
QA
RO
RS
RU
Romania
Russian Federation
SA
SD
SE
SG
SI
SK
SY
Saudi Arabia
Slovakia
South Africa
South Korea
Spain
Sri Lanka
Sweden
Switzerland
TH
TN
TR
TW
Taiwan
Tanzania
Thailand
Tunisia
Turkey
UA
UG
UK
US
UY
UZ
Ukraine
United Arab Emirates
United Kingdom
United States
VE
VN
Venezuela
Vietnam
ZA
Zambia
Zimbabwe

In [ ]:
country_mapping = {
    "AE": "United Arab Emirates",
    "AM": "Armenia",
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BN": "Brunei",
    "BO": "Bolivia",
    "BR": "Brazil",
    "BY": "Belarus",
    "CA": "Canada",
    "CH": "Switzerland",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DK": "Denmark",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FR": "France",
    "GE": "Georgia",
    "GH": "Ghana",
    "GR": "Greece",
    "GT": "Guatemala",
    "HK": "Hong Kong",
    "HN": "Honduras",
    "HR": "Croatia",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IN": "India",
    "IQ": "Iraq",
    "IR": "Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KZ": "Kazakhstan",
    "LB": "Lebanon",
    "LK": "Sri Lanka",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "MA": "Morocco",
    "MO": "Macao",
    "MT": "Malta",
    "MX": "Mexico",
    "MY": "Malaysia",
    "NCY": "Northern Cyprus",
    "NG": "Nigeria",
    "NL": "Netherlands",
    "NO": "Norway",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PR": "Puerto Rico",
    "PS": "Palestine",
    "PT": "Portugal",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russian Federation",
    "SA": "Saudi Arabia",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "SY": "Syria",
    "TH": "Thailand",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TW": "Taiwan",
    "UA": "Ukraine",
    "UG": "Uganda",
    "UK": "United Kingdom",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "ZA": "South Africa",
    "Zimbab": "Zimbabwe"
}

In [ ]:
# Check which country values are NOT covered by the mapping
unmapped_countries = [
    country for country in countries
    if country not in country_mapping and country not in country_mapping.values()
]

print("Total original country values:", len(countries))
print("Unmapped country values:", len(unmapped_countries))
print("\nUnmapped values:")
for country in unmapped_countries:
    print(country)

Total original country values: 192
Unmapped country values: 13

Unmapped values:
Algeria
Botswana
Fiji
Jamaica
Kosovo
Mauritius
Montenegro
Mozambique
Namibia
Nepal
North Macedonia
Tanzania
Zambia

In [ ]:
print("The 13 unmapped country values are:")

for country in unmapped_countries:
    print(country)

The 13 unmapped country values are:
Algeria
Botswana
Fiji
Jamaica
Kosovo
Mauritius
Montenegro
Mozambique
Namibia
Nepal
North Macedonia
Tanzania
Zambia

In [ ]:
country_mapping.update({
    "Algeria": "Algeria",
    "Botswana": "Botswana",
    "Fiji": "Fiji",
    "Jamaica": "Jamaica",
    "Kosovo": "Kosovo",
    "Mauritius": "Mauritius",
    "Montenegro": "Montenegro",
    "Mozambique": "Mozambique",
    "Namibia": "Namibia",
    "Nepal": "Nepal",
    "North Macedonia": "North Macedonia",
    "Tanzania": "Tanzania",
    "Zambia": "Zambia"
})

In [ ]:
unmapped_countries = [
    country for country in countries
    if country not in country_mapping
]

print("Total original country values:", len(countries))
print("Unmapped country values:", len(unmapped_countries))

if unmapped_countries:
    print("\nUnmapped values:")
    for country in unmapped_countries:
        print(country)
else:
    print("\nAll 192 country values are covered! ✅")

Total original country values: 192
Unmapped country values: 73

Unmapped values:
Argentina
Australia
Austria
Bangladesh
Belgium
Brazil
Bulgaria
Canada
Chile
China
Colombia
Costa Rica
Cuba
Cyprus
Czech Republic
Denmark
Ecuador
Egypt
Ethiopia
Finland
France
Georgia
Germany
Ghana
Greece
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Japan
Kazakhstan
Latvia
Lebanon
Lithuania
Malaysia
Mexico
Morocco
Netherlands
New Zealand
Nigeria
Northern Cyprus
Norway
Pakistan
Peru
Poland
Portugal
Puerto Rico
Romania
Russian Federation
Saudi Arabia
Slovakia
South Africa
South Korea
Spain
Sri Lanka
Sweden
Switzerland
Taiwan
Thailand
Tunisia
Turkey
Ukraine
United Arab Emirates
United Kingdom
United States
Venezuela
Vietnam
Zimbabwe

In [ ]:
standardized_countries = set(country_mapping.values())

In [ ]:
unmapped_countries = [
    country for country in countries
    if country not in country_mapping
    and country not in standardized_countries
]

print("Total original country values:", len(countries))
print("Unmapped country values:", len(unmapped_countries))

if unmapped_countries:
    print("\nUnmapped values:")
    for country in unmapped_countries:
        print(country)
else:
    print("\nAll 192 country values are covered! ✅")

Total original country values: 192
Unmapped country values: 0

All 192 country values are covered! ✅

In [ ]:
df["Country"] = df["Country"].replace(country_mapping)

In [ ]:
print("Unique country values after cleaning:", df["Country"].nunique())

Unique country values after cleaning: 120

In [ ]:
df["Country"].value_counts().head(20)

Country
United States         242
Japan                 122
China                 115
India                 113
United Kingdom        112
Russian Federation     93
Germany                87
Turkey                 86
Spain                  82
Brazil                 82
Italy                  77
Iran                   74
France                 68
Chile                  50
Poland                 48
South Korea            47
Taiwan                 47
Mexico                 45
Pakistan               43
Colombia               42
Name: count, dtype: int64

In [ ]:
remaining_codes = [
    country for country in df["Country"].dropna().unique()
    if len(country) == 2 and country.isupper()
]

print("Remaining 2-letter country codes:", len(remaining_codes))
print(remaining_codes)

Remaining 2-letter country codes: 0
[]

In [ ]:
for col in [
    "QS_Rank",
    "QS_Overall_Score",
    "THE_Rank",
    "THE_Overall_Score",
    "THE_Number_Students",
    "THE_International_Students",
    "THE_Female_Male_Ratio"
]:
    print(f"\n--- {col} ---")
    print(df[col].dropna().unique()[:20])

--- QS_Rank ---
['306' '113' '144' '671-680' '661-670' '621-630' '501' '761-770' '771-780'
 '851-900' '711-720' '592' '308' '481' '477' '631-640' '1401+' '801-850'
 '552' '1001-1200']

--- QS_Overall_Score ---
['35.7' '57.9' '53.3' '-' '24.1' '21' '35.3' '25' '25.1' '22.5' '51'
 '44.8' '54.1' '29' '40.6' '24.8' '33.6' '29.5' '30.6' '22.8']

--- THE_Rank ---
['201–250' '=109' '1501+' '601–800' '501–600' '1201–1500' '1001–1200'
 '801–1000' '351–400' '182' '401–500' '67' '301–350' '251–300' '=177' '78'
 '=64' '7' '190' '24']

--- THE_Overall_Score ---
['55.9–58.6' '65.9' '9.7–22.7' '37.0–41.8' '41.9–45.3' '22.8–28.2'
 '28.3–32.6' '32.7–36.9' '49.1–51.0' '59.9' '45.4–49.0' '72.6' '51.1–53.0'
 '53.1–55.8' '60.2' '70.1' '73.0' '96.5' '59.3' '86.3']

--- THE_Number_Students ---
['17,275' '14,427' '26,996' '122,962' '11,681' '6,180' '2,506' '2,547'
 '5,771' '33,268' '6,582' '10,606' '9,660' '19,189' '8,987' '1,315'
 '152,995' '7,806' '72,946' '7,714']

--- THE_International_Students ---
['12%' '23%' '9%' '1%' '0%' '60%' '3%' '7%' '6%' '5%' '14%' '17%' '4%'
 '8%' '2%' '10%' '32%' '27%' '20%' '74%']

--- THE_Female_Male_Ratio ---
['39 : 61' '56 : 44' '52 : 48' '26 : 74' '51 : 49' '73 : 27' '32 : 68'
 '68 : 32' '70 : 30' '38 : 62' '57 : 43' '35 : 65' '67 : 33' '58 : 42'
 '34 : 66' '60 : 40' '41 : 59' '45 : 55' '49 : 51' '42 : 58']

In [ ]:
# Replace "-" with missing values
df["QS_Overall_Score"] = df["QS_Overall_Score"].replace("-", pd.NA)

# Convert QS Overall Score to numeric
df["QS_Overall_Score"] = pd.to_numeric(
    df["QS_Overall_Score"],
    errors="coerce"
)

# Remove commas from student numbers
df["THE_Number_Students"] = (
    df["THE_Number_Students"]
    .str.replace(",", "", regex=False)
)

# Convert student numbers to numeric
df["THE_Number_Students"] = pd.to_numeric(
    df["THE_Number_Students"],
    errors="coerce"
)

# Remove % from international students
df["THE_International_Students"] = (
    df["THE_International_Students"]
    .str.replace("%", "", regex=False)
)

# Convert to numeric
df["THE_International_Students"] = pd.to_numeric(
    df["THE_International_Students"],
    errors="coerce"
)

In [ ]:
df[[
    "QS_Overall_Score",
    "THE_Number_Students",
    "THE_International_Students"
]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 3 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   QS_Overall_Score            600 non-null    float64
 1   THE_Number_Students         1904 non-null   float64
 2   THE_International_Students  1904 non-null   float64
dtypes: float64(3)
memory usage: 59.1 KB

In [ ]:
# Split female:male ratio into two columns
ratio = df["THE_Female_Male_Ratio"].str.split(":", expand=True)

df["THE_Female_Percentage"] = pd.to_numeric(
    ratio[0].str.strip(),
    errors="coerce"
)

df["THE_Male_Percentage"] = pd.to_numeric(
    ratio[1].str.strip(),
    errors="coerce"
)

In [ ]:
df[[
    "THE_Female_Male_Ratio",
    "THE_Female_Percentage",
    "THE_Male_Percentage"
]].head(10)

  THE_Female_Male_Ratio  THE_Female_Percentage  THE_Male_Percentage
0                   NaN                    NaN                  NaN
1               39 : 61                   39.0                 61.0
2               56 : 44                   56.0                 44.0
3                   NaN                    NaN                  NaN
4               52 : 48                   52.0                 48.0
5               26 : 74                   26.0                 74.0
6               51 : 49                   51.0                 49.0
7                   NaN                    NaN                  NaN
8               51 : 49                   51.0                 49.0
9               73 : 27                   73.0                 27.0

In [ ]:
print("QS Rank examples:")
print(df["QS_Rank"].value_counts().head(20))

print("\nTHE Rank examples:")
print(df["THE_Rank"].value_counts().head(20))

QS Rank examples:
QS_Rank
1201-1400    199
1001-1200    197
1401+        102
951-1000      53
901-950       51
851-900       50
801-850       49
721-730       14
741-750       13
711-720       13
661-670       13
641-650       13
601-610       12
691-700       12
621-630       12
771-780       11
781-790       11
631-640       10
751-760       10
791-800       10
Name: count, dtype: int64

THE Rank examples:
THE_Rank
1501+        395
1201–1500    307
1001–1200    201
601–800      199
801–1000     198
401–500      102
501–600      102
251–300       52
351–400       50
201–250       49
301–350       48
=168           6
=193           5
=177           3
=64            3
=140           3
=199           3
=152           3
=155           3
=106           3
Name: count, dtype: int64

In [ ]:
print("\nQS Rank data type:", df["QS_Rank"].dtype)
print("THE Rank data type:", df["THE_Rank"].dtype)

QS Rank data type: object
THE Rank data type: object

In [ ]:
print("QS Rank examples:")
print(df["QS_Rank"].value_counts().head(20))

print("\nTHE Rank examples:")
print(df["THE_Rank"].value_counts().head(20))

QS Rank examples:
QS_Rank
1201-1400    199
1001-1200    197
1401+        102
951-1000      53
901-950       51
851-900       50
801-850       49
721-730       14
741-750       13
711-720       13
661-670       13
641-650       13
601-610       12
691-700       12
621-630       12
771-780       11
781-790       11
631-640       10
751-760       10
791-800       10
Name: count, dtype: int64

THE Rank examples:
THE_Rank
1501+        395
1201–1500    307
1001–1200    201
601–800      199
801–1000     198
401–500      102
501–600      102
251–300       52
351–400       50
201–250       49
301–350       48
=168           6
=193           5
=177           3
=64            3
=140           3
=199           3
=152           3
=155           3
=106           3
Name: count, dtype: int64

In [ ]:
import re

def extract_rank_start(value):
    if pd.isna(value):
        return pd.NA

    # Remove "=" and spaces
    value = str(value).replace("=", "").strip()

    # Extract the first number
    match = re.search(r"\d+", value)

    if match:
        return int(match.group())

    return pd.NA


df["QS_Rank_Numeric"] = df["QS_Rank"].apply(extract_rank_start)
df["THE_Rank_Numeric"] = df["THE_Rank"].apply(extract_rank_start)

df["QS_Rank_Numeric"] = pd.to_numeric(
    df["QS_Rank_Numeric"],
    errors="coerce"
)

df["THE_Rank_Numeric"] = pd.to_numeric(
    df["THE_Rank_Numeric"],
    errors="coerce"
)

In [ ]:
print(
    df[
        ["QS_Rank", "QS_Rank_Numeric",
         "THE_Rank", "THE_Rank_Numeric"]
    ].head(20)
)

    QS_Rank  QS_Rank_Numeric   THE_Rank  THE_Rank_Numeric
0       306            306.0    201–250             201.0
1       113            113.0    201–250             201.0
2       144            144.0       =109             109.0
3   671-680            671.0        NaN               NaN
4       NaN              NaN      1501+            1501.0
5       NaN              NaN    601–800             601.0
6   661-670            661.0    501–600             501.0
7   621-630            621.0        NaN               NaN
8       501            501.0    201–250             201.0
9       NaN              NaN      1501+            1501.0
10      NaN              NaN  1201–1500            1201.0
11  761-770            761.0  1001–1200            1001.0
12  771-780            771.0        NaN               NaN
13      NaN              NaN      1501+            1501.0
14      NaN              NaN  1201–1500            1201.0
15      NaN              NaN      1501+            1501.0
16      NaN              NaN  1001–1200            1001.0
17  851-900            851.0        NaN               NaN
18  711-720            711.0        NaN               NaN
19      NaN              NaN   801–1000             801.0

In [ ]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

missing = missing.sort_values(
    by="Missing_Percentage",
    ascending=False
)

missing

                                   Missing_Count  Missing_Percentage
QS_Overall_Score                            1917           76.162098
QS_International_Faculty                    1114           44.259039
QS_International_Students                   1072           42.590385
QS_Sustainability                           1033           41.040922
QS_International_Research_Network           1015           40.325785
QS_Citations_Per_Faculty                    1014           40.286055
QS_Rank                                     1014           40.286055
QS_Faculty_Student                          1014           40.286055
QS_Employer_Reputation                      1014           40.286055
QS_Employment_Outcomes                      1014           40.286055
QS_Rank_Numeric                             1014           40.286055
QS_Academic_Reputation                      1014           40.286055
THE_Male_Percentage                          690           27.413588
THE_Female_Percentage                        690           27.413588
THE_Female_Male_Ratio                        690           27.413588
THE_Industry_Income                          613           24.354390
THE_International_Outlook                    613           24.354390
THE_Rank                                     613           24.354390
THE_Overall_Score                            613           24.354390
THE_Teaching                                 613           24.354390
THE_International_Students                   613           24.354390
THE_Student_Staff_Ratio                      613           24.354390
THE_Citations                                613           24.354390
THE_Research                                 613           24.354390
THE_Number_Students                          613           24.354390
THE_Rank_Numeric                             613           24.354390
Country                                        0            0.000000
University                                     0            0.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 28 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   University                         2517 non-null   object
 1   Country                            2517 non-null   object
 2   QS_Rank                            1503 non-null   object
 3   QS_Overall_Score                   600 non-null    float64
 4   QS_Academic_Reputation             1503 non-null   float64
 5   QS_Employer_Reputation             1503 non-null   float64
 6   QS_Faculty_Student                 1503 non-null   float64
 7   QS_Citations_Per_Faculty           1503 non-null   float64
 8   QS_International_Faculty           1403 non-null   float64
 9   QS_International_Students          1445 non-null   float64
 10  QS_International_Research_Network  1502 non-null   float64
 11  QS_Employment_Outcomes             1503 non-null   float64
 12  QS_Sustainability                  1484 non-null   float64
 13  THE_Rank                           1904 non-null   object
 14  THE_Overall_Score                  1904 non-null   object
 15  THE_Teaching                       1904 non-null   float64
 16  THE_Research                       1904 non-null   float64
 17  THE_Citations                      1904 non-null   float64
 18  THE_Industry_Income                1904 non-null   float64
 19  THE_International_Outlook          1904 non-null   float64
 20  THE_Number_Students                1904 non-null   float64
 21  THE_Student_Staff_Ratio            1904 non-null   float64
 22  THE_International_Students         1904 non-null   float64
 23  THE_Female_Male_Ratio              1827 non-null   object
 24  THE_Female_Percentage              1827 non-null   float64
 25  THE_Male_Percentage                1827 non-null   float64
 26  QS_Rank_Numeric                    1503 non-null   float64
 27  THE_Rank_Numeric                   1904 non-null   float64
dtypes: float64(22), object(6)
memory usage: 550.7+ KB

In [ ]:
qs_score_non_numeric = df.loc[
    df["QS_Overall_Score"].isna(),
    "QS_Overall_Score"
]

print("Current missing QS scores:", qs_score_non_numeric.isna().sum())

Current missing QS scores: 1917

In [ ]:
raw_df = pd.read_csv("university_raw_data.csv")

print(raw_df["QS_Overall_Score"].dropna().unique()[:50])

FileNotFoundError: [Errno 2] No such file or directory: 'university_raw_data.csv'

In [ ]:
import os

for file in os.listdir():
    print(file)

.config
university_raw_data (1).csv
sample_data

In [ ]:
import os

for file in os.listdir():
    print(file)

.config
university_raw_data (1).csv
sample_data

In [ ]:
raw_df = pd.read_csv("university_raw_data (1).csv")

print("Rows:", len(raw_df))
print("Columns:", len(raw_df.columns))

Rows: 2517
Columns: 24

In [ ]:
print(raw_df["QS_Overall_Score"].dropna().unique()[:50])

['35.7' '57.9' '53.3' '-' '24.1' '21' '35.3' '25' '25.1' '22.5' '51'
 '44.8' '54.1' '29' '40.6' '24.8' '33.6' '29.5' '30.6' '22.8' '23.9'
 '46.2' '28.1' '23.6' '28.9' '82.4' '39.9' '25.2' '36.5' '26.4' '35.9'
 '38.5' '30.3' '25.5' '29.1' '28.5' '21.1' '58.1' '64.7' '33' '32.5'
 '90.9' '23.5' '47.6' '72' '39.7' '24.4' '27.6' '53.7' '41']

In [ ]:
print("Original QS Overall Score non-null:", raw_df["QS_Overall_Score"].notna().sum())
print("Original '-' values:", (raw_df["QS_Overall_Score"] == "-").sum())
print("Original numeric-looking values:",
      raw_df["QS_Overall_Score"].ne("-").sum())

Original QS Overall Score non-null: 1503
Original '-' values: 903
Original numeric-looking values: 1614

In [ ]:
print(raw_df["QS_Overall_Score"].value_counts().head(10))

QS_Overall_Score
-       903
23.6      7
24.5      6
37.2      6
21.3      5
22.6      5
21.1      5
20.8      5
22.4      5
24.1      5
Name: count, dtype: int64

In [ ]:
print("QS Overall Score missing:", df["QS_Overall_Score"].isna().sum())
print("QS Overall Score available:", df["QS_Overall_Score"].notna().sum())

QS Overall Score missing: 1917
QS Overall Score available: 600

In [ ]:
print(raw_df["THE_Overall_Score"].dropna().unique()[:50])

['55.9–58.6' '65.9' '9.7–22.7' '37.0–41.8' '41.9–45.3' '22.8–28.2'
 '28.3–32.6' '32.7–36.9' '49.1–51.0' '59.9' '45.4–49.0' '72.6' '51.1–53.0'
 '53.1–55.8' '60.2' '70.1' '73.0' '96.5' '59.3' '86.3' '61.3' '59.4'
 '67.2' '75.4' '69.3' '81.4' '90.9' '89.5' '61.4' '76.3' '83.9' '60.6'
 '60.8' '66.1' '66.7' '93.1' '66.5' '77.5' '59.5' '80.0' '65.6' '97.8'
 '68.2' '61.7' '95.1' '58.9' '71.3' '91.1' '62.8' '75.9']

In [ ]:
def convert_the_score(value):
    if pd.isna(value):
        return pd.NA

    value = str(value).strip()

    # Handle ranges such as 55.9–58.6
    if "–" in value:
        parts = value.split("–")
        try:
            lower = float(parts[0])
            upper = float(parts[1])
            return (lower + upper) / 2
        except:
            return pd.NA

    # Handle normal numeric values
    try:
        return float(value)
    except:
        return pd.NA


df["THE_Overall_Score_Numeric"] = (
    df["THE_Overall_Score"].apply(convert_the_score)
)

df["THE_Overall_Score_Numeric"] = pd.to_numeric(
    df["THE_Overall_Score_Numeric"],
    errors="coerce"
)

In [ ]:
print(
    df[
        ["THE_Overall_Score", "THE_Overall_Score_Numeric"]
    ].head(20)
)

   THE_Overall_Score  THE_Overall_Score_Numeric
0          55.9–58.6                      57.25
1          55.9–58.6                      57.25
2               65.9                      65.90
3                NaN                        NaN
4           9.7–22.7                      16.20
5          37.0–41.8                      39.40
6          41.9–45.3                      43.60
7                NaN                        NaN
8          55.9–58.6                      57.25
9           9.7–22.7                      16.20
10         22.8–28.2                      25.50
11         28.3–32.6                      30.45
12               NaN                        NaN
13          9.7–22.7                      16.20
14         22.8–28.2                      25.50
15          9.7–22.7                      16.20
16         28.3–32.6                      30.45
17               NaN                        NaN
18               NaN                        NaN
19         32.7–36.9                      34.80

In [ ]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

missing = missing.sort_values(
    by="Missing_Percentage",
    ascending=False
)

missing

                                   Missing_Count  Missing_Percentage
QS_Overall_Score                            1917           76.162098
QS_International_Faculty                    1114           44.259039
QS_International_Students                   1072           42.590385
QS_Sustainability                           1033           41.040922
QS_International_Research_Network           1015           40.325785
QS_Citations_Per_Faculty                    1014           40.286055
QS_Faculty_Student                          1014           40.286055
QS_Rank                                     1014           40.286055
QS_Academic_Reputation                      1014           40.286055
QS_Employer_Reputation                      1014           40.286055
QS_Employment_Outcomes                      1014           40.286055
QS_Rank_Numeric                             1014           40.286055
THE_Female_Male_Ratio                        690           27.413588
THE_Female_Percentage                        690           27.413588
THE_Male_Percentage                          690           27.413588
THE_Number_Students                          613           24.354390
THE_International_Outlook                    613           24.354390
THE_Rank                                     613           24.354390
THE_Overall_Score                            613           24.354390
THE_Teaching                                 613           24.354390
THE_Research                                 613           24.354390
THE_Student_Staff_Ratio                      613           24.354390
THE_International_Students                   613           24.354390
THE_Industry_Income                          613           24.354390
THE_Citations                                613           24.354390
THE_Rank_Numeric                             613           24.354390
THE_Overall_Score_Numeric                    613           24.354390
University                                     0            0.000000
Country                                        0            0.000000

In [ ]:
numeric_columns = df.select_dtypes(include="number").columns

for col in numeric_columns:
    negative_count = (df[col] < 0).sum()

    if negative_count > 0:
        print(f"{col}: {negative_count} negative values")

In [ ]:
print("THE International Students:")
print(df["THE_International_Students"].agg(["min", "max"]))

print("\nTHE Female Percentage:")
print(df["THE_Female_Percentage"].agg(["min", "max"]))

print("\nTHE Male Percentage:")
print(df["THE_Male_Percentage"].agg(["min", "max"]))

THE International Students:
min     0.0
max    92.0
Name: THE_International_Students, dtype: float64

THE Female Percentage:
min      0.0
max    100.0
Name: THE_Female_Percentage, dtype: float64

THE Male Percentage:
min      0.0
max    100.0
Name: THE_Male_Percentage, dtype: float64

In [ ]:
negative_values = {}

for col in df.select_dtypes(include="number").columns:
    count = (df[col] < 0).sum()
    if count > 0:
        negative_values[col] = count

print("Negative-value issues:", negative_values)

Negative-value issues: {}

In [ ]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate universities:", df["University"].duplicated().sum())

Duplicate rows: 0
Duplicate universities: 0

In [ ]:
print("Unique countries:", df["Country"].nunique())
print("Remaining 2-letter country codes:", len([
    x for x in df["Country"].dropna().unique()
    if len(x) == 2 and x.isupper()
]))

Unique countries: 120
Remaining 2-letter country codes: 0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 29 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   University                         2517 non-null   object
 1   Country                            2517 non-null   object
 2   QS_Rank                            1503 non-null   object
 3   QS_Overall_Score                   600 non-null    float64
 4   QS_Academic_Reputation             1503 non-null   float64
 5   QS_Employer_Reputation             1503 non-null   float64
 6   QS_Faculty_Student                 1503 non-null   float64
 7   QS_Citations_Per_Faculty           1503 non-null   float64
 8   QS_International_Faculty           1403 non-null   float64
 9   QS_International_Students          1445 non-null   float64
 10  QS_International_Research_Network  1502 non-null   float64
 11  QS_Employment_Outcomes             1503 non-null   float64
 12  QS_Sustainability                  1484 non-null   float64
 13  THE_Rank                           1904 non-null   object
 14  THE_Overall_Score                  1904 non-null   object
 15  THE_Teaching                       1904 non-null   float64
 16  THE_Research                       1904 non-null   float64
 17  THE_Citations                      1904 non-null   float64
 18  THE_Industry_Income                1904 non-null   float64
 19  THE_International_Outlook          1904 non-null   float64
 20  THE_Number_Students                1904 non-null   float64
 21  THE_Student_Staff_Ratio            1904 non-null   float64
 22  THE_International_Students         1904 non-null   float64
 23  THE_Female_Male_Ratio              1827 non-null   object
 24  THE_Female_Percentage              1827 non-null   float64
 25  THE_Male_Percentage                1827 non-null   float64
 26  QS_Rank_Numeric                    1503 non-null   float64
 27  THE_Rank_Numeric                   1904 non-null   float64
 28  THE_Overall_Score_Numeric          1904 non-null   float64
dtypes: float64(23), object(6)
memory usage: 570.4+ KB

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 2517
Columns: 29

In [ ]:
print("Final columns:")
for i, col in enumerate(df.columns, 1):
    print(i, col)

Final columns:
1 University
2 Country
3 QS_Rank
4 QS_Overall_Score
5 QS_Academic_Reputation
6 QS_Employer_Reputation
7 QS_Faculty_Student
8 QS_Citations_Per_Faculty
9 QS_International_Faculty
10 QS_International_Students
11 QS_International_Research_Network
12 QS_Employment_Outcomes
13 QS_Sustainability
14 THE_Rank
15 THE_Overall_Score
16 THE_Teaching
17 THE_Research
18 THE_Citations
19 THE_Industry_Income
20 THE_International_Outlook
21 THE_Number_Students
22 THE_Student_Staff_Ratio
23 THE_International_Students
24 THE_Female_Male_Ratio
25 THE_Female_Percentage
26 THE_Male_Percentage
27 QS_Rank_Numeric
28 THE_Rank_Numeric
29 THE_Overall_Score_Numeric

In [ ]:
print("========== FINAL DATA QUALITY CHECK ==========")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nDuplicate rows:", df.duplicated().sum())
print("Duplicate universities:", df["University"].duplicated().sum())

print("\nMissing University:", df["University"].isna().sum())
print("Missing Country:", df["Country"].isna().sum())

print("\nUnique countries:", df["Country"].nunique())

remaining_codes = [
    x for x in df["Country"].dropna().unique()
    if len(x) == 2 and x.isupper()
]

print("Remaining country codes:", len(remaining_codes))

print("\nNumeric columns:", len(df.select_dtypes(include="number").columns))
print("Text columns:", len(df.select_dtypes(include="object").columns))

print("\n==============================================")

========== FINAL DATA QUALITY CHECK ==========
Rows: 2517
Columns: 29

Duplicate rows: 0
Duplicate universities: 0

Missing University: 0
Missing Country: 0

Unique countries: 120
Remaining country codes: 0

Numeric columns: 23
Text columns: 6

==============================================

In [ ]:
output_file = "university_cleaned_data.csv"

df.to_csv(output_file, index=False)

print("Cleaned dataset saved successfully!")
print("File:", output_file)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Cleaned dataset saved successfully!
File: university_cleaned_data.csv
Rows: 2517
Columns: 29

In [ ]:
import os

print("File exists:", os.path.exists("university_cleaned_data.csv"))

File exists: True