# EduVision_DV – Higher Education Intelligence System

## Milestone 1: Data Collection and Preparation

This notebook covers the collection, validation, cleaning,
standardization, and preparation of higher-education datasets
for KPI engineering and Tableau dashboard development.

In [ ]:
import pandas as pd
import numpy as np
import os

print("Libraries imported successfully!")

Libraries imported successfully!

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"

print("Project path:")
print(PROJECT_PATH)

Project path:
/content/drive/MyDrive/EduVision_DV

In [ ]:
import os

print("Files and folders inside EduVision_DV:\n")

for item in os.listdir(PROJECT_PATH):
    print("✓", item)

Files and folders inside EduVision_DV:

✓ 02_Cleaned_Data
✓ 03_Processed_Data
✓ 04_Reports
✓ 01_Raw_Data
✓ EduVision_Milestone1_Data_Preparation.ipynb

In [ ]:
folders = [
    "01_Raw_Data",
    "02_Cleaned_Data",
    "03_Processed_Data",
    "04_Reports"
]

for folder in folders:
    folder_path = os.path.join(PROJECT_PATH, folder)
    os.makedirs(folder_path, exist_ok=True)

print("All project folders created successfully!")

All project folders created successfully!

In [ ]:
print("EduVision_DV contents:\n")

for item in os.listdir(PROJECT_PATH):
    print("✓", item)

EduVision_DV contents:

✓ 01_Raw_Data
✓ 02_Cleaned_Data
✓ 03_Processed_Data
✓ 04_Reports
✓ EduVision_Milestone1_Data_Preparation.ipynb

In [ ]:
RAW_PATH = os.path.join(PROJECT_PATH, "01_Raw_Data")

print("Raw data folder:")
print(RAW_PATH)

Raw data folder:
/content/drive/MyDrive/EduVision_DV/01_Raw_Data

In [ ]:
RAW_PATH = os.path.join(PROJECT_PATH, "01_Raw_Data")

print("Files in 01_Raw_Data:\n")

for item in os.listdir(RAW_PATH):
    print("✓", item)

Files in 01_Raw_Data:

✓ QS World University Rankings 2025 (Top global universities).csv
✓ TIMES_WorldUniversityRankings_2024.csv
✓ World University Rankings 2023.csv
✓ edstats-csv-zip-32-mb-.zip

In [ ]:
print("Raw datasets:\n")

for item in os.listdir(RAW_PATH):
    file_path = os.path.join(RAW_PATH, item)
    print(f"{item}  →  {os.path.splitext(item)[1]}")

Raw datasets:

QS World University Rankings 2025 (Top global universities).csv  →  .csv
TIMES_WorldUniversityRankings_2024.csv  →  .csv
World University Rankings 2023.csv  →  .csv
edstats-csv-zip-32-mb-.zip  →  .zip

In [ ]:
qs_files = [
    f for f in os.listdir(RAW_PATH)
    if "QS" in f.upper()
]

print("QS file(s) found:")
for file in qs_files:
    print("✓", file)

QS file(s) found:
✓ QS World University Rankings 2025 (Top global universities).csv

In [ ]:
QS_FILE = os.path.join(RAW_PATH, qs_files[0])

print("QS dataset:")
print(QS_FILE)

QS dataset:
/content/drive/MyDrive/EduVision_DV/01_Raw_Data/QS World University Rankings 2025 (Top global universities).csv

In [ ]:
qs_df = pd.read_csv(QS_FILE, encoding="latin1")

print("QS dataset loaded successfully!")
print("Rows:", qs_df.shape[0])
print("Columns:", qs_df.shape[1])

QS dataset loaded successfully!
Rows: 1503
Columns: 28

In [ ]:
print("QS 2025 Column Names:")
print("-" * 30)

for i, column in enumerate(qs_df.columns, start=1):
    print(f"{i}. {column}")

QS 2025 Column Names:
------------------------------
1. RANK_2025
2. RANK_2024
3. Institution_Name
4. Location
5. Region
6. SIZE
7. FOCUS
8. RES.
9. STATUS
10. Academic_Reputation_Score
11. Academic_Reputation_Rank
12. Employer_Reputation_Score
13. Employer_Reputation_Rank
14. Faculty_Student_Score
15. Faculty_Student_Rank
16. Citations_per_Faculty_Score
17. Citations_per_Faculty_Rank
18. International_Faculty_Score
19. International_Faculty_Rank
20. International_Students_Score
21. International_Students_Rank
22. International_Research_Network_Score
23. International_Research_Network_Rank
24. Employment_Outcomes_Score
25. Employment_Outcomes_Rank
26. Sustainability_Score
27. Sustainability_Rank
28. Overall_Score

In [ ]:
print("QS 2025 - First 5 Rows")
print("=" * 50)

display(qs_df.head())

QS 2025 - First 5 Rows
==================================================

,RANK_2025,RANK_2024,Institution_Name,Location,Region,SIZE,FOCUS,RES.,STATUS,Academic_Reputation_Score,...,International_Faculty_Rank,International_Students_Score,International_Students_Rank,International_Research_Network_Score,International_Research_Network_Rank,Employment_Outcomes_Score,Employment_Outcomes_Rank,Sustainability_Score,Sustainability_Rank,Overall_Score
0,1,1,Massachusetts Institute of Technology (MIT),United States,Americas,M,CO,VH,B,100.0,...,100,86.8,143,96.0,58,100.0,8,99.0,15=,100
1,2,6,Imperial College London,United Kingdom,Europe,L,FC,VH,A,98.5,...,66,99.6,44,97.4,34,93.4,61,99.7,6,98.5
2,3,3,University of Oxford,United Kingdom,Europe,L,FC,VH,A,100.0,...,120,97.7,73,100.0,1,100.0,3,85.0,126,96.9
3,4,4,Harvard University,United States,Americas,L,FC,VH,B,100.0,...,269,69.0,215,99.6,5,100.0,1,84.4,130,96.8
4,5,2,University of Cambridge,United Kingdom,Europe,L,FC,VH,A,100.0,...,73,94.8,98,99.3,10,100.0,5,84.8,127=,96.7

In [ ]:
print("QS 2025 - Data Types")
print("=" * 50)

print(qs_df.dtypes)

QS 2025 - Data Types
==================================================
RANK_2025                                object
RANK_2024                                object
Institution_Name                         object
Location                                 object
Region                                   object
SIZE                                     object
FOCUS                                    object
RES.                                     object
STATUS                                   object
Academic_Reputation_Score               float64
Academic_Reputation_Rank                 object
Employer_Reputation_Score               float64
Employer_Reputation_Rank                 object
Faculty_Student_Score                   float64
Faculty_Student_Rank                     object
Citations_per_Faculty_Score             float64
Citations_per_Faculty_Rank               object
International_Faculty_Score             float64
International_Faculty_Rank               object
International_Students_Score            float64
International_Students_Rank              object
International_Research_Network_Score    float64
International_Research_Network_Rank      object
Employment_Outcomes_Score               float64
Employment_Outcomes_Rank                 object
Sustainability_Score                    float64
Sustainability_Rank                      object
Overall_Score                            object
dtype: object

In [ ]:
print("QS 2025 - Sample Values")
print("=" * 50)

print("\nRANK_2025:")
print(qs_df["RANK_2025"].head(10).to_list())

print("\nRANK_2024:")
print(qs_df["RANK_2024"].head(10).to_list())

print("\nOverall_Score:")
print(qs_df["Overall_Score"].head(10).to_list())

QS 2025 - Sample Values
==================================================

RANK_2025:
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

RANK_2024:
['1', '6', '3', '4', '2', '5', '7', '8', '9', '15']

Overall_Score:
['100', '98.5', '96.9', '96.8', '96.7', '96.1', '93.9', '93.7', '91.6', '90.9']

In [ ]:
print("QS 2025 - Checking Non-Numeric Values")
print("=" * 50)

columns_to_check = ["RANK_2025", "RANK_2024", "Overall_Score"]

for column in columns_to_check:
    numeric_values = pd.to_numeric(qs_df[column], errors="coerce")

    non_numeric = qs_df.loc[
        qs_df[column].notna() & numeric_values.isna(),
        column
    ].unique()

    print(f"\n{column}:")

    if len(non_numeric) == 0:
        print("No non-numeric values found.")
    else:
        print("Non-numeric values found:")
        print(non_numeric)

QS 2025 - Checking Non-Numeric Values
==================================================

RANK_2025:
Non-numeric values found:
['621-630' '601-610' '611-620' '631-640' '641-650' '651-660' '661-670'
 '671-680' '681-690' '691-700' '701-710' '711-720' '721-730' '731-740'
 '741-750' '751-760' '761-770' '771-780' '781-790' '791-800' '801-850'
 '851-900' '901-950' '951-1000' '1001-1200' '1201-1400' '1401+']

RANK_2024:
Non-numeric values found:
['1401+' '621-630' '701-710' '611-620' '641-650' '1201-1400' '731-740'
 '691-700' '601-610' '741-750' '671-680' '651-660' '631-640' '771-780'
 '721-730' '661-670' '761-770' '681-690' '711-720' '751-760' '801-850'
 '781-790' '791-800' '851-900' '951-1000' '901-950' '1001-1200']

Overall_Score:
Non-numeric values found:
['-']

In [ ]:
print("QS 2025 - Missing Values")
print("=" * 50)

missing_values = qs_df.isnull().sum()

print(missing_values)

QS 2025 - Missing Values
==================================================
RANK_2025                                 0
RANK_2024                                21
Institution_Name                          0
Location                                  0
Region                                    0
SIZE                                      0
FOCUS                                     0
RES.                                      0
STATUS                                   37
Academic_Reputation_Score                 0
Academic_Reputation_Rank                  0
Employer_Reputation_Score                 0
Employer_Reputation_Rank                  0
Faculty_Student_Score                     0
Faculty_Student_Rank                      0
Citations_per_Faculty_Score               0
Citations_per_Faculty_Rank                0
International_Faculty_Score             100
International_Faculty_Rank              100
International_Students_Score             58
International_Students_Rank              58
International_Research_Network_Score      1
International_Research_Network_Rank       1
Employment_Outcomes_Score                 0
Employment_Outcomes_Rank                  0
Sustainability_Score                     19
Sustainability_Rank                      19
Overall_Score                           902
dtype: int64

In [ ]:
print("QS 2025 - Missing Value Percentage")
print("=" * 50)

missing_percentage = (qs_df.isnull().sum() / len(qs_df)) * 100

print(missing_percentage.round(2))

QS 2025 - Missing Value Percentage
==================================================
RANK_2025                                0.00
RANK_2024                                1.40
Institution_Name                         0.00
Location                                 0.00
Region                                   0.00
SIZE                                     0.00
FOCUS                                    0.00
RES.                                     0.00
STATUS                                   2.46
Academic_Reputation_Score                0.00
Academic_Reputation_Rank                 0.00
Employer_Reputation_Score                0.00
Employer_Reputation_Rank                 0.00
Faculty_Student_Score                    0.00
Faculty_Student_Rank                     0.00
Citations_per_Faculty_Score              0.00
Citations_per_Faculty_Rank               0.00
International_Faculty_Score              6.65
International_Faculty_Rank               6.65
International_Students_Score             3.86
International_Students_Rank              3.86
International_Research_Network_Score     0.07
International_Research_Network_Rank      0.07
Employment_Outcomes_Score                0.00
Employment_Outcomes_Rank                 0.00
Sustainability_Score                     1.26
Sustainability_Rank                      1.26
Overall_Score                           60.01
dtype: float64

In [ ]:
print("QS 2025 - Special Missing Values")
print("=" * 50)

print("Overall_Score values containing '-':")
print((qs_df["Overall_Score"] == "-").sum())

QS 2025 - Special Missing Values
==================================================
Overall_Score values containing '-':
1

In [ ]:
print("QS 2025 - Duplicate University Check")
print("=" * 50)

duplicate_count = qs_df["Institution_Name"].duplicated().sum()

print("Duplicate university names:", duplicate_count)

QS 2025 - Duplicate University Check
==================================================
Duplicate university names: 0

In [ ]:
print("QS 2025 - Duplicate Row Check")
print("=" * 50)

duplicate_rows = qs_df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

QS 2025 - Duplicate Row Check
==================================================
Duplicate rows: 0

In [ ]:
print("QS 2025 - Blank Text Value Check")
print("=" * 50)

text_columns = qs_df.select_dtypes(include="object").columns

for column in text_columns:
    blank_count = qs_df[column].astype(str).str.strip().eq("").sum()
    if blank_count > 0:
        print(f"{column}: {blank_count} blank values")

print("Blank text value check completed.")

QS 2025 - Blank Text Value Check
==================================================
Blank text value check completed.

In [ ]:
print("QS 2025 - Categorical Value Check")
print("=" * 50)

categorical_columns = ["Region", "SIZE", "FOCUS", "STATUS"]

for column in categorical_columns:
    print(f"\n{column}:")
    print(qs_df[column].value_counts(dropna=False))

QS 2025 - Categorical Value Check
==================================================

Region:
Region
Asia              501
Europe            497
Americas          418
Oceania            46
Africa             40
Not Classified      1
Name: count, dtype: int64

SIZE:
SIZE
L     691
M     372
XL    352
S      88
Name: count, dtype: int64

FOCUS:
FOCUS
FC    592
CO    480
FO    353
SP     78
Name: count, dtype: int64

STATUS:
STATUS
A      1165
B       249
C        52
NaN      37
Name: count, dtype: int64

In [ ]:
print("QS 2025 - Score Range Check")
print("=" * 50)

score_columns = [
    "Academic_Reputation_Score",
    "Employer_Reputation_Score",
    "Faculty_Student_Score",
    "Citations_per_Faculty_Score",
    "International_Faculty_Score",
    "International_Students_Score",
    "International_Research_Network_Score",
    "Employment_Outcomes_Score",
    "Sustainability_Score"
]

for column in score_columns:
    print(f"{column}:")
    print("  Minimum:", qs_df[column].min())
    print("  Maximum:", qs_df[column].max())

QS 2025 - Score Range Check
==================================================
Academic_Reputation_Score:
  Minimum: 1.3
  Maximum: 100.0
Employer_Reputation_Score:
  Minimum: 1.1
  Maximum: 100.0
Faculty_Student_Score:
  Minimum: 1.0
  Maximum: 100.0
Citations_per_Faculty_Score:
  Minimum: 1.0
  Maximum: 100.0
International_Faculty_Score:
  Minimum: 1.0
  Maximum: 100.0
International_Students_Score:
  Minimum: 1.0
  Maximum: 100.0
International_Research_Network_Score:
  Minimum: 1.0
  Maximum: 100.0
Employment_Outcomes_Score:
  Minimum: 1.2
  Maximum: 100.0
Sustainability_Score:
  Minimum: 1.0
  Maximum: 100.0

In [ ]:
print("QS 2025 - Ranking Value Check")
print("=" * 50)

rank_columns = [
    "RANK_2025",
    "RANK_2024",
    "Academic_Reputation_Rank",
    "Employer_Reputation_Rank",
    "Faculty_Student_Rank",
    "Citations_per_Faculty_Rank",
    "International_Faculty_Rank",
    "International_Students_Rank",
    "International_Research_Network_Rank",
    "Employment_Outcomes_Rank",
    "Sustainability_Rank"
]

for column in rank_columns:
    print(f"\n{column}:")
    print("Unique values:", qs_df[column].nunique(dropna=True))
    print("Missing values:", qs_df[column].isna().sum())

QS 2025 - Ranking Value Check
==================================================

RANK_2025:
Unique values: 388
Missing values: 0

RANK_2024:
Unique values: 378
Missing values: 21

Academic_Reputation_Rank:
Unique values: 601
Missing values: 0

Employer_Reputation_Rank:
Unique values: 601
Missing values: 0

Faculty_Student_Rank:
Unique values: 683
Missing values: 0

Citations_per_Faculty_Rank:
Unique values: 699
Missing values: 0

International_Faculty_Rank:
Unique values: 680
Missing values: 100

International_Students_Rank:
Unique values: 690
Missing values: 58

International_Research_Network_Rank:
Unique values: 701
Missing values: 1

Employment_Outcomes_Rank:
Unique values: 695
Missing values: 0

Sustainability_Rank:
Unique values: 340
Missing values: 19

In [ ]:
print("QS 2025 - University Name Check")
print("=" * 50)

print("Missing university names:", qs_df["Institution_Name"].isna().sum())

print("Blank university names:",
      qs_df["Institution_Name"].astype(str).str.strip().eq("").sum())

print("\nUniversity names with leading/trailing spaces:")

space_issues = qs_df[
    qs_df["Institution_Name"] != qs_df["Institution_Name"].str.strip()
]

print("Count:", len(space_issues))

if len(space_issues) > 0:
    print(space_issues["Institution_Name"].head(10).to_list())

QS 2025 - University Name Check
==================================================
Missing university names: 0
Blank university names: 0

University names with leading/trailing spaces:
Count: 105
['Massachusetts Institute of Technology (MIT) ', 'KTH Royal Institute of Technology ', 'Erasmus University Rotterdam ', 'Université de Montréal ', 'Universiti Teknologi Malaysia ', 'Maastricht University ', 'University of Warsaw ', 'University of Lisbon ', 'Beijing Normal University ', 'Radboud University ']

In [ ]:
print("QS 2025 - Location Check")
print("=" * 50)

print("Missing locations:", qs_df["Location"].isna().sum())

print("Blank locations:",
      qs_df["Location"].astype(str).str.strip().eq("").sum())

print("\nNumber of unique locations:",
      qs_df["Location"].nunique(dropna=True))

print("\nSample location values:")
print(qs_df["Location"].dropna().unique()[:30])

QS 2025 - Location Check
==================================================
Missing locations: 0
Blank locations: 0

Number of unique locations: 106

Sample location values:
['United States' 'United Kingdom' 'Switzerland' 'Singapore' 'Australia'
 'China (Mainland)' 'Hong Kong SAR' 'France' 'Canada' 'Germany'
 'South Korea' 'Japan' 'Netherlands' 'Malaysia' 'Belgium' 'New Zealand'
 'Taiwan' 'Argentina' 'Sweden' 'Ireland' 'Brazil' 'Chile' 'Russia'
 'Mexico' 'Denmark' 'Saudi Arabia' 'Italy' 'Finland' 'India' 'Norway']

In [ ]:
print("QS 2025 - Location Formatting Check")
print("=" * 50)

location_space_issues = qs_df[
    qs_df["Location"] != qs_df["Location"].str.strip()
]

print("Locations with leading/trailing spaces:",
      len(location_space_issues))

if len(location_space_issues) > 0:
    print("\nExamples:")
    print(location_space_issues["Location"].unique()[:20])

QS 2025 - Location Formatting Check
==================================================
Locations with leading/trailing spaces: 0

In [ ]:
print("QS 2025 - Text Formatting Check")
print("=" * 50)

text_columns = qs_df.select_dtypes(include="object").columns

for column in text_columns:
    space_issues = (
        qs_df[column].notna() &
        (qs_df[column] != qs_df[column].str.strip())
    ).sum()

    if space_issues > 0:
        print(f"{column}: {space_issues} values with leading/trailing spaces")

QS 2025 - Text Formatting Check
==================================================
Institution_Name: 105 values with leading/trailing spaces

In [ ]:
print("QS 2025 - Capitalization Check")
print("=" * 50)

categorical_columns = ["Region", "SIZE", "FOCUS", "STATUS"]

for column in categorical_columns:
    print(f"\n{column}:")
    print(qs_df[column].dropna().unique())

QS 2025 - Capitalization Check
==================================================

Region:
['Americas' 'Europe' 'Asia' 'Oceania' 'Africa' 'Not Classified']

SIZE:
['M' 'L' 'XL' 'S']

FOCUS:
['CO' 'FC' 'FO' 'SP']

STATUS:
['B' 'A' 'C']

In [ ]:
print("Creating QS 2025 cleaning copy...")
print("=" * 50)

qs_clean = qs_df.copy()

print("Original rows:", len(qs_df))
print("Cleaning copy rows:", len(qs_clean))

print("\nQS cleaning copy created successfully.")

Creating QS 2025 cleaning copy...
==================================================
Original rows: 1503
Cleaning copy rows: 1503

QS cleaning copy created successfully.

In [ ]:
print("QS 2025 - Cleaning University Names")
print("=" * 50)

qs_clean["Institution_Name"] = qs_clean["Institution_Name"].str.strip()

print("University names cleaned successfully.")

QS 2025 - Cleaning University Names
==================================================
University names cleaned successfully.

In [ ]:
print("QS 2025 - Verify University Name Cleaning")
print("=" * 50)

remaining_spaces = (
    qs_clean["Institution_Name"] != qs_clean["Institution_Name"].str.strip()
).sum()

print("University names with leading/trailing spaces:", remaining_spaces)

QS 2025 - Verify University Name Cleaning
==================================================
University names with leading/trailing spaces: 0

In [ ]:
print("QS 2025 - Cleaning Overall Score")
print("=" * 50)

qs_clean["Overall_Score"] = qs_clean["Overall_Score"].replace("-", pd.NA)

qs_clean["Overall_Score"] = pd.to_numeric(
    qs_clean["Overall_Score"],
    errors="coerce"
)

print("Overall_Score converted to numeric.")
print("Missing Overall_Score values:", qs_clean["Overall_Score"].isna().sum())

QS 2025 - Cleaning Overall Score
==================================================
Overall_Score converted to numeric.
Missing Overall_Score values: 903

In [ ]:
print("QS 2025 - Verify Overall Score")
print("=" * 50)

print("Data type:", qs_clean["Overall_Score"].dtype)
print("Missing values:", qs_clean["Overall_Score"].isna().sum())

QS 2025 - Verify Overall Score
==================================================
Data type: float64
Missing values: 903

In [ ]:
print("QS 2025 - Cleaning Score Columns")
print("=" * 50)

score_columns = [
    "Academic_Reputation_Score",
    "Employer_Reputation_Score",
    "Faculty_Student_Score",
    "Citations_per_Faculty_Score",
    "International_Faculty_Score",
    "International_Students_Score",
    "International_Research_Network_Score",
    "Employment_Outcomes_Score",
    "Sustainability_Score"
]

for column in score_columns:
    qs_clean[column] = pd.to_numeric(
        qs_clean[column],
        errors="coerce"
    )

print("All score columns converted to numeric.")

QS 2025 - Cleaning Score Columns
==================================================
All score columns converted to numeric.

In [ ]:
print("QS 2025 - Verify Score Data Types")
print("=" * 50)

for column in score_columns:
    print(f"{column}: {qs_clean[column].dtype}")

QS 2025 - Verify Score Data Types
==================================================
Academic_Reputation_Score: float64
Employer_Reputation_Score: float64
Faculty_Student_Score: float64
Citations_per_Faculty_Score: float64
International_Faculty_Score: float64
International_Students_Score: float64
International_Research_Network_Score: float64
Employment_Outcomes_Score: float64
Sustainability_Score: float64

In [ ]:
print("QS 2025 - Cleaning Ranking Columns")
print("=" * 50)

rank_columns = [
    "RANK_2025",
    "RANK_2024",
    "Academic_Reputation_Rank",
    "Employer_Reputation_Rank",
    "Faculty_Student_Rank",
    "Citations_per_Faculty_Rank",
    "International_Faculty_Rank",
    "International_Students_Rank",
    "International_Research_Network_Rank",
    "Employment_Outcomes_Rank",
    "Sustainability_Rank"
]

for column in rank_columns:
    qs_clean[column] = qs_clean[column].str.strip()

print("Ranking columns cleaned successfully.")

QS 2025 - Cleaning Ranking Columns
==================================================
Ranking columns cleaned successfully.

In [ ]:
print("QS 2025 - Verify Ranking Columns")
print("=" * 50)

for column in rank_columns:
    print(f"{column}: {qs_clean[column].dtype}")

QS 2025 - Verify Ranking Columns
==================================================
RANK_2025: object
RANK_2024: object
Academic_Reputation_Rank: object
Employer_Reputation_Rank: object
Faculty_Student_Rank: object
Citations_per_Faculty_Rank: object
International_Faculty_Rank: object
International_Students_Rank: object
International_Research_Network_Rank: object
Employment_Outcomes_Rank: object
Sustainability_Rank: object

In [ ]:
print("QS 2025 - Missing STATUS Inspection")
print("=" * 50)

missing_status = qs_clean[qs_clean["STATUS"].isna()]

print("Number of missing STATUS values:", len(missing_status))

print("\nUniversities with missing STATUS:")
print(missing_status[["Institution_Name", "Location", "Region", "STATUS"]].head(20))

QS 2025 - Missing STATUS Inspection
==================================================
Number of missing STATUS values: 37

Universities with missing STATUS:
                                   Institution_Name  \
356                        University of Luxembourg
379    Technische Universität Bergakademie Freiberg
439   Singapore University of Technology and Design
490                Isfahan University of Technology
549                           University of Iceland
691     Norwegian University of Life Sciences (UMB)
770                          Addis Ababa University
791                   Zürcher Hochschule Winterthur
848                         University of Stavanger
879                       Universidad de Valladolid
920                   Osaka Metropolitan University
984                 Universidad de Córdoba - España
986                             Universidad de León
992                  Université Sorbonne Paris Nord
1147                          Universitat de Lleida
1164                           University of Deusto
1166                           University of Ibadan
1168                         University of Ioannina
1171                            University of Lagos
1233                        Fundación CEU San Pablo

                       Location  Region STATUS
356                  Luxembourg  Europe    NaN
379                     Germany  Europe    NaN
439                   Singapore    Asia    NaN
490   Iran, Islamic Republic of    Asia    NaN
549                     Iceland  Europe    NaN
691                      Norway  Europe    NaN
770                    Ethiopia  Africa    NaN
791                 Switzerland  Europe    NaN
848                      Norway  Europe    NaN
879                       Spain  Europe    NaN
920                       Japan    Asia    NaN
984                       Spain  Europe    NaN
986                       Spain  Europe    NaN
992                      France  Europe    NaN
1147                      Spain  Europe    NaN
1164                      Spain  Europe    NaN
1166                    Nigeria  Africa    NaN
1168                     Greece  Europe    NaN
1171                    Nigeria  Africa    NaN
1233                      Spain  Europe    NaN

In [ ]:
print("QS 2025 - STATUS Missing Value Handling")
print("=" * 50)

status_missing_before = qs_clean["STATUS"].isna().sum()

print("Missing STATUS values preserved:", status_missing_before)
print("STATUS values will remain missing because the source does not provide them.")

QS 2025 - STATUS Missing Value Handling
==================================================
Missing STATUS values preserved: 37
STATUS values will remain missing because the source does not provide them.

In [ ]:
print("QS 2025 - Not Classified Region Inspection")
print("=" * 50)

not_classified = qs_clean[
    qs_clean["Region"] == "Not Classified"
]

print(not_classified[
    ["Institution_Name", "Location", "Region"]
])

QS 2025 - Not Classified Region Inspection
==================================================
                     Institution_Name         Location          Region
616  Eastern Mediterranean University  Northern Cyprus  Not Classified

In [ ]:
print("QS 2025 - Verify Categorical Cleaning")
print("=" * 50)

print("Missing STATUS values:", qs_clean["STATUS"].isna().sum())

print("\nRegion values:")
print(qs_clean["Region"].value_counts(dropna=False))

print("\nSTATUS values:")
print(qs_clean["STATUS"].value_counts(dropna=False))

QS 2025 - Verify Categorical Cleaning
==================================================
Missing STATUS values: 37

Region values:
Region
Asia              501
Europe            497
Americas          418
Oceania            46
Africa             40
Not Classified      1
Name: count, dtype: int64

STATUS values:
STATUS
A      1165
B       249
C        52
NaN      37
Name: count, dtype: int64

In [ ]:
print("QS 2025 - Final Structure Check")
print("=" * 50)

print("Original rows:", qs_df.shape[0])
print("Cleaned rows:", qs_clean.shape[0])

print("Original columns:", qs_df.shape[1])
print("Cleaned columns:", qs_clean.shape[1])

print("\nRows unchanged:", qs_df.shape[0] == qs_clean.shape[0])
print("Columns unchanged:", qs_df.shape[1] == qs_clean.shape[1])

QS 2025 - Final Structure Check
==================================================
Original rows: 1503
Cleaned rows: 1503
Original columns: 28
Cleaned columns: 28

Rows unchanged: True
Columns unchanged: True

In [ ]:
print("QS 2025 - Final Data Quality Check")
print("=" * 50)

print("University name spacing issues:",
      (qs_clean["Institution_Name"] != qs_clean["Institution_Name"].str.strip()).sum())

print("Overall_Score data type:",
      qs_clean["Overall_Score"].dtype)

print("Overall_Score missing values:",
      qs_clean["Overall_Score"].isna().sum())

print("Total rows:",
      len(qs_clean))

print("Total columns:",
      len(qs_clean.columns))

QS 2025 - Final Data Quality Check
==================================================
University name spacing issues: 0
Overall_Score data type: float64
Overall_Score missing values: 903
Total rows: 1503
Total columns: 28

In [ ]:
CLEANED_PATH = os.path.join(PROJECT_PATH, "02_Cleaned_Data")

QS_CLEANED_FILE = os.path.join(
    CLEANED_PATH,
    "QS_2025_Cleaned.csv"
)

qs_clean.to_csv(
    QS_CLEANED_FILE,
    index=False,
    encoding="utf-8"
)

print("QS 2025 cleaned dataset saved successfully.")
print("Saved to:", QS_CLEANED_FILE)

QS 2025 cleaned dataset saved successfully.
Saved to: /content/drive/MyDrive/EduVision_DV/02_Cleaned_Data/QS_2025_Cleaned.csv

In [ ]:
print("QS 2025 Cleaned File Verification")
print("=" * 40)

print("File exists:", os.path.exists(QS_CLEANED_FILE))

verified_qs = pd.read_csv(QS_CLEANED_FILE)

print("Rows:", len(verified_qs))
print("Columns:", len(verified_qs.columns))

QS 2025 Cleaned File Verification
========================================
File exists: True
Rows: 1503
Columns: 28

In [ ]:
the_files = [
    f for f in os.listdir(RAW_PATH)
    if "TIMES" in f.upper()
]

print("THE 2024 files found:")
for f in the_files:
    print("-", f)

THE 2024 files found:
- TIMES_WorldUniversityRankings_2024.csv

In [ ]:
THE_FILE = os.path.join(RAW_PATH, the_files[0])

the_df = pd.read_csv(THE_FILE)

print("THE 2024 dataset loaded successfully.")
print("Rows:", len(the_df))
print("Columns:", len(the_df.columns))

THE 2024 dataset loaded successfully.
Rows: 2673
Columns: 29

In [ ]:
print("THE 2024 - Dataset Structure")
print("=" * 50)

print("\nColumn names:")
for i, column in enumerate(the_df.columns, start=1):
    print(i, "-", column)

print("\nFirst 5 rows:")
display(the_df.head())

THE 2024 - Dataset Structure
==================================================

Column names:
1 - rank
2 - name
3 - scores_overall
4 - scores_overall_rank
5 - scores_teaching
6 - scores_teaching_rank
7 - scores_research
8 - scores_research_rank
9 - scores_citations
10 - scores_citations_rank
11 - scores_industry_income
12 - scores_industry_income_rank
13 - scores_international_outlook
14 - scores_international_outlook_rank
15 - record_type
16 - member_level
17 - url
18 - nid
19 - location
20 - stats_number_students
21 - stats_student_staff_ratio
22 - stats_pc_intl_students
23 - stats_female_male_ratio
24 - aliases
25 - subjects_offered
26 - closed
27 - unaccredited
28 - disabled
29 - website_url

First 5 rows:

,rank,name,scores_overall,scores_overall_rank,scores_teaching,scores_teaching_rank,scores_research,scores_research_rank,scores_citations,scores_citations_rank,...,stats_number_students,stats_student_staff_ratio,stats_pc_intl_students,stats_female_male_ratio,aliases,subjects_offered,closed,unaccredited,disabled,website_url
0,1,University of Oxford,98.5,10,96.6,5,100.0,2,99.0,5,...,"21,750",10.9,42%,49 : 51,University of Oxford,"Geography,Chemistry,Chemical Engineering,Biolo...",False,False,False,https://www.timeshighereducation.com/student/r...
1,2,Stanford University,98.0,20,99.0,1,97.8,8,99.6,2,...,"14,517",6.4,23%,47 : 53,Stanford University,"Computer Science,Communication & Media Studies...",False,False,False,NaN
2,3,Massachusetts Institute of Technology,97.9,30,98.6,2,96.2,11,99.7,1,...,"11,085",8.0,33%,41 : 59,Massachusetts Institute of Technology,"Architecture,Economics & Econometrics,Archaeol...",False,False,False,https://www.timeshighereducation.com/student/r...
3,4,Harvard University,97.8,40,97.7,3,99.9,3,99.4,3,...,"20,050",9.0,25%,51 : 49,Harvard University,"Sociology,Architecture,Physics & Astronomy,Psy...",False,False,False,https://www.timeshighereducation.com/student/r...
4,5,University of Cambridge,97.5,50,95.8,7,100.0,1,98.0,12,...,"20,565",11.5,38%,48 : 52,University of Cambridge,Politics & International Studies (incl Develop...,False,False,False,https://www.timeshighereducation.com/student/r...

In [ ]:
print("THE 2024 - Data Types")
print("=" * 50)

print(the_df.dtypes)

THE 2024 - Data Types
==================================================
rank                                  object
name                                  object
scores_overall                        object
scores_overall_rank                    int64
scores_teaching                      float64
scores_teaching_rank                   int64
scores_research                      float64
scores_research_rank                   int64
scores_citations                     float64
scores_citations_rank                  int64
scores_industry_income               float64
scores_industry_income_rank            int64
scores_international_outlook         float64
scores_international_outlook_rank      int64
record_type                           object
member_level                           int64
url                                   object
nid                                    int64
location                              object
stats_number_students                 object
stats_student_staff_ratio            float64
stats_pc_intl_students                object
stats_female_male_ratio               object
aliases                               object
subjects_offered                      object
closed                                  bool
unaccredited                            bool
disabled                                bool
website_url                           object
dtype: object

In [ ]:
print("THE 2024 - Missing Values")
print("=" * 50)

missing_counts = the_df.isna().sum()

print(missing_counts[missing_counts > 0])

THE 2024 - Missing Values
==================================================
scores_overall                   769
scores_teaching                  769
scores_research                  769
scores_citations                 769
scores_industry_income           769
scores_international_outlook     769
stats_female_male_ratio           93
subjects_offered                   4
website_url                     2329
dtype: int64

In [ ]:
print("THE 2024 - Duplicate Check")
print("=" * 50)

print("Duplicate university names:",
      the_df["name"].duplicated().sum())

print("Duplicate complete rows:",
      the_df.duplicated().sum())

THE 2024 - Duplicate Check
==================================================
Duplicate university names: 0
Duplicate complete rows: 0

In [ ]:
print("THE 2024 - Blank Text Check")
print("=" * 50)

text_columns = the_df.select_dtypes(include="object").columns

for column in text_columns:
    blank_count = the_df[column].fillna("").str.strip().eq("").sum()
    if blank_count > 0:
        print(column, ":", blank_count)

THE 2024 - Blank Text Check
==================================================
scores_overall : 769
stats_female_male_ratio : 93
subjects_offered : 4
website_url : 2329

In [ ]:
print("THE 2024 - Categorical Values")
print("=" * 50)

for column in ["record_type", "member_level", "closed", "unaccredited", "disabled"]:
    print(f"\n{column}:")
    print(the_df[column].value_counts(dropna=False))

THE 2024 - Categorical Values
==================================================

record_type:
record_type
master_account    2509
public             106
private             58
Name: count, dtype: int64

member_level:
member_level
0     2492
11      98
6       62
1       21
Name: count, dtype: int64

closed:
closed
False    2673
Name: count, dtype: int64

unaccredited:
unaccredited
False    2672
True        1
Name: count, dtype: int64

disabled:
disabled
False    2557
True      116
Name: count, dtype: int64

In [ ]:
print("THE 2024 - Score Range Check")
print("=" * 50)

score_columns = [
    "scores_overall",
    "scores_teaching",
    "scores_research",
    "scores_citations",
    "scores_industry_income",
    "scores_international_outlook"
]

for column in score_columns:
    numeric_values = pd.to_numeric(the_df[column], errors="coerce")

    print(
        f"{column}: "
        f"Min = {numeric_values.min()}, "
        f"Max = {numeric_values.max()}"
    )

THE 2024 - Score Range Check
==================================================
scores_overall: Min = 58.7, Max = 98.5
scores_teaching: Min = 9.4, Max = 99.0
scores_research: Min = 4.6, Max = 100.0
scores_citations: Min = 3.4, Max = 99.7
scores_industry_income: Min = 15.6, Max = 100.0
scores_international_outlook: Min = 16.1, Max = 98.8

In [ ]:
print("THE 2024 - Ranking Check")
print("=" * 50)

rank_columns = [
    "rank",
    "scores_overall_rank",
    "scores_teaching_rank",
    "scores_research_rank",
    "scores_citations_rank",
    "scores_industry_income_rank",
    "scores_international_outlook_rank"
]

for column in rank_columns:
    print(
        f"{column}: "
        f"Unique = {the_df[column].nunique()}, "
        f"Missing = {the_df[column].isna().sum()}"
    )

THE 2024 - Ranking Check
==================================================
rank: Unique = 160, Missing = 0
scores_overall_rank: Unique = 2673, Missing = 0
scores_teaching_rank: Unique = 1905, Missing = 0
scores_research_rank: Unique = 1905, Missing = 0
scores_citations_rank: Unique = 1905, Missing = 0
scores_industry_income_rank: Unique = 1905, Missing = 0
scores_international_outlook_rank: Unique = 1905, Missing = 0

In [ ]:
print("THE 2024 - University Name Check")
print("=" * 50)

print("Missing names:",
      the_df["name"].isna().sum())

print("Blank names:",
      the_df["name"].fillna("").str.strip().eq("").sum())

print("Names with leading/trailing spaces:",
      (the_df["name"] != the_df["name"].str.strip()).sum())

THE 2024 - University Name Check
==================================================
Missing names: 0
Blank names: 0
Names with leading/trailing spaces: 0

In [ ]:
the_clean = the_df.copy()

print("THE 2024 cleaning copy created successfully.")
print("Original rows:", len(the_df))
print("Cleaning copy rows:", len(the_clean))

THE 2024 cleaning copy created successfully.
Original rows: 2673
Cleaning copy rows: 2673

In [ ]:
missing_columns = [
    "scores_overall",
    "stats_female_male_ratio",
    "subjects_offered",
    "website_url"
]

for column in missing_columns:
    the_clean[column] = the_clean[column].replace(r"^\s*$", pd.NA, regex=True)

print("Blank values converted to missing values.")

for column in missing_columns:
    print(column, "missing:", the_clean[column].isna().sum())

Blank values converted to missing values.
scores_overall missing: 769
stats_female_male_ratio missing: 93
subjects_offered missing: 4
website_url missing: 2329

In [ ]:
the_clean["scores_overall"] = pd.to_numeric(
    the_clean["scores_overall"],
    errors="coerce"
)

print("scores_overall data type:", the_clean["scores_overall"].dtype)
print("Missing scores_overall:", the_clean["scores_overall"].isna().sum())

scores_overall data type: float64
Missing scores_overall: 2472

In [ ]:
print("THE 2024 - Inspect scores_overall")
print("=" * 50)

print("Original non-missing values:")
print(the_df["scores_overall"].dropna().head(20).tolist())

print("\nValues that are not converting to numbers:")
original_scores = the_df["scores_overall"].dropna()

non_numeric = original_scores[
    pd.to_numeric(original_scores, errors="coerce").isna()
]

print(non_numeric.head(30).tolist())
print("\nCount of non-numeric values:", len(non_numeric))

THE 2024 - Inspect scores_overall
==================================================
Original non-missing values:
['98.5', '98.0', '97.9', '97.8', '97.5', '96.9', '96.5', '95.1', '94.6', '94.2', '93.1', '92.4', '92.1', '91.8', '91.1', '91.0', '90.9', '90.1', '90.0', '89.5']

Values that are not converting to numbers:
['55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6']

Count of non-numeric values: 1703

In [ ]:
the_clean["scores_overall"] = the_df["scores_overall"].copy()

print("scores_overall restored from original data.")
print("Data type:", the_clean["scores_overall"].dtype)
print("Missing values:", the_clean["scores_overall"].isna().sum())

print("\nSample range values:")
print(
    the_clean.loc[
        the_clean["scores_overall"].astype("string").str.contains("–", na=False),
        "scores_overall"
    ].head().tolist()
)

scores_overall restored from original data.
Data type: object
Missing values: 769

Sample range values:
['55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6', '55.9–58.6']

In [ ]:
print("THE 2024 - Student Count Check")
print("=" * 50)

print("Sample values:")
print(the_clean["stats_number_students"].head(10).tolist())

print("\nMissing values:",
      the_clean["stats_number_students"].isna().sum())

THE 2024 - Student Count Check
==================================================
Sample values:
['21,750', '14,517', '11,085', '20,050', '20,565', '7,753', '2,240', '20,275', '39,991', '11,924']

Missing values: 0

In [ ]:
the_clean["stats_number_students"] = (
    the_clean["stats_number_students"]
    .str.replace(",", "", regex=False)
    .astype(int)
)

print("stats_number_students data type:",
      the_clean["stats_number_students"].dtype)

print("Sample values:",
      the_clean["stats_number_students"].head(10).tolist())

stats_number_students data type: int64
Sample values: [21750, 14517, 11085, 20050, 20565, 7753, 2240, 20275, 39991, 11924]

In [ ]:
print("THE 2024 - International Student Percentage Check")
print("=" * 50)

print("Sample values:")
print(the_clean["stats_pc_intl_students"].head(15).tolist())

print("\nUnique formats/examples:")
print(the_clean["stats_pc_intl_students"].dropna().unique()[:20])

THE 2024 - International Student Percentage Check
==================================================
Sample values:
['42%', '23%', '33%', '25%', '38%', '23%', '33%', '61%', '22%', '21%', '43%', '10%', '36%', '14%', '28%']

Unique formats/examples:
['42%' '23%' '33%' '25%' '38%' '61%' '22%' '21%' '43%' '10%' '36%' '14%'
 '28%' '35%' '15%' '24%' '27%' '16%' '44%' '18%']

In [ ]:
the_clean["stats_pc_intl_students"] = (
    the_clean["stats_pc_intl_students"]
    .str.replace("%", "", regex=False)
    .astype(float)
)

print("Data type:",
      the_clean["stats_pc_intl_students"].dtype)

print("Sample values:",
      the_clean["stats_pc_intl_students"].head(10).tolist())

print("Missing values:",
      the_clean["stats_pc_intl_students"].isna().sum())

ValueError: could not convert string to float: ''

In [ ]:
print("THE 2024 - International Student Percentage Missing Check")
print("=" * 50)

empty_count = the_clean["stats_pc_intl_students"].eq("").sum()

print("Empty strings:", empty_count)
print("NaN values:", the_clean["stats_pc_intl_students"].isna().sum())
print("Total missing/empty:",
      empty_count + the_clean["stats_pc_intl_students"].isna().sum())

THE 2024 - International Student Percentage Missing Check
==================================================
Empty strings: 0
NaN values: 0
Total missing/empty: 0

In [ ]:
print("THE 2024 - Compare International Student Percentage")
print("=" * 50)

print("Original column dtype:", the_df["stats_pc_intl_students"].dtype)
print("Cleaning column dtype:", the_clean["stats_pc_intl_students"].dtype)

print("\nOriginal missing:", the_df["stats_pc_intl_students"].isna().sum())
print("Cleaning missing:", the_clean["stats_pc_intl_students"].isna().sum())

print("\nOriginal sample:")
print(the_df["stats_pc_intl_students"].head(10).tolist())

print("\nCleaning sample:")
print(the_clean["stats_pc_intl_students"].head(10).tolist())

THE 2024 - Compare International Student Percentage
==================================================
Original column dtype: object
Cleaning column dtype: object

Original missing: 0
Cleaning missing: 0

Original sample:
['42%', '23%', '33%', '25%', '38%', '23%', '33%', '61%', '22%', '21%']

Cleaning sample:
['42%', '23%', '33%', '25%', '38%', '23%', '33%', '61%', '22%', '21%']

In [ ]:
the_clean["stats_pc_intl_students"] = (
    the_clean["stats_pc_intl_students"]
    .astype(str)
    .str.strip()
    .str.replace("%", "", regex=False)
)

print("Data type:", the_clean["stats_pc_intl_students"].dtype)
print("Sample values:")
print(the_clean["stats_pc_intl_students"].head(10).tolist())

Data type: object
Sample values:
['42', '23', '33', '25', '38', '23', '33', '61', '22', '21']

In [ ]:
the_clean["stats_pc_intl_students"] = (
    the_df["stats_pc_intl_students"]
    .astype("string")
    .str.strip()
    .str.replace("%", "", regex=False)
    .replace("", pd.NA)
)

the_clean["stats_pc_intl_students"] = pd.to_numeric(
    the_clean["stats_pc_intl_students"],
    errors="coerce"
)

print("Data type:", the_clean["stats_pc_intl_students"].dtype)
print("Missing values:", the_clean["stats_pc_intl_students"].isna().sum())
print("Minimum:", the_clean["stats_pc_intl_students"].min())
print("Maximum:", the_clean["stats_pc_intl_students"].max())

Data type: Int64
Missing values: 3
Minimum: 0
Maximum: 100

In [ ]:
missing_intl = the_df.loc[
    the_clean["stats_pc_intl_students"].isna(),
    "stats_pc_intl_students"
]

print("Problematic values from original dataset:")
print(missing_intl.tolist())

Problematic values from original dataset:
['%', '%', '%']

In [ ]:
print("International Student Percentage Validation")
print("=" * 50)

print("Data type:", the_clean["stats_pc_intl_students"].dtype)
print("Missing values:", the_clean["stats_pc_intl_students"].isna().sum())
print("Minimum:", the_clean["stats_pc_intl_students"].min())
print("Maximum:", the_clean["stats_pc_intl_students"].max())

invalid_values = the_clean[
    (the_clean["stats_pc_intl_students"] < 0) |
    (the_clean["stats_pc_intl_students"] > 100)
]

print("Invalid percentage values:", len(invalid_values))

International Student Percentage Validation
==================================================
Data type: Int64
Missing values: 3
Minimum: 0
Maximum: 100
Invalid percentage values: 0

In [ ]:
print("THE 2024 - Female-Male Ratio")
print("=" * 50)

print("Data type:", the_clean["stats_female_male_ratio"].dtype)
print("Missing values:", the_clean["stats_female_male_ratio"].isna().sum())

print("\nSample values:")
print(the_clean["stats_female_male_ratio"].head(20).tolist())

print("\nUnique sample values:")
print(the_clean["stats_female_male_ratio"].dropna().unique()[:20])

THE 2024 - Female-Male Ratio
==================================================
Data type: object
Missing values: 93

Sample values:
['49 : 51', '47 : 53', '41 : 59', '51 : 49', '48 : 52', '47 : 53', '37 : 63', '42 : 58', '52 : 48', '51 : 49', '33 : 67', nan, '47 : 53', nan, '56 : 44', '54 : 46', nan, '56 : 44', '49 : 51', '51 : 49']

Unique sample values:
['49 : 51' '47 : 53' '41 : 59' '51 : 49' '48 : 52' '37 : 63' '42 : 58'
 '52 : 48' '33 : 67' '56 : 44' '54 : 46' '59 : 41' '44 : 56' '58 : 42'
 '61 : 39' '30 : 70' '45 : 55' '55 : 45' '34 : 66' '63 : 37']

In [ ]:
the_clean["stats_female_male_ratio"] = (
    the_clean["stats_female_male_ratio"]
    .astype("string")
    .str.replace(r"\s*:\s*", " : ", regex=True)
    .str.strip()
)

print("Data type:", the_clean["stats_female_male_ratio"].dtype)
print("Missing values:", the_clean["stats_female_male_ratio"].isna().sum())

print("\nSample values:")
print(the_clean["stats_female_male_ratio"].head(20).tolist())

Data type: string
Missing values: 93

Sample values:
['49 : 51', '47 : 53', '41 : 59', '51 : 49', '48 : 52', '47 : 53', '37 : 63', '42 : 58', '52 : 48', '51 : 49', '33 : 67', <NA>, '47 : 53', <NA>, '56 : 44', '54 : 46', <NA>, '56 : 44', '49 : 51', '51 : 49']

In [ ]:
print("THE 2024 - Subjects Offered")
print("=" * 50)

print("Data type:", the_clean["subjects_offered"].dtype)
print("Missing values:", the_clean["subjects_offered"].isna().sum())

print("\nSample values:")
print(the_clean["subjects_offered"].head(10).tolist())

print("\nNumber of unique values:", the_clean["subjects_offered"].nunique())

THE 2024 - Subjects Offered
==================================================
Data type: object
Missing values: 4

Sample values:
['Geography,Chemistry,Chemical Engineering,Biological Sciences,General Engineering,Computer Science,Art, Performing Arts & Design,Communication & Media Studies,Electrical & Electronic Engineering,Law,Economics & Econometrics,Geology, Environmental, Earth & Marine Sciences,Politics & International Studies (incl Development Studies),History, Philosophy & Theology,Medicine & Dentistry,Languages, Literature & Linguistics,Business & Management,Accounting & Finance,Mechanical & Aerospace Engineering,Mathematics & Statistics,Physics & Astronomy,Psychology,Other Health,Archaeology,Sociology,Civil Engineering,Education', 'Computer Science,Communication & Media Studies,Electrical & Electronic Engineering,Mathematics & Statistics,Education,Medicine & Dentistry,Civil Engineering,Politics & International Studies (incl Development Studies),History, Philosophy & Theology,Veterinary Science,Economics & Econometrics,Other Health,Geology, Environmental, Earth & Marine Sciences,Accounting & Finance,Mechanical & Aerospace Engineering,Chemistry,Sociology,Art, Performing Arts & Design,Chemical Engineering,Business & Management,General Engineering,Physics & Astronomy,Archaeology,Agriculture & Forestry,Law,Languages, Literature & Linguistics,Biological Sciences,Psychology', 'Architecture,Economics & Econometrics,Archaeology,Biological Sciences,Languages, Literature & Linguistics,Mechanical & Aerospace Engineering,Psychology,Politics & International Studies (incl Development Studies),History, Philosophy & Theology,Mathematics & Statistics,Civil Engineering,Geology, Environmental, Earth & Marine Sciences,General Engineering,Art, Performing Arts & Design,Other Health,Physics & Astronomy,Computer Science,Accounting & Finance,Chemical Engineering,Business & Management,Electrical & Electronic Engineering,Communication & Media Studies,Chemistry', 'Sociology,Architecture,Physics & Astronomy,Psychology,Mechanical & Aerospace Engineering,Law,Chemical Engineering,Electrical & Electronic Engineering,Medicine & Dentistry,Communication & Media Studies,Mathematics & Statistics,History, Philosophy & Theology,Languages, Literature & Linguistics,Agriculture & Forestry,Education,Computer Science,Business & Management,Geography,Accounting & Finance,Politics & International Studies (incl Development Studies),Chemistry,Archaeology,Art, Performing Arts & Design,Other Health,Biological Sciences,Geology, Environmental, Earth & Marine Sciences,Economics & Econometrics,General Engineering,Civil Engineering', 'Politics & International Studies (incl Development Studies),Biological Sciences,Business & Management,Civil Engineering,Geology, Environmental, Earth & Marine Sciences,Mathematics & Statistics,Psychology,General Engineering,Physics & Astronomy,Chemical Engineering,Chemistry,Economics & Econometrics,History, Philosophy & Theology,Computer Science,Accounting & Finance,Education,Veterinary Science,Electrical & Electronic Engineering,Geography,Other Health,Architecture,Art, Performing Arts & Design,Law,Mechanical & Aerospace Engineering,Sociology,Medicine & Dentistry,Archaeology,Languages, Literature & Linguistics', 'History, Philosophy & Theology,Agriculture & Forestry,Economics & Econometrics,Languages, Literature & Linguistics,Architecture,Sociology,General Engineering,Geology, Environmental, Earth & Marine Sciences,Other Health,Chemistry,Mechanical & Aerospace Engineering,Physics & Astronomy,Civil Engineering,Mathematics & Statistics,Electrical & Electronic Engineering,Biological Sciences,Computer Science,Politics & International Studies (incl Development Studies),Art, Performing Arts & Design,Chemical Engineering,Psychology', 'Computer Science,Chemistry,Chemical Engineering,Mathematics & Statistics,Physics & Astronomy,Economics & Econometrics,Languages, Literature & Linguistics,General Engineering,Geology, Environmental, Earth & Marine Sciences,History, Philosophy & Theology,Politics & International Studies (incl Development Studies),Mechanical & Aerospace Engineering,Civil Engineering,Biological Sciences,Electrical & Electronic Engineering,Business & Management', 'Computer Science,Mechanical & Aerospace Engineering,Chemical Engineering,Physics & Astronomy,Other Health,Mathematics & Statistics,Electrical & Electronic Engineering,Chemistry,Medicine & Dentistry,General Engineering,Geology, Environmental, Earth & Marine Sciences,Biological Sciences,Civil Engineering', 'Chemistry,Electrical & Electronic Engineering,Geology, Environmental, Earth & Marine Sciences,Computer Science,Mathematics & Statistics,Archaeology,History, Philosophy & Theology,Law,Agriculture & Forestry,Education,Communication & Media Studies,Other Health,Art, Performing Arts & Design,Civil Engineering,Mechanical & Aerospace Engineering,Psychology,Languages, Literature & Linguistics,Politics & International Studies (incl Development Studies),Chemical Engineering,Architecture,Geography,Economics & Econometrics,Biological Sciences,Sociology,General Engineering,Physics & Astronomy,Business & Management', 'Law,Computer Science,Electrical & Electronic Engineering,Chemical Engineering,Economics & Econometrics,Accounting & Finance,Archaeology,Mechanical & Aerospace Engineering,Business & Management,Medicine & Dentistry,Mathematics & Statistics,Art, Performing Arts & Design,Architecture,Sociology,Politics & International Studies (incl Development Studies),Biological Sciences,Agriculture & Forestry,Geology, Environmental, Earth & Marine Sciences,History, Philosophy & Theology,Languages, Literature & Linguistics,General Engineering,Physics & Astronomy,Chemistry,Other Health,Psychology']

Number of unique values: 2567

In [ ]:
print("Subjects Offered Validation")
print("=" * 50)

print("Missing values:", the_clean["subjects_offered"].isna().sum())

empty_subjects = (
    the_clean["subjects_offered"]
    .astype("string")
    .str.strip()
    .eq("")
    .sum()
)

print("Empty strings:", empty_subjects)

print("Unique subject lists:", the_clean["subjects_offered"].nunique())

print("\nSample cleaned values:")
print(the_clean["subjects_offered"].dropna().head(5).tolist())

Subjects Offered Validation
==================================================
Missing values: 4
Empty strings: 0
Unique subject lists: 2567

Sample cleaned values:
['Geography,Chemistry,Chemical Engineering,Biological Sciences,General Engineering,Computer Science,Art, Performing Arts & Design,Communication & Media Studies,Electrical & Electronic Engineering,Law,Economics & Econometrics,Geology, Environmental, Earth & Marine Sciences,Politics & International Studies (incl Development Studies),History, Philosophy & Theology,Medicine & Dentistry,Languages, Literature & Linguistics,Business & Management,Accounting & Finance,Mechanical & Aerospace Engineering,Mathematics & Statistics,Physics & Astronomy,Psychology,Other Health,Archaeology,Sociology,Civil Engineering,Education', 'Computer Science,Communication & Media Studies,Electrical & Electronic Engineering,Mathematics & Statistics,Education,Medicine & Dentistry,Civil Engineering,Politics & International Studies (incl Development Studies),History, Philosophy & Theology,Veterinary Science,Economics & Econometrics,Other Health,Geology, Environmental, Earth & Marine Sciences,Accounting & Finance,Mechanical & Aerospace Engineering,Chemistry,Sociology,Art, Performing Arts & Design,Chemical Engineering,Business & Management,General Engineering,Physics & Astronomy,Archaeology,Agriculture & Forestry,Law,Languages, Literature & Linguistics,Biological Sciences,Psychology', 'Architecture,Economics & Econometrics,Archaeology,Biological Sciences,Languages, Literature & Linguistics,Mechanical & Aerospace Engineering,Psychology,Politics & International Studies (incl Development Studies),History, Philosophy & Theology,Mathematics & Statistics,Civil Engineering,Geology, Environmental, Earth & Marine Sciences,General Engineering,Art, Performing Arts & Design,Other Health,Physics & Astronomy,Computer Science,Accounting & Finance,Chemical Engineering,Business & Management,Electrical & Electronic Engineering,Communication & Media Studies,Chemistry', 'Sociology,Architecture,Physics & Astronomy,Psychology,Mechanical & Aerospace Engineering,Law,Chemical Engineering,Electrical & Electronic Engineering,Medicine & Dentistry,Communication & Media Studies,Mathematics & Statistics,History, Philosophy & Theology,Languages, Literature & Linguistics,Agriculture & Forestry,Education,Computer Science,Business & Management,Geography,Accounting & Finance,Politics & International Studies (incl Development Studies),Chemistry,Archaeology,Art, Performing Arts & Design,Other Health,Biological Sciences,Geology, Environmental, Earth & Marine Sciences,Economics & Econometrics,General Engineering,Civil Engineering', 'Politics & International Studies (incl Development Studies),Biological Sciences,Business & Management,Civil Engineering,Geology, Environmental, Earth & Marine Sciences,Mathematics & Statistics,Psychology,General Engineering,Physics & Astronomy,Chemical Engineering,Chemistry,Economics & Econometrics,History, Philosophy & Theology,Computer Science,Accounting & Finance,Education,Veterinary Science,Electrical & Electronic Engineering,Geography,Other Health,Architecture,Art, Performing Arts & Design,Law,Mechanical & Aerospace Engineering,Sociology,Medicine & Dentistry,Archaeology,Languages, Literature & Linguistics']

In [ ]:
print("THE 2024 - Website URL")
print("=" * 50)

print("Data type:", the_clean["website_url"].dtype)
print("Missing values:", the_clean["website_url"].isna().sum())

print("\nSample values:")
print(the_clean["website_url"].dropna().head(10).tolist())

print("\nUnique non-missing URLs:", the_clean["website_url"].nunique())

THE 2024 - Website URL
==================================================
Data type: object
Missing values: 2329

Sample values:
['https://www.timeshighereducation.com/student/register-interest/siuk?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-92611101', 'https://www.timeshighereducation.com/student/register-interest/shorelight?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-68334672', 'https://www.timeshighereducation.com/student/register-interest/shorelight?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-48698023', 'https://www.timeshighereducation.com/student/register-interest/siuk?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-67516113', 'https://www.timeshighereducation.com/student/register-interest/shorelight?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-20795402', 'https://www.timeshighereducation.com/student/register-interest/shorelight?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-20537945', 'https://www.timeshighereducation.com/student/register-interest/siuk?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-67704114', 'https://www.timeshighereducation.com/student/register-interest/shorelight?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-50018853', 'https://www.timeshighereducation.com/student/register-interest/shorelight?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-73583889', 'https://www.timeshighereducation.com/student/register-interest/shorelight?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-44788493']

Unique non-missing URLs: 344

In [ ]:
the_clean["website_url"] = (
    the_clean["website_url"]
    .astype("string")
    .str.extract(r"\((https?://[^)]+)\)", expand=False)
)

print("Data type:", the_clean["website_url"].dtype)
print("Missing values:", the_clean["website_url"].isna().sum())

print("\nSample cleaned URLs:")
print(the_clean["website_url"].dropna().head(10).tolist())

print("\nUnique non-missing URLs:", the_clean["website_url"].nunique())

Data type: string
Missing values: 2673

Sample cleaned URLs:
[]

Unique non-missing URLs: 0

In [ ]:
the_clean["website_url"] = the_df["website_url"].copy()

print("Missing values:", the_clean["website_url"].isna().sum())

print("\nExact first URL representation:")
print(repr(the_clean["website_url"].dropna().iloc[0]))

print("\nFirst URL:")
print(the_clean["website_url"].dropna().iloc[0])

Missing values: 2329

Exact first URL representation:
'https://www.timeshighereducation.com/student/register-interest/siuk?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-92611101'

First URL:
https://www.timeshighereducation.com/student/register-interest/siuk?utm_medium=thewebsite&utm_campaign=cta-link&utm_source=rankings&iid=i-92611101

In [ ]:
print("THE 2024 - Final Cleaning Validation")
print("=" * 55)

print("Rows:", len(the_clean))
print("Columns:", len(the_clean.columns))

print("\nMissing values:")
print(the_clean.isna().sum()[the_clean.isna().sum() > 0])

print("\nData types:")
print(the_clean.dtypes)

print("\nDuplicate rows:", the_clean.duplicated().sum())
print("Duplicate university names:", the_clean["name"].duplicated().sum())

print("\nInternational Student Percentage:")
print("Minimum:", the_clean["stats_pc_intl_students"].min())
print("Maximum:", the_clean["stats_pc_intl_students"].max())

print("\nNumber of students:")
print("Minimum:", the_clean["stats_number_students"].min())
print("Maximum:", the_clean["stats_number_students"].max())

THE 2024 - Final Cleaning Validation
=======================================================
Rows: 2673
Columns: 29

Missing values:
scores_overall                   769
scores_teaching                  769
scores_research                  769
scores_citations                 769
scores_industry_income           769
scores_international_outlook     769
stats_pc_intl_students             3
stats_female_male_ratio           93
subjects_offered                   4
website_url                     2329
dtype: int64

Data types:
rank                                  object
name                                  object
scores_overall                        object
scores_overall_rank                    int64
scores_teaching                      float64
scores_teaching_rank                   int64
scores_research                      float64
scores_research_rank                   int64
scores_citations                     float64
scores_citations_rank                  int64
scores_industry_income               float64
scores_industry_income_rank            int64
scores_international_outlook         float64
scores_international_outlook_rank      int64
record_type                           object
member_level                           int64
url                                   object
nid                                    int64
location                              object
stats_number_students                  int64
stats_student_staff_ratio            float64
stats_pc_intl_students                 Int64
stats_female_male_ratio               object
aliases                               object
subjects_offered                      object
closed                                  bool
unaccredited                            bool
disabled                                bool
website_url                           object
dtype: object

Duplicate rows: 0
Duplicate university names: 0

International Student Percentage:
Minimum: 0
Maximum: 100

Number of students:
Minimum: 25
Maximum: 482541

In [ ]:
THE_CLEANED_FILE = os.path.join(
    CLEANED_PATH,
    "THE_2024_Cleaned.csv"
)

the_clean.to_csv(
    THE_CLEANED_FILE,
    index=False,
    encoding="utf-8"
)

print("THE 2024 cleaned dataset saved successfully!")
print("File:", THE_CLEANED_FILE)

THE 2024 cleaned dataset saved successfully!
File: /content/drive/MyDrive/EduVision_DV/02_Cleaned_Data/THE_2024_Cleaned.csv

In [ ]:
check_the = pd.read_csv(THE_CLEANED_FILE)

print("THE 2024 Saved File Verification")
print("=" * 50)

print("File exists:", os.path.exists(THE_CLEANED_FILE))
print("Rows:", len(check_the))
print("Columns:", len(check_the.columns))
print("Duplicate rows:", check_the.duplicated().sum())

print("\nInternational Student Percentage:")
print("Missing:", check_the["stats_pc_intl_students"].isna().sum())
print("Minimum:", check_the["stats_pc_intl_students"].min())
print("Maximum:", check_the["stats_pc_intl_students"].max())

THE 2024 Saved File Verification
==================================================
File exists: True
Rows: 2673
Columns: 29
Duplicate rows: 0

International Student Percentage:
Missing: 3
Minimum: 0.0
Maximum: 100.0

In [ ]:
wur2023_files = [
    f for f in os.listdir(RAW_PATH)
    if "2023" in f
]

print("World University Rankings 2023 file(s):")
for f in wur2023_files:
    print(f)

World University Rankings 2023 file(s):
World University Rankings 2023.csv

In [ ]:
WUR2023_FILE = os.path.join(
    RAW_PATH,
    "World University Rankings 2023.csv"
)

wur2023_df = pd.read_csv(WUR2023_FILE)

print("World University Rankings 2023 loaded successfully!")
print("Rows:", wur2023_df.shape[0])
print("Columns:", wur2023_df.shape[1])

World University Rankings 2023 loaded successfully!
Rows: 2341
Columns: 13

In [ ]:
print("World University Rankings 2023 columns:")
for i, col in enumerate(wur2023_df.columns, start=1):
    print(i, "→", col)

World University Rankings 2023 columns:
1 → University Rank
2 → Name of University
3 → Location
4 → No of student
5 → No of student per staff
6 → International Student
7 → Female:Male Ratio
8 → OverAll Score
9 → Teaching Score
10 → Research Score
11 → Citations Score
12 → Industry Income Score
13 → International Outlook Score

In [ ]:
print("Data types of World University Rankings 2023:")
print(wur2023_df.dtypes)

Data types of World University Rankings 2023:
University Rank                 object
Name of University              object
Location                        object
No of student                   object
No of student per staff        float64
International Student           object
Female:Male Ratio               object
OverAll Score                   object
Teaching Score                 float64
Research Score                 float64
Citations Score                float64
Industry Income Score          float64
International Outlook Score    float64
dtype: object

In [ ]:
print("Missing values in World University Rankings 2023:")
print(wur2023_df.isnull().sum())

Missing values in World University Rankings 2023:
University Rank                  0
Name of University             108
Location                       294
No of student                  132
No of student per staff        133
International Student          132
Female:Male Ratio              213
OverAll Score                  542
Teaching Score                 542
Research Score                 542
Citations Score                542
Industry Income Score          542
International Outlook Score    542
dtype: int64

In [ ]:
duplicate_rows = wur2023_df.duplicated().sum()

print("Duplicate complete rows:", duplicate_rows)

Duplicate complete rows: 29

In [ ]:
duplicate_data = wur2023_df[wur2023_df.duplicated(keep=False)]

print("Total rows involved in duplicates:", len(duplicate_data))
print("\nDuplicate rows:")
display(duplicate_data)

Total rows involved in duplicates: 30

Duplicate rows:

,University Rank,Name of University,Location,No of student,No of student per staff,International Student,Female:Male Ratio,OverAll Score,Teaching Score,Research Score,Citations Score,Industry Income Score,International Outlook Score
2287,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2288,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2289,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2290,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2291,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2292,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2293,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2294,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2295,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2296,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2297,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2298,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2299,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2300,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2301,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2302,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2303,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2304,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2305,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2306,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2307,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2308,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2309,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2310,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2311,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2312,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2313,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2314,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2315,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
empty_university_rows = wur2023_df["Name of University"].isna().sum()

print("Rows with missing university name:", empty_university_rows)

Rows with missing university name: 108

In [ ]:
missing_name_rows = wur2023_df[
    wur2023_df["Name of University"].isna()
]

print("Rows with missing university names:", len(missing_name_rows))

display(missing_name_rows)

Rows with missing university names: 108

,University Rank,Name of University,Location,No of student,No of student per staff,International Student,Female:Male Ratio,OverAll Score,Teaching Score,Research Score,Citations Score,Industry Income Score,International Outlook Score
2209,-,NaN,NaN,NaN,NaN,NaN,NaN,56.9,81.0,72.9,9.3,99.1,72.4
2210,-,NaN,NaN,NaN,NaN,NaN,NaN,51.2–54.3,55.7,46.8,51.4,99.1,62.2
2211,-,NaN,NaN,NaN,NaN,NaN,NaN,47.0–48.7,31.1,23.7,83.0,75.5,57.4
2212,-,NaN,NaN,NaN,NaN,NaN,NaN,42.1–44.9,32.5,45.3,54.6,61.6,43.9
2213,-,NaN,NaN,NaN,NaN,NaN,NaN,42.1–44.9,45.3,41.7,29.1,100.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2312,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2313,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2314,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2315,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data_columns = [
    "Name of University",
    "Location",
    "No of student",
    "No of student per staff",
    "International Student",
    "Female:Male Ratio",
    "OverAll Score",
    "Teaching Score",
    "Research Score",
    "Citations Score",
    "Industry Income Score",
    "International Outlook Score"
]

completely_empty = wur2023_df[data_columns].isna().all(axis=1)

print("Completely empty records:", completely_empty.sum())
print("Records with some actual data:", (~completely_empty).sum())

Completely empty records: 30
Records with some actual data: 2311

In [ ]:
wur2023_clean = wur2023_df.copy()
wur2023_clean = wur2023_clean[~completely_empty].copy()

print("Original rows:", len(wur2023_df))
print("Cleaned rows:", len(wur2023_clean))
print("Rows removed:", len(wur2023_df) - len(wur2023_clean))

Original rows: 2341
Cleaned rows: 2311
Rows removed: 30

In [ ]:
print("University Rank data type:", wur2023_clean["University Rank"].dtype)

print("\nFirst 30 rank values:")
print(wur2023_clean["University Rank"].head(30).tolist())

print("\nSample unique rank values:")
print(wur2023_clean["University Rank"].dropna().unique()[:50])

University Rank data type: object

First 30 rank values:
['1', '2', '3', '3', '5', '6', '7', '8', '9', '10', '11', '11', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '26', '28', '29', '30']

Sample unique rank values:
['1' '2' '3' '5' '6' '7' '8' '9' '10' '11' '13' '14' '15' '16' '17' '18'
 '19' '20' '21' '22' '23' '24' '25' '26' '28' '29' '30' '31' '32' '33'
 '34' '35' '36' '37' '38' '39' '40' '41' '42' '43' '44' '45' '46' '47'
 '48' '49' '50' '51' '52' '53']

In [ ]:
wur2023_clean["University Rank"] = pd.to_numeric(
    wur2023_clean["University Rank"],
    errors="coerce"
)

print("Data type:", wur2023_clean["University Rank"].dtype)
print("Missing values:", wur2023_clean["University Rank"].isna().sum())

Data type: float64
Missing values: 2112

In [ ]:
wur2023_clean["University Rank"] = wur2023_df.loc[
    wur2023_clean.index, "University Rank"
].copy()

print("Data type:", wur2023_clean["University Rank"].dtype)
print("Missing values:", wur2023_clean["University Rank"].isna().sum())

Data type: object
Missing values: 0

In [ ]:
rank_numeric = pd.to_numeric(
    wur2023_clean["University Rank"],
    errors="coerce"
)

non_numeric_ranks = wur2023_clean.loc[
    rank_numeric.isna(),
    "University Rank"
].unique()

print("Number of non-numeric rank values:", len(non_numeric_ranks))
print("\nNon-numeric rank values:")
print(non_numeric_ranks)

Number of non-numeric rank values: 13

Non-numeric rank values:
['201–250' '251–300' '301–350' '351–400' '401–500' '501–600' '601–800'
 '801–1000' '1001–1200' '1201–1500' '1501+' 'Reporter' '-']

In [ ]:
special_ranks = [
    "201–250", "251–300", "301–350", "351–400",
    "401–500", "501–600", "601–800", "801–1000",
    "1001–1200", "1201–1500", "1501+",
    "Reporter", "-"
]

for rank in special_ranks:
    count = (wur2023_clean["University Rank"] == rank).sum()
    print(rank, "→", count)

201–250 → 49
251–300 → 51
301–350 → 48
351–400 → 50
401–500 → 101
501–600 → 96
601–800 → 172
801–1000 → 193
1001–1200 → 200
1201–1500 → 285
1501+ → 253
Reporter → 512
- → 102

In [ ]:
duplicate_names = wur2023_clean["Name of University"].duplicated().sum()

print("Duplicate university names:", duplicate_names)

Duplicate university names: 77

In [ ]:
duplicate_name_rows = wur2023_clean[
    wur2023_clean["Name of University"].duplicated(keep=False)
].sort_values("Name of University")

print("Rows involved in duplicate names:", len(duplicate_name_rows))

display(duplicate_name_rows[
    ["University Rank", "Name of University", "Location", "OverAll Score"]
])

Rows involved in duplicate names: 78

     University Rank Name of University Location OverAll Score
2209               -                NaN      NaN          56.9
2210               -                NaN      NaN     51.2–54.3
2211               -                NaN      NaN     47.0–48.7
2212               -                NaN      NaN     42.1–44.9
2213               -                NaN      NaN     42.1–44.9
...              ...                ...      ...           ...
2282               -                NaN      NaN     10.4–18.3
2283               -                NaN      NaN     10.4–18.3
2284               -                NaN      NaN     10.4–18.3
2285               -                NaN      NaN     10.4–18.3
2286               -                NaN      NaN     10.4–18.3

[78 rows x 4 columns]

In [ ]:
real_names = wur2023_clean[
    wur2023_clean["Name of University"].notna()
]

duplicate_real_names = real_names["Name of University"].duplicated().sum()

print("Duplicate actual university names:", duplicate_real_names)

Duplicate actual university names: 0

In [ ]:
print("Data type:", wur2023_clean["No of student"].dtype)

print("\nFirst 20 values:")
print(wur2023_clean["No of student"].head(20).tolist())

print("\nMissing values:", wur2023_clean["No of student"].isna().sum())

Data type: object

First 20 values:
['20,965', '21,887', '20,185', '16,164', '11,415', '2,237', '8,279', '40,921', '13,482', '18,545', '21,781', '21,665', '15,366', '21,453', '17,584', '38,324', '31,994', '77,468', '32,337', '24,027']

Missing values: 102

In [ ]:
wur2023_clean["No of student"] = (
    wur2023_clean["No of student"]
    .str.replace(",", "", regex=False)
)

wur2023_clean["No of student"] = pd.to_numeric(
    wur2023_clean["No of student"],
    errors="coerce"
)

print("Data type:", wur2023_clean["No of student"].dtype)
print("Missing values:", wur2023_clean["No of student"].isna().sum())
print("Minimum:", wur2023_clean["No of student"].min())
print("Maximum:", wur2023_clean["No of student"].max())

Data type: float64
Missing values: 102
Minimum: 115.0
Maximum: 460632.0

In [ ]:
print("Data type:", wur2023_clean["International Student"].dtype)

print("\nFirst 20 values:")
print(wur2023_clean["International Student"].head(20).tolist())

print("\nMissing values:", wur2023_clean["International Student"].isna().sum())

Data type: object

First 20 values:
['42%', '25%', '39%', '24%', '33%', '34%', '23%', '24%', '21%', '61%', '38%', '41%', '36%', '23%', '29%', '10%', '19%', '26%', '25%', '26%']

Missing values: 102

In [ ]:
wur2023_clean["International Student"] = (
    wur2023_clean["International Student"]
    .str.replace("%", "", regex=False)
)

wur2023_clean["International Student"] = pd.to_numeric(
    wur2023_clean["International Student"],
    errors="coerce"
)

print("Data type:", wur2023_clean["International Student"].dtype)
print("Missing values:", wur2023_clean["International Student"].isna().sum())
print("Minimum:", wur2023_clean["International Student"].min())
print("Maximum:", wur2023_clean["International Student"].max())

Data type: float64
Missing values: 105
Minimum: 0.0
Maximum: 100.0

In [ ]:
original_values = wur2023_df.loc[
    wur2023_clean.index, "International Student"
]

new_values = wur2023_clean["International Student"]

became_missing = original_values[
    original_values.notna() & new_values.isna()
]

print("Values that became missing:")
print(became_missing.unique())
print("\nNumber of values:", len(became_missing))

Values that became missing:
['%']

Number of values: 3

In [ ]:
print("Data type:", wur2023_clean["Female:Male Ratio"].dtype)

print("\nFirst 20 values:")
print(wur2023_clean["Female:Male Ratio"].head(20).tolist())

print("\nMissing values:", wur2023_clean["Female:Male Ratio"].isna().sum())

Data type: object

First 20 values:
['48 : 52', '50 : 50', '47 : 53', '46 : 54', '40 : 60', '37 : 63', '46 : 54', '52 : 48', '52 : 48', '40 : 60', nan, '33 : 67', '47 : 53', '53 : 47', '53 : 47', nan, nan, '56 : 44', '51 : 49', '51 : 49']

Missing values: 183

In [ ]:
wur2023_clean["Female:Male Ratio"] = (
    wur2023_clean["Female:Male Ratio"]
    .astype("string")
    .str.replace(r"\s*:\s*", " : ", regex=True)
    .str.strip()
)

print("Data type:", wur2023_clean["Female:Male Ratio"].dtype)
print("Missing values:", wur2023_clean["Female:Male Ratio"].isna().sum())

print("\nSample values:")
print(wur2023_clean["Female:Male Ratio"].dropna().head(10).tolist())

Data type: string
Missing values: 183

Sample values:
['48 : 52', '50 : 50', '47 : 53', '46 : 54', '40 : 60', '37 : 63', '46 : 54', '52 : 48', '52 : 48', '40 : 60']

In [ ]:
score_columns = [
    "OverAll Score",
    "Teaching Score",
    "Research Score",
    "Citations Score",
    "Industry Income Score",
    "International Outlook Score"
]

for col in score_columns:
    print(
        col,
        "→ Min:", wur2023_clean[col].min(),
        "| Max:", wur2023_clean[col].max(),
        "| Missing:", wur2023_clean[col].isna().sum()
    )

TypeError: '<=' not supported between instances of 'str' and 'float'

In [ ]:
score_columns = [
    "OverAll Score",
    "Teaching Score",
    "Research Score",
    "Citations Score",
    "Industry Income Score",
    "International Outlook Score"
]

for col in score_columns:
    print("\n", col)
    print("Data type:", wur2023_clean[col].dtype)
    print("Sample values:", wur2023_clean[col].dropna().head(10).tolist())

 OverAll Score
Data type: object
Sample values: ['96.4', '95.2', '94.8', '94.8', '94.2', '94.1', '92.4', '92.1', '91.4', '90.4']

 Teaching Score
Data type: float64
Sample values: [92.3, 94.8, 90.9, 94.2, 90.7, 90.9, 87.6, 86.4, 92.6, 82.8]

 Research Score
Data type: float64
Sample values: [99.7, 99.0, 99.5, 96.7, 93.6, 97.0, 95.9, 95.8, 92.7, 90.8]

 Citations Score
Data type: float64
Sample values: [99.0, 99.3, 97.0, 99.8, 99.8, 97.3, 99.1, 99.0, 97.0, 98.3]

 Industry Income Score
Data type: float64
Sample values: [74.9, 49.5, 54.2, 65.0, 90.9, 89.8, 66.0, 76.8, 55.0, 59.8]

 International Outlook Score
Data type: float64
Sample values: [96.2, 80.5, 95.8, 79.8, 89.3, 83.6, 80.3, 78.4, 70.9, 97.5]

In [ ]:
overall_numeric = pd.to_numeric(
    wur2023_clean["OverAll Score"],
    errors="coerce"
)

non_numeric_overall = wur2023_clean.loc[
    overall_numeric.isna() & wur2023_clean["OverAll Score"].notna(),
    "OverAll Score"
].unique()

print("Non-numeric Overall Score values:")
print(non_numeric_overall)

print("\nNumber of non-numeric values:", len(non_numeric_overall))

Non-numeric Overall Score values:
['51.2–54.3' '48.9–51.1' '47.0–48.7' '45.0–46.9' '42.1–44.9' '39.3–42.0'
 '34.0–39.2' '29.8–33.9' '24.4–29.7' '18.4–24.3' '10.4–18.3']

Number of non-numeric values: 11

In [ ]:
print("Data type:", wur2023_clean["OverAll Score"].dtype)
print("Missing values:", wur2023_clean["OverAll Score"].isna().sum())

print("\nSample exact scores:")
print(wur2023_clean["OverAll Score"].dropna().head(10).tolist())

print("\nSample score ranges:")
print(non_numeric_overall)

Data type: object
Missing values: 512

Sample exact scores:
['96.4', '95.2', '94.8', '94.8', '94.2', '94.1', '92.4', '92.1', '91.4', '90.4']

Sample score ranges:
['51.2–54.3' '48.9–51.1' '47.0–48.7' '45.0–46.9' '42.1–44.9' '39.3–42.0'
 '34.0–39.2' '29.8–33.9' '24.4–29.7' '18.4–24.3' '10.4–18.3']

In [ ]:
numeric_score_columns = [
    "Teaching Score",
    "Research Score",
    "Citations Score",
    "Industry Income Score",
    "International Outlook Score"
]

for col in numeric_score_columns:
    print(
        col,
        "→ Min:", wur2023_clean[col].min(),
        "| Max:", wur2023_clean[col].max(),
        "| Missing:", wur2023_clean[col].isna().sum()
    )

Teaching Score → Min: 11.6 | Max: 94.8 | Missing: 512
Research Score → Min: 7.4 | Max: 99.7 | Missing: 512
Citations Score → Min: 0.8 | Max: 100.0 | Missing: 512
Industry Income Score → Min: 36.9 | Max: 100.0 | Missing: 512
International Outlook Score → Min: 14.1 | Max: 99.7 | Missing: 512

In [ ]:
print("===== FINAL VALIDATION: WUR 2023 =====")

print("\nRows:", wur2023_clean.shape[0])
print("Columns:", wur2023_clean.shape[1])

print("\nMissing values:")
print(wur2023_clean.isna().sum())

print("\nDuplicate complete rows:",
      wur2023_clean.duplicated().sum())

print("\nDuplicate actual university names:",
      wur2023_clean[
          wur2023_clean["Name of University"].notna()
      ]["Name of University"].duplicated().sum())

print("\nData types:")
print(wur2023_clean.dtypes)

===== FINAL VALIDATION: WUR 2023 =====

Rows: 2311
Columns: 13

Missing values:
University Rank                  0
Name of University              78
Location                       264
No of student                  102
No of student per staff        103
International Student          105
Female:Male Ratio              183
OverAll Score                  512
Teaching Score                 512
Research Score                 512
Citations Score                512
Industry Income Score          512
International Outlook Score    512
dtype: int64

Duplicate complete rows: 0

Duplicate actual university names: 0

Data types:
University Rank                        object
Name of University                     object
Location                               object
No of student                         float64
No of student per staff               float64
International Student                 float64
Female:Male Ratio              string[python]
OverAll Score                          object
Teaching Score                        float64
Research Score                        float64
Citations Score                       float64
Industry Income Score                 float64
International Outlook Score           float64
dtype: object

In [ ]:
# Step 101A: Set cleaned data path

PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"
CLEANED_PATH = os.path.join(PROJECT_PATH, "02_Cleaned_Data")

print("Cleaned data path:", CLEANED_PATH)

Cleaned data path: /content/drive/MyDrive/EduVision_DV/02_Cleaned_Data

In [ ]:
WUR2023_CLEANED_FILE = os.path.join(
    CLEANED_PATH,
    "WUR_2023_Cleaned.csv"
)

wur2023_clean.to_csv(
    WUR2023_CLEANED_FILE,
    index=False,
    encoding="utf-8"
)

print("Cleaned WUR 2023 dataset saved successfully!")
print("File:", WUR2023_CLEANED_FILE)

Cleaned WUR 2023 dataset saved successfully!
File: /content/drive/MyDrive/EduVision_DV/02_Cleaned_Data/WUR_2023_Cleaned.csv

In [ ]:
saved_wur2023 = pd.read_csv(WUR2023_CLEANED_FILE)

print("File exists:", os.path.exists(WUR2023_CLEANED_FILE))
print("Rows:", saved_wur2023.shape[0])
print("Columns:", saved_wur2023.shape[1])
print("Duplicate rows:", saved_wur2023.duplicated().sum())

File exists: True
Rows: 2311
Columns: 13
Duplicate rows: 0

In [ ]:
WORLD_BANK_ZIP = os.path.join(
    RAW_PATH,
    "edstats-csv-zip-32-mb-.zip"
)

print("File exists:", os.path.exists(WORLD_BANK_ZIP))

if os.path.exists(WORLD_BANK_ZIP):
    print("File size (MB):", round(os.path.getsize(WORLD_BANK_ZIP) / (1024 * 1024), 2))

File exists: True
File size (MB): 37.14

In [ ]:
import zipfile

with zipfile.ZipFile(WORLD_BANK_ZIP, "r") as zip_ref:
    files_inside = zip_ref.namelist()

print("Number of files inside ZIP:", len(files_inside))

print("\nFiles inside the ZIP:")
for file in files_inside:
    print(file)

Number of files inside ZIP: 5

Files inside the ZIP:
EdStatsData.csv
EdStatsCountry.csv
EdStatsSeries.csv
EdStatsCountry-Series.csv
EdStatsFootNote.csv

In [ ]:
with zipfile.ZipFile(WORLD_BANK_ZIP, "r") as zip_ref:
    with zip_ref.open("EdStatsData.csv") as file:
        wb_data_sample = pd.read_csv(file, nrows=5)

print("Columns in EdStatsData.csv:")
for i, col in enumerate(wb_data_sample.columns, start=1):
    print(i, "→", col)

print("\nSample data:")
display(wb_data_sample)

Columns in EdStatsData.csv:
1 → Country Name
2 → Country Code
3 → Indicator Name
4 → Indicator Code
5 → 1970
6 → 1971
7 → 1972
8 → 1973
9 → 1974
10 → 1975
11 → 1976
12 → 1977
13 → 1978
14 → 1979
15 → 1980
16 → 1981
17 → 1982
18 → 1983
19 → 1984
20 → 1985
21 → 1986
22 → 1987
23 → 1988
24 → 1989
25 → 1990
26 → 1991
27 → 1992
28 → 1993
29 → 1994
30 → 1995
31 → 1996
32 → 1997
33 → 1998
34 → 1999
35 → 2000
36 → 2001
37 → 2002
38 → 2003
39 → 2004
40 → 2005
41 → 2006
42 → 2007
43 → 2008
44 → 2009
45 → 2010
46 → 2011
47 → 2012
48 → 2013
49 → 2014
50 → 2015
51 → 2016
52 → 2017
53 → 2020
54 → 2025
55 → 2030
56 → 2035
57 → 2040
58 → 2045
59 → 2050
60 → 2055
61 → 2060
62 → 2065
63 → 2070
64 → 2075
65 → 2080
66 → 2085
67 → 2090
68 → 2095
69 → 2100
70 → Unnamed: 69

Sample data:

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,...,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
0,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,54.822121,54.894138,56.209438,57.267109,57.991138,59.36554,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
with zipfile.ZipFile(WORLD_BANK_ZIP, "r") as zip_ref:
    with zip_ref.open("EdStatsData.csv") as file:
        wb_indicators = pd.read_csv(
            file,
            usecols=["Indicator Name", "Indicator Code"]
        )

higher_ed = wb_indicators[
    wb_indicators["Indicator Name"].str.contains(
        "tertiary|higher|university|college",
        case=False,
        na=False
    )
].drop_duplicates()

print("Higher-education-related indicators found:", len(higher_ed))

display(higher_ed)

Higher-education-related indicators found: 354

,Indicator Name,Indicator Code
126,All staff compensation as % of total expenditu...,UIS.XSPENDP.4.FDPUB.FNS
131,All staff compensation as % of total expenditu...,UIS.XSPENDP.56.FDPUB.FNS
209,Barro-Lee: Average years of tertiary schooling...,BAR.TER.SCHL.15UP.FE
210,Barro-Lee: Average years of tertiary schooling...,BAR.TER.SCHL.15UP
211,Barro-Lee: Average years of tertiary schooling...,BAR.TER.SCHL.1519.FE
...,...,...
3234,UIS: Percentage of population age 25+ with at ...,UIS.EA.1T6.AG25T99
3235,UIS: Percentage of population age 25+ with at ...,UIS.EA.3T6.AG25T99.F
3236,UIS: Percentage of population age 25+ with at ...,UIS.EA.3T6.AG25T99.GPI
3237,UIS: Percentage of population age 25+ with at ...,UIS.EA.3T6.AG25T99.M
3238,UIS: Percentage of population age 25+ with at ...,UIS.EA.3T6.AG25T99

In [ ]:
tertiary_enrollment = higher_ed[
    higher_ed["Indicator Name"].str.contains(
        "tertiary.*enrol|enrol.*tertiary",
        case=False,
        regex=True,
        na=False
    )
]

print("Tertiary enrollment indicators found:", len(tertiary_enrollment))

display(tertiary_enrollment)

Tertiary enrollment indicators found: 87

                                         Indicator Name     Indicator Code
1171  Enrolment in post-secondary non-tertiary educa...            UIS.E.4
1172  Enrolment in post-secondary non-tertiary educa...          UIS.E.4.F
1173  Enrolment in post-secondary non-tertiary educa...         UIS.E.4.PR
1174  Enrolment in post-secondary non-tertiary educa...       UIS.E.4.PR.F
1175  Enrolment in post-secondary non-tertiary educa...         UIS.E.4.PU
...                                                 ...                ...
2045  Percentage of students in tertiary education e...  UIS.FOSEP.56.F200
2046  Percentage of students in tertiary education e...   UIS.FOSEP.56.FUK
2047  Percentage of students in tertiary education e...  UIS.FOSEP.56.F400
2048  Percentage of students in tertiary education e...  UIS.FOSEP.56.F800
2049  Percentage of students in tertiary education e...  UIS.FOSEP.56.F300

[87 rows x 2 columns]

In [ ]:
tertiary_actual = higher_ed[
    higher_ed["Indicator Name"].str.contains(
        "Enrolment in tertiary education",
        case=False,
        na=False
    )
]

print("Actual tertiary enrollment indicators:", len(tertiary_actual))

display(tertiary_actual)

Actual tertiary enrollment indicators: 14

                                         Indicator Name      Indicator Code
1201  Enrolment in tertiary education per 100,000 in...    UIS.TE_100000.56
1202  Enrolment in tertiary education per 100,000 in...  UIS.TE_100000.56.F
1203  Enrolment in tertiary education per 100,000 in...  UIS.TE_100000.56.M
1204  Enrolment in tertiary education, all programme...         SE.TER.ENRL
1205  Enrolment in tertiary education, all programme...      SE.TER.ENRL.FE
1206  Enrolment in tertiary education, ISCED 5 progr...           UIS.E.5.B
1207  Enrolment in tertiary education, ISCED 5 progr...         UIS.E.5.B.F
1208  Enrolment in tertiary education, ISCED 6 progr...             UIS.E.6
1209  Enrolment in tertiary education, ISCED 6 progr...           UIS.E.6.F
1210  Enrolment in tertiary education, ISCED 7 progr...             UIS.E.7
1211  Enrolment in tertiary education, ISCED 7 progr...           UIS.E.7.F
1212  Enrolment in tertiary education, ISCED 8 progr...             UIS.E.8
1213  Enrolment in tertiary education, ISCED 8 progr...           UIS.E.8.F
1857  Percentage of enrolment in tertiary education ...      SE.TER.PRIV.ZS

In [ ]:
broad_tertiary = tertiary_actual[
    ~tertiary_actual["Indicator Code"].str.contains(
        r"\.FE$|\.M$",
        regex=True,
        na=False
    )
]

print("Broad tertiary indicators:", len(broad_tertiary))

display(broad_tertiary)

Broad tertiary indicators: 12

                                         Indicator Name      Indicator Code
1201  Enrolment in tertiary education per 100,000 in...    UIS.TE_100000.56
1202  Enrolment in tertiary education per 100,000 in...  UIS.TE_100000.56.F
1204  Enrolment in tertiary education, all programme...         SE.TER.ENRL
1206  Enrolment in tertiary education, ISCED 5 progr...           UIS.E.5.B
1207  Enrolment in tertiary education, ISCED 5 progr...         UIS.E.5.B.F
1208  Enrolment in tertiary education, ISCED 6 progr...             UIS.E.6
1209  Enrolment in tertiary education, ISCED 6 progr...           UIS.E.6.F
1210  Enrolment in tertiary education, ISCED 7 progr...             UIS.E.7
1211  Enrolment in tertiary education, ISCED 7 progr...           UIS.E.7.F
1212  Enrolment in tertiary education, ISCED 8 progr...             UIS.E.8
1213  Enrolment in tertiary education, ISCED 8 progr...           UIS.E.8.F
1857  Percentage of enrolment in tertiary education ...      SE.TER.PRIV.ZS

In [ ]:
pd.set_option("display.max_colwidth", None)

print("Tertiary education indicators:\n")
display(tertiary_actual)

Tertiary education indicators:

,Indicator Name,Indicator Code
1201,"Enrolment in tertiary education per 100,000 inhabitants, both sexes",UIS.TE_100000.56
1202,"Enrolment in tertiary education per 100,000 inhabitants, female",UIS.TE_100000.56.F
1203,"Enrolment in tertiary education per 100,000 inhabitants, male",UIS.TE_100000.56.M
1204,"Enrolment in tertiary education, all programmes, both sexes (number)",SE.TER.ENRL
1205,"Enrolment in tertiary education, all programmes, female (number)",SE.TER.ENRL.FE
1206,"Enrolment in tertiary education, ISCED 5 programmes, both sexes (number)",UIS.E.5.B
1207,"Enrolment in tertiary education, ISCED 5 programmes, female (number)",UIS.E.5.B.F
1208,"Enrolment in tertiary education, ISCED 6 programmes, both sexes (number)",UIS.E.6
1209,"Enrolment in tertiary education, ISCED 6 programmes, female (number)",UIS.E.6.F
1210,"Enrolment in tertiary education, ISCED 7 programmes, both sexes (number)",UIS.E.7
1211,"Enrolment in tertiary education, ISCED 7 programmes, female (number)",UIS.E.7.F
1212,"Enrolment in tertiary education, ISCED 8 programmes, both sexes (number)",UIS.E.8
1213,"Enrolment in tertiary education, ISCED 8 programmes, female (number)",UIS.E.8.F
1857,Percentage of enrolment in tertiary education in private institutions (%),SE.TER.PRIV.ZS

In [ ]:
selected_codes = tertiary_actual["Indicator Code"].tolist()

print("Selected tertiary indicators:", len(selected_codes))
print("\nIndicator codes:")
for code in selected_codes:
    print(code)

Selected tertiary indicators: 14

Indicator codes:
UIS.TE_100000.56
UIS.TE_100000.56.F
UIS.TE_100000.56.M
SE.TER.ENRL
SE.TER.ENRL.FE
UIS.E.5.B
UIS.E.5.B.F
UIS.E.6
UIS.E.6.F
UIS.E.7
UIS.E.7.F
UIS.E.8
UIS.E.8.F
SE.TER.PRIV.ZS

In [ ]:
import zipfile
import pandas as pd

zip_path = os.path.join(RAW_PATH, "edstats-csv-zip-32-mb-.zip")

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("EdStatsData.csv") as f:
        wb_selected = pd.read_csv(
            f,
            usecols=lambda col: col in [
                "Country Name",
                "Country Code",
                "Indicator Name",
                "Indicator Code"
            ] or col.isdigit()
        )

wb_selected = wb_selected[
    wb_selected["Indicator Code"].isin(selected_codes)
].copy()

print("Extracted rows:", len(wb_selected))
print("Columns:", len(wb_selected.columns))
print("\nCountries:", wb_selected["Country Name"].nunique())
print("Indicators:", wb_selected["Indicator Code"].nunique())

Extracted rows: 3388
Columns: 69

Countries: 242
Indicators: 14

In [ ]:
year_columns = [
    col for col in wb_selected.columns
    if str(col).isdigit()
]

print("Number of year columns:", len(year_columns))
print("\nAvailable years:")
print(year_columns)

Number of year columns: 65

Available years:
['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2020', '2025', '2030', '2035', '2040', '2045', '2050', '2055', '2060', '2065', '2070', '2075', '2080', '2085', '2090', '2095', '2100']

In [ ]:
year_data_count = wb_selected[year_columns].notna().sum()

print("Non-missing values available for each year:\n")
print(year_data_count)

Non-missing values available for each year:

1970    193
1971    553
1972    532
1973    520
1974    506
       ...
2080      0
2085      0
2090      0
2095      0
2100      0
Length: 65, dtype: int64

In [ ]:
historical_years = [str(year) for year in range(1970, 2018)]

historical_counts = wb_selected[historical_years].notna().sum()

print("Data availability from 1970 to 2017:\n")
print(historical_counts.to_string())

Data availability from 1970 to 2017:

1970     193
1971     553
1972     532
1973     520
1974     506
1975     514
1976     506
1977     526
1978     519
1979     564
1980     553
1981     577
1982     548
1983     541
1984     555
1985     547
1986     577
1987     532
1988     508
1989     525
1990     533
1991     533
1992     536
1993     527
1994     508
1995     522
1996     513
1997     460
1998     556
1999    1124
2000    1102
2001    1102
2002    1182
2003    1216
2004    1225
2005    1195
2006    1178
2007    1193
2008    1271
2009    1291
2010    1330
2011    1359
2012    1470
2013    1774
2014    1562
2015     366
2016      21
2017       0

In [ ]:
indicator_coverage = (
    wb_selected
    .groupby(["Indicator Code", "Indicator Name"])[historical_years]
    .apply(lambda x: x.notna().sum())
)

print(indicator_coverage.to_string())

                                                                                              1970  1971  1972  1973  1974  1975  1976  1977  1978  1979  1980  1981  1982  1983  1984  1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017
Indicator Code     Indicator Name
SE.TER.ENRL        Enrolment in tertiary education, all programmes, both sexes (number)         62   146   136   137   133   136   135   136   137   145   144   162   148   144   148   144   157   142   141   148   148   148   142   136   128   135   130   107   111   158   149   148   158   159   159   154   154   154   159   162   165   167   166   156   149   116     7     0
SE.TER.ENRL.FE     Enrolment in tertiary education, all programmes, female (number)             51   120   117   113   111   111   110   114   111   123   120   117   116   116   116   115   117   112   105   106   106   108   113   113   111   110   110    96   102   140   137   136   151   149   151   147   148   147   154   158   163   163   163   152   146   113     7     0
SE.TER.PRIV.ZS     Percentage of enrolment in tertiary education in private institutions (%)     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0    18    52    59    61    70    72    79    75    76    86    96   102   104   111   107   114   111   103     7     0
UIS.E.5.B          Enrolment in tertiary education, ISCED 5 programmes, both sexes (number)      0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     8    23   118   117   112   116   123   119   116   113   116   124   123   130   131   133   117   105     4     0     0
UIS.E.5.B.F        Enrolment in tertiary education, ISCED 5 programmes, female (number)          0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     7    22   108   112   108   113   121   119   114   111   115   124   122   128   130   132   115   105     3     0     0
UIS.E.6            Enrolment in tertiary education, ISCED 6 programmes, both sexes (number)      0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     1     1     1     1     1     1     1     1     2     1     3     4    33   127   115     3     0     0
UIS.E.6.F          Enrolment in tertiary education, ISCED 6 programmes, female (number)          0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     1     1     1     1     1     1     1     1     2     1     3     4    33   126   114     2     0     0
UIS.E.7            Enrolment in tertiary education, ISCED 7 programmes, both sexes (number)      0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     2     3    33   126   112     2     0     0
UIS.E.7.F          Enrolment in tertiary education, ISCED 7 programmes, female (number)          0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     1     0     2     3    33   124   111     2     0     0
UIS.E.8            Enrolment in tertiary education, ISCED 8 programmes, both sexes (number)      0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     9    23    98    96   100    99   106   111   110   106   109   116   114   115   120   124   127   111     3     0     0
UIS.E.8.F          Enrolment in tertiary education, ISCED 8 programmes, female (number)          0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     9    22    91    93    96    97   105   110   109   104   108   114   113   113   119   123   125   108     3     0     0
UIS.TE_100000.56   Enrolment in tertiary education per 100,000 inhabitants, both sexes          32   111   104   106   102   105   103   106   107   114   113   129   116   113   119   116   127   112   112   119   121   119   113   108   101   109   103    82    85   131   121   121   130   133   131   128   126   124   130   135   136   138   132   123    93     4     0     0
UIS.TE_100000.56.F Enrolment in tertiary education per 100,000 inhabitants, female              24    88    87    82    80    81    79    85    82    91    88    84    84    84    86    86    88    83    75    76    79    79    84    85    84    84    85    71    75   113   108   109   123   123   122   120   119   116   124   130   133   133   129   121    91     4     0     0
UIS.TE_100000.56.M Enrolment in tertiary education per 100,000 inhabitants, male                24    88    88    82    80    81    79    85    82    91    88    85    84    84    86    86    88    83    75    76    79    79    84    85    84    84    85    71    75   113   108   109   123   123   122   120   119   116   124   130   133   133   129   121    91     4     0     0

In [ ]:
print("Data types:\n")
print(wb_selected.dtypes.to_string())

Data types:

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1970              float64
1971              float64
1972              float64
1973              float64
1974              float64
1975              float64
1976              float64
1977              float64
1978              float64
1979              float64
1980              float64
1981              float64
1982              float64
1983              float64
1984              float64
1985              float64
1986              float64
1987              float64
1988              float64
1989              float64
1990              float64
1991              float64
1992              float64
1993              float64
1994              float64
1995              float64
1996              float64
1997              float64
1998              float64
1999              float64
2000              float64
2001              float64
2002              float64
2003              float64
2004              float64
2005              float64
2006              float64
2007              float64
2008              float64
2009              float64
2010              float64
2011              float64
2012              float64
2013              float64
2014              float64
2015              float64
2016              float64
2017              float64
2020              float64
2025              float64
2030              float64
2035              float64
2040              float64
2045              float64
2050              float64
2055              float64
2060              float64
2065              float64
2070              float64
2075              float64
2080              float64
2085              float64
2090              float64
2095              float64
2100              float64

In [ ]:
duplicate_records = wb_selected.duplicated(
    subset=["Country Code", "Indicator Code"]
).sum()

print("Duplicate country-indicator records:", duplicate_records)

Duplicate country-indicator records: 0

In [ ]:
missing_values = wb_selected.isna().sum()

print("Columns with missing values:\n")
print(missing_values[missing_values > 0].to_string())

Columns with missing values:

1970    3195
1971    2835
1972    2856
1973    2868
1974    2882
1975    2874
1976    2882
1977    2862
1978    2869
1979    2824
1980    2835
1981    2811
1982    2840
1983    2847
1984    2833
1985    2841
1986    2811
1987    2856
1988    2880
1989    2863
1990    2855
1991    2855
1992    2852
1993    2861
1994    2880
1995    2866
1996    2875
1997    2928
1998    2832
1999    2264
2000    2286
2001    2286
2002    2206
2003    2172
2004    2163
2005    2193
2006    2210
2007    2195
2008    2117
2009    2097
2010    2058
2011    2029
2012    1918
2013    1614
2014    1826
2015    3022
2016    3367
2017    3388
2020    3388
2025    3388
2030    3388
2035    3388
2040    3388
2045    3388
2050    3388
2055    3388
2060    3388
2065    3388
2070    3388
2075    3388
2080    3388
2085    3388
2090    3388
2095    3388
2100    3388

In [ ]:
year_columns = [
    col for col in wb_selected.columns
    if str(col).isdigit()
]

empty_years = [
    col for col in year_columns
    if wb_selected[col].isna().all()
]

print("Completely empty years:")
print(empty_years)

wb_selected_clean = wb_selected.drop(columns=empty_years)

print("\nRemaining columns:", len(wb_selected_clean.columns))

Completely empty years:
['2017', '2020', '2025', '2030', '2035', '2040', '2045', '2050', '2055', '2060', '2065', '2070', '2075', '2080', '2085', '2090', '2095', '2100']

Remaining columns: 51

In [ ]:
print("Rows:", len(wb_selected_clean))
print("Columns:", len(wb_selected_clean.columns))
print("Countries:", wb_selected_clean["Country Code"].nunique())
print("Indicators:", wb_selected_clean["Indicator Code"].nunique())

print("\nIndicators present:")
print(wb_selected_clean["Indicator Code"].unique())

Rows: 3388
Columns: 51
Countries: 242
Indicators: 14

Indicators present:
['UIS.TE_100000.56' 'UIS.TE_100000.56.F' 'UIS.TE_100000.56.M'
 'SE.TER.ENRL' 'SE.TER.ENRL.FE' 'UIS.E.5.B' 'UIS.E.5.B.F' 'UIS.E.6'
 'UIS.E.6.F' 'UIS.E.7' 'UIS.E.7.F' 'UIS.E.8' 'UIS.E.8.F' 'SE.TER.PRIV.ZS']

In [ ]:
country_names = (
    wb_selected_clean[["Country Code", "Country Name"]]
    .drop_duplicates()
    .sort_values("Country Name")
)

print("Unique country records:", len(country_names))
print("\nFirst 50 country names:")
print(country_names.head(50).to_string(index=False))

Unique country records: 242

First 50 country names:
Country Code             Country Name
         AFG              Afghanistan
         ALB                  Albania
         DZA                  Algeria
         ASM           American Samoa
         AND                  Andorra
         AGO                   Angola
         ATG      Antigua and Barbuda
         ARB               Arab World
         ARG                Argentina
         ARM                  Armenia
         ABW                    Aruba
         AUS                Australia
         AUT                  Austria
         AZE               Azerbaijan
         BHS             Bahamas, The
         BHR                  Bahrain
         BGD               Bangladesh
         BRB                 Barbados
         BLR                  Belarus
         BEL                  Belgium
         BLZ                   Belize
         BEN                    Benin
         BMU                  Bermuda
         BTN                   Bhutan
         BOL                  Bolivia
         BIH   Bosnia and Herzegovina
         BWA                 Botswana
         BRA                   Brazil
         VGB   British Virgin Islands
         BRN        Brunei Darussalam
         BGR                 Bulgaria
         BFA             Burkina Faso
         BDI                  Burundi
         CPV               Cabo Verde
         KHM                 Cambodia
         CMR                 Cameroon
         CAN                   Canada
         CYM           Cayman Islands
         CAF Central African Republic
         TCD                     Chad
         CHI          Channel Islands
         CHL                    Chile
         CHN                    China
         COL                 Colombia
         COM                  Comoros
         COD         Congo, Dem. Rep.
         COG              Congo, Rep.
         CRI               Costa Rica
         CIV            Cote d'Ivoire
         HRV                  Croatia

In [ ]:
aggregate_keywords = [
    "World",
    "income",
    "IDA",
    "IBRD",
    "Euro area",
    "European Union",
    "Arab World",
    "Central Europe",
    "Pacific",
    "Caribbean",
    "Africa",
    "Asia",
    "America"
]

possible_aggregates = country_names[
    country_names["Country Name"].str.contains(
        "|".join(aggregate_keywords),
        case=False,
        na=False
    )
]

print("Possible aggregate/non-country entities:")
print(possible_aggregates.to_string(index=False))

Possible aggregate/non-country entities:
Country Code                                       Country Name
         ASM                                     American Samoa
         ARB                                         Arab World
         CAF                           Central African Republic
         EAS                                East Asia & Pacific
         EAP        East Asia & Pacific (excluding high income)
         EMU                                          Euro area
         ECS                              Europe & Central Asia
         ECA      Europe & Central Asia (excluding high income)
         EUU                                     European Union
         HIC                                        High income
         LCN                          Latin America & Caribbean
         LAC  Latin America & Caribbean (excluding high income)
         LMY                                Low & middle income
         LIC                                         Low income
         LMC                                Lower middle income
         MEA                         Middle East & North Africa
         MNA Middle East & North Africa (excluding high income)
         MIC                                      Middle income
         NAC                                      North America
         ZAF                                       South Africa
         SAS                                         South Asia
         SSF                                 Sub-Saharan Africa
         SSA         Sub-Saharan Africa (excluding high income)
         TTO                                Trinidad and Tobago
         UMC                                Upper middle income
         WLD                                              World

In [ ]:
with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("EdStatsCountry.csv") as f:
        wb_country_info = pd.read_csv(f)

print("Rows:", len(wb_country_info))
print("Columns:", len(wb_country_info.columns))
print("\nColumns:")
print(wb_country_info.columns.tolist())

Rows: 241
Columns: 32

Columns:
['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code', 'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code', 'National accounts base year', 'National accounts reference year', 'SNA price valuation', 'Lending category', 'Other groups', 'System of National Accounts', 'Alternative conversion factor', 'PPP survey year', 'Balance of Payments Manual in use', 'External debt Reporting status', 'System of trade', 'Government Accounting concept', 'IMF data dissemination standard', 'Latest population census', 'Latest household survey', 'Source of most recent Income and expenditure data', 'Vital registration complete', 'Latest agricultural census', 'Latest industrial data', 'Latest trade data', 'Latest water withdrawal data', 'Unnamed: 31']

In [ ]:
print("Region value counts:\n")
print(wb_country_info["Region"].value_counts(dropna=False).to_string())

print("\nRecords with missing Region:")
print(
    wb_country_info[
        wb_country_info["Region"].isna()
    ][["Country Code", "Short Name", "Region"]].to_string(index=False)
)

Region value counts:

Region
Europe & Central Asia         57
Sub-Saharan Africa            48
Latin America & Caribbean     41
East Asia & Pacific           36
NaN                           27
Middle East & North Africa    21
South Asia                     8
North America                  3

Records with missing Region:
Country Code                                     Short Name Region
         ARB                                     Arab World    NaN
         EAP          East Asia & Pacific (developing only)    NaN
         EAS        East Asia & Pacific (all income levels)    NaN
         ECA        Europe & Central Asia (developing only)    NaN
         ECS      Europe & Central Asia (all income levels)    NaN
         EMU                                      Euro area    NaN
         EUU                                 European Union    NaN
         GIB                                      Gibraltar    NaN
         HIC                                    High income    NaN
         HPC         Heavily indebted poor countries (HIPC)    NaN
         LAC    Latin America & Caribbean (developing only)    NaN
         LCN  Latin America & Caribbean (all income levels)    NaN
         LDC   Least developed countries: UN classification    NaN
         LIC                                     Low income    NaN
         LMC                            Lower middle income    NaN
         LMY                            Low & middle income    NaN
         MEA Middle East & North Africa (all income levels)    NaN
         MIC                                  Middle income    NaN
         MNA   Middle East & North Africa (developing only)    NaN
         NAC                                  North America    NaN
         NRU                                          Nauru    NaN
         OED                                   OECD members    NaN
         SAS                                     South Asia    NaN
         SSA           Sub-Saharan Africa (developing only)    NaN
         SSF         Sub-Saharan Africa (all income levels)    NaN
         UMC                            Upper middle income    NaN
         WLD                                          World    NaN

In [ ]:
non_region_codes = wb_country_info[
    wb_country_info["Region"].isna()
][["Country Code", "Short Name"]].copy()

print("Records without a World Bank region:")
print(non_region_codes.to_string(index=False))

Records without a World Bank region:
Country Code                                     Short Name
         ARB                                     Arab World
         EAP          East Asia & Pacific (developing only)
         EAS        East Asia & Pacific (all income levels)
         ECA        Europe & Central Asia (developing only)
         ECS      Europe & Central Asia (all income levels)
         EMU                                      Euro area
         EUU                                 European Union
         GIB                                      Gibraltar
         HIC                                    High income
         HPC         Heavily indebted poor countries (HIPC)
         LAC    Latin America & Caribbean (developing only)
         LCN  Latin America & Caribbean (all income levels)
         LDC   Least developed countries: UN classification
         LIC                                     Low income
         LMC                            Lower middle income
         LMY                            Low & middle income
         MEA Middle East & North Africa (all income levels)
         MIC                                  Middle income
         MNA   Middle East & North Africa (developing only)
         NAC                                  North America
         NRU                                          Nauru
         OED                                   OECD members
         SAS                                     South Asia
         SSA           Sub-Saharan Africa (developing only)
         SSF         Sub-Saharan Africa (all income levels)
         UMC                            Upper middle income
         WLD                                          World

In [ ]:
aggregate_codes = [
    "ARB", "EAP", "EAS", "ECA", "ECS", "EMU", "EUU",
    "HIC", "HPC", "LAC", "LCN", "LDC", "LIC", "LMC",
    "LMY", "MEA", "MIC", "MNA", "NAC", "OED", "SAS",
    "SSA", "SSF", "UMC", "WLD"
]

wb_final = wb_selected_clean[
    ~wb_selected_clean["Country Code"].isin(aggregate_codes)
].copy()

print("World Bank cleaned successfully!")
print("Rows:", len(wb_final))
print("Countries:", wb_final["Country Code"].nunique())
print("Indicators:", wb_final["Indicator Code"].nunique())

World Bank cleaned successfully!
Rows: 3038
Countries: 217
Indicators: 14

In [ ]:
print("===== WORLD BANK FINAL VALIDATION =====")
print("Rows:", len(wb_final))
print("Columns:", len(wb_final.columns))
print("Countries:", wb_final["Country Code"].nunique())
print("Indicators:", wb_final["Indicator Code"].nunique())
print("Duplicate rows:", wb_final.duplicated().sum())
print("Duplicate country-indicator records:",
      wb_final.duplicated(["Country Code", "Indicator Code"]).sum())
print("Missing country codes:", wb_final["Country Code"].isna().sum())
print("Missing indicator codes:", wb_final["Indicator Code"].isna().sum())

===== WORLD BANK FINAL VALIDATION =====
Rows: 3038
Columns: 51
Countries: 217
Indicators: 14
Duplicate rows: 0
Duplicate country-indicator records: 0
Missing country codes: 0
Missing indicator codes: 0

In [ ]:
wb_output_path = os.path.join(
    CLEANED_PATH,
    "World_Bank_Tertiary_Education_Cleaned.csv"
)

wb_final.to_csv(wb_output_path, index=False)

print("World Bank cleaned dataset saved successfully!")
print(wb_output_path)

World Bank cleaned dataset saved successfully!
/content/drive/MyDrive/EduVision_DV/02_Cleaned_Data/World_Bank_Tertiary_Education_Cleaned.csv

In [ ]:
cleaned_files = [
    "QS_2025_Cleaned.csv",
    "THE_2024_Cleaned.csv",
    "WUR_2023_Cleaned.csv",
    "World_Bank_Tertiary_Education_Cleaned.csv"
]

print("===== MILESTONE 1 FINAL DATASET CHECK =====\n")

for file in cleaned_files:
    path = os.path.join(CLEANED_PATH, file)

    if os.path.exists(path):
        df = pd.read_csv(path)

        print(f"✓ {file}")
        print(f"  Rows: {len(df)}")
        print(f"  Columns: {len(df.columns)}")
        print(f"  Duplicate rows: {df.duplicated().sum()}")
        print()
    else:
        print(f"✗ MISSING: {file}")

===== MILESTONE 1 FINAL DATASET CHECK =====

✓ QS_2025_Cleaned.csv
  Rows: 1503
  Columns: 28
  Duplicate rows: 0

✓ THE_2024_Cleaned.csv
  Rows: 2673
  Columns: 29
  Duplicate rows: 0

✓ WUR_2023_Cleaned.csv
  Rows: 2311
  Columns: 13
  Duplicate rows: 0

✓ World_Bank_Tertiary_Education_Cleaned.csv
  Rows: 3038
  Columns: 51
  Duplicate rows: 0

In [ ]:
required_columns = {
    "QS_2025_Cleaned.csv": ["Institution_Name", "Location", "RANK_2025", "Overall_Score"],
    "THE_2024_Cleaned.csv": ["name", "location", "rank", "scores_overall"],
    "WUR_2023_Cleaned.csv": ["Name of University", "Location", "University Rank", "OverAll Score"],
    "World_Bank_Tertiary_Education_Cleaned.csv": [
        "Country Name", "Country Code", "Indicator Name", "Indicator Code"
    ]
}

print("===== REQUIRED COLUMN CHECK =====\n")

for file, columns in required_columns.items():
    df = pd.read_csv(os.path.join(CLEANED_PATH, file))

    missing_columns = [col for col in columns if col not in df.columns]

    if not missing_columns:
        print(f"✓ {file} — All required columns present")
    else:
        print(f"✗ {file} — Missing columns: {missing_columns}")

===== REQUIRED COLUMN CHECK =====

✓ QS_2025_Cleaned.csv — All required columns present
✓ THE_2024_Cleaned.csv — All required columns present
✓ WUR_2023_Cleaned.csv — All required columns present
✓ World_Bank_Tertiary_Education_Cleaned.csv — All required columns present

In [ ]:
validation_summary = pd.DataFrame({
    "Dataset": [
        "QS World University Rankings 2025",
        "THE World University Rankings 2024",
        "World University Rankings 2023",
        "World Bank Tertiary Education"
    ],
    "Rows": [1503, 2673, 2311, 3038],
    "Columns": [28, 29, 13, 51],
    "Duplicate_Rows": [0, 0, 0, 0],
    "Status": ["PASS", "PASS", "PASS", "PASS"]
})

print("===== MILESTONE 1 VALIDATION SUMMARY =====")
print(validation_summary.to_string(index=False))

===== MILESTONE 1 VALIDATION SUMMARY =====
                           Dataset  Rows  Columns  Duplicate_Rows Status
 QS World University Rankings 2025  1503       28               0   PASS
THE World University Rankings 2024  2673       29               0   PASS
    World University Rankings 2023  2311       13               0   PASS
     World Bank Tertiary Education  3038       51               0   PASS

In [ ]:
REPORT_PATH = os.path.join(PROJECT_PATH, "04_Reports")

validation_file = os.path.join(
    REPORT_PATH,
    "Milestone1_Validation_Summary.csv"
)

validation_summary.to_csv(validation_file, index=False)

print("Milestone 1 validation summary saved successfully!")
print(validation_file)

Milestone 1 validation summary saved successfully!
/content/drive/MyDrive/EduVision_DV/04_Reports/Milestone1_Validation_Summary.csv

In [ ]:
import pandas as pd
import os
import re

# Load the cleaned datasets
qs_clean = pd.read_csv(
    os.path.join(CLEANED_PATH, "QS_2025_Cleaned.csv")
)

the_clean = pd.read_csv(
    os.path.join(CLEANED_PATH, "THE_2024_Cleaned.csv")
)

wur_clean = pd.read_csv(
    os.path.join(CLEANED_PATH, "WUR_2023_Cleaned.csv")
)

# Function to standardize university names
def standardize_university_name(series):
    return (
        series.astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"[^\w\s]", "", regex=True)
        .str.replace(r"\s+", " ", regex=True)
    )

# Create standardized name columns
qs_clean["university_name_std"] = standardize_university_name(
    qs_clean["Institution_Name"]
)

the_clean["university_name_std"] = standardize_university_name(
    the_clean["name"]
)

wur_clean["university_name_std"] = standardize_university_name(
    wur_clean["Name of University"]
)

print("===== UNIVERSITY NAME STANDARDIZATION =====")
print("QS 2025:", qs_clean["university_name_std"].notna().sum(), "names standardized")
print("THE 2024:", the_clean["university_name_std"].notna().sum(), "names standardized")
print("WUR 2023:", wur_clean["university_name_std"].notna().sum(), "names standardized")

print("\nExamples:")
print("\nQS:")
print(qs_clean[["Institution_Name", "university_name_std"]].dropna().head(5).to_string(index=False))

print("\nTHE:")
print(the_clean[["name", "university_name_std"]].dropna().head(5).to_string(index=False))

print("\nWUR:")
print(wur_clean[["Name of University", "university_name_std"]].dropna().head(5).to_string(index=False))

===== UNIVERSITY NAME STANDARDIZATION =====
QS 2025: 1503 names standardized
THE 2024: 2673 names standardized
WUR 2023: 2233 names standardized

Examples:

QS:
                           Institution_Name                       university_name_std
Massachusetts Institute of Technology (MIT) massachusetts institute of technology mit
                    Imperial College London                   imperial college london
                       University of Oxford                      university of oxford
                         Harvard University                        harvard university
                    University of Cambridge                   university of cambridge

THE:
                                 name                   university_name_std
                 University of Oxford                  university of oxford
                  Stanford University                   stanford university
Massachusetts Institute of Technology massachusetts institute of technology
                   Harvard University                    harvard university
              University of Cambridge               university of cambridge

WUR:
                   Name of University                   university_name_std
                 University of Oxford                  university of oxford
                   Harvard University                    harvard university
              University of Cambridge               university of cambridge
                  Stanford University                   stanford university
Massachusetts Institute of Technology massachusetts institute of technology

In [ ]:
# World Bank country reference
country_reference = (
    wb_country_info[["Country Code", "Short Name"]]
    .dropna()
    .drop_duplicates()
    .copy()
)

# Create a lookup using lowercase country names
country_lookup = {
    name.strip().lower(): name
    for name in country_reference["Short Name"]
}

# Common naming differences found in ranking datasets
country_aliases = {
    "usa": "United States",
    "united states of america": "United States",
    "uk": "United Kingdom",
    "u.k.": "United Kingdom",
    "russia": "Russian Federation",
    "south korea": "Korea, Rep.",
    "republic of korea": "Korea, Rep.",
    "iran": "Iran, Islamic Rep.",
    "vietnam": "Viet Nam",
    "venezuela": "Venezuela, RB",
    "bolivia": "Bolivia",
    "tanzania": "Tanzania",
    "moldova": "Moldova",
    "laos": "Lao PDR",
    "egypt": "Egypt, Arab Rep."
}

def standardize_country_name(series):
    result = series.astype("string").str.strip()

    result = result.map(
        lambda x: (
            pd.NA
            if pd.isna(x)
            else country_aliases.get(
                x.lower(),
                country_lookup.get(x.lower(), x)
            )
        )
    )

    return result

# Standardize country names
qs_clean["country_name_std"] = standardize_country_name(
    qs_clean["Location"]
)

the_clean["country_name_std"] = standardize_country_name(
    the_clean["location"]
)

wur_clean["country_name_std"] = standardize_country_name(
    wur_clean["Location"]
)

print("===== COUNTRY NAME STANDARDIZATION =====")
print("QS countries:", qs_clean["country_name_std"].nunique())
print("THE countries:", the_clean["country_name_std"].nunique())
print("WUR countries:", wur_clean["country_name_std"].nunique())

print("\nExamples:")
print("\nQS:")
print(
    qs_clean[["Location", "country_name_std"]]
    .drop_duplicates()
    .head(10)
    .to_string(index=False)
)

print("\nTHE:")
print(
    the_clean[["location", "country_name_std"]]
    .drop_duplicates()
    .head(10)
    .to_string(index=False)
)

print("\nWUR:")
print(
    wur_clean[["Location", "country_name_std"]]
    .drop_duplicates()
    .head(10)
    .to_string(index=False)
)

===== COUNTRY NAME STANDARDIZATION =====
QS countries: 106
THE countries: 127
WUR countries: 116

Examples:

QS:
        Location country_name_std
   United States    United States
  United Kingdom   United Kingdom
     Switzerland      Switzerland
       Singapore        Singapore
       Australia        Australia
China (Mainland) China (Mainland)
   Hong Kong SAR    Hong Kong SAR
          France           France
          Canada           Canada
         Germany          Germany

THE:
      location country_name_std
United Kingdom   United Kingdom
 United States    United States
   Switzerland      Switzerland
         China            China
     Singapore        Singapore
        Canada           Canada
         Japan            Japan
       Germany          Germany
     Hong Kong        Hong Kong
     Australia        Australia

WUR:
      Location country_name_std
United Kingdom   United Kingdom
 United States    United States
   Switzerland      Switzerland
           NaN             <NA>
        Canada           Canada
     Australia        Australia
     Singapore        Singapore
         Japan            Japan
        France           France
        Sweden           Sweden

In [ ]:
# Create a master list of unique university + country combinations
university_master = pd.concat([
    qs_clean[["university_name_std", "country_name_std"]],
    the_clean[["university_name_std", "country_name_std"]],
    wur_clean[["university_name_std", "country_name_std"]]
], ignore_index=True)

# Remove records where university name is missing
university_master = university_master.dropna(
    subset=["university_name_std"]
).drop_duplicates()

# Create a stable University ID
university_master = university_master.sort_values(
    ["university_name_std", "country_name_std"],
    na_position="last"
).reset_index(drop=True)

university_master["university_id"] = [
    f"U{i:05d}" for i in range(1, len(university_master) + 1)
]

# Create lookup key
university_master["university_key"] = (
    university_master["university_name_std"]
    + "||"
    + university_master["country_name_std"].fillna("")
)

# Apply IDs to each dataset
def add_university_id(df):
    df["university_key"] = (
        df["university_name_std"]
        + "||"
        + df["country_name_std"].fillna("")
    )

    return df.merge(
        university_master[["university_key", "university_id"]],
        on="university_key",
        how="left"
    )

qs_clean = add_university_id(qs_clean)
the_clean = add_university_id(the_clean)
wur_clean = add_university_id(wur_clean)

print("===== UNIVERSITY ID CREATION =====")
print("Unique universities in master:", len(university_master))

print("\nQS IDs created:",
      qs_clean["university_id"].notna().sum())

print("THE IDs created:",
      the_clean["university_id"].notna().sum())

print("WUR IDs created:",
      wur_clean["university_id"].notna().sum())

print("\nMissing University IDs:")
print("QS:", qs_clean["university_id"].isna().sum())
print("THE:", the_clean["university_id"].isna().sum())
print("WUR:", wur_clean["university_id"].isna().sum())

print("\nSample University IDs:")
print(
    university_master[
        ["university_id", "university_name_std", "country_name_std"]
    ].head(10).to_string(index=False)
)

===== UNIVERSITY ID CREATION =====
Unique universities in master: 3745

QS IDs created: 1503
THE IDs created: 2673
WUR IDs created: 2233

Missing University IDs:
QS: 0
THE: 0
WUR: 78

Sample University IDs:
university_id                             university_name_std country_name_std
       U00001                              aalborg university          Denmark
       U00002                                aalto university          Finland
       U00003                               aarhus university          Denmark
       U00004     abai kazakh national pedagogical university       Kazakhstan
       U00005          abbes laghrour university of khenchala          Algeria
       U00006 abbottabad university of science and technology         Pakistan
       U00007   abdelhafid boussouf university center of mila          Algeria
       U00008                   abdelmalek essaâdi university          Morocco
       U00009               abdul wali khan university mardan         Pakistan
       U00010                         abdullah gül university           Turkey

In [ ]:
# Count how many university IDs appear in each dataset
qs_ids = set(qs_clean["university_id"].dropna())
the_ids = set(the_clean["university_id"].dropna())
wur_ids = set(wur_clean["university_id"].dropna())

# Find IDs common between datasets
qs_the_common = qs_ids & the_ids
qs_wur_common = qs_ids & wur_ids
the_wur_common = the_ids & wur_ids
all_three_common = qs_ids & the_ids & wur_ids

print("===== UNIVERSITY ID MATCHING VALIDATION =====")

print("QS universities:", len(qs_ids))
print("THE universities:", len(the_ids))
print("WUR universities:", len(wur_ids))

print("\nCommon universities:")
print("QS + THE:", len(qs_the_common))
print("QS + WUR:", len(qs_wur_common))
print("THE + WUR:", len(the_wur_common))
print("All three datasets:", len(all_three_common))

print("\nSample universities present in all three:")

sample_ids = list(all_three_common)[:10]

sample = university_master[
    university_master["university_id"].isin(sample_ids)
][
    ["university_id", "university_name_std", "country_name_std"]
]

print(sample.to_string(index=False))

===== UNIVERSITY ID MATCHING VALIDATION =====
QS universities: 1503
THE universities: 2673
WUR universities: 2233

Common universities:
QS + THE: 752
QS + WUR: 618
THE + WUR: 1897
All three datasets: 603

Sample universities present in all three:
university_id             university_name_std country_name_std
       U00183               assiut university Egypt, Arab Rep.
       U01242     leibniz university hannover          Germany
       U01508   national tsing hua university           Taiwan
       U02069 stevens institute of technology    United States
       U02126                tanta university Egypt, Arab Rep.
       U02188             tel aviv university           Israel
       U02761             university of basel      Switzerland
       U03071           university of maribor         Slovenia
       U03214         university of rochester    United States
       U03364           university of trieste            Italy

In [ ]:
# Create country master from World Bank country information
country_master = (
    wb_country_info[["Country Code", "Short Name"]]
    .dropna(subset=["Country Code", "Short Name"])
    .drop_duplicates()
    .copy()
)

# Create Country_ID
country_master = country_master.sort_values("Country Code").reset_index(drop=True)

country_master["country_id"] = [
    f"C{i:03d}" for i in range(1, len(country_master) + 1)
]

# Create lookup from standardized country name to Country_ID
country_id_lookup = dict(
    zip(
        country_master["Short Name"].str.strip().str.lower(),
        country_master["country_id"]
    )
)

# Add Country_ID to university master
university_master["country_id"] = (
    university_master["country_name_std"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map(country_id_lookup)
)

print("===== COUNTRY ID CREATION =====")
print("Countries in master:", len(country_master))

print("\nUniversity master records:", len(university_master))
print(
    "University records with Country_ID:",
    university_master["country_id"].notna().sum()
)
print(
    "University records missing Country_ID:",
    university_master["country_id"].isna().sum()
)

print("\nSample Country IDs:")
print(
    country_master[
        ["country_id", "Country Code", "Short Name"]
    ].head(10).to_string(index=False)
)

===== COUNTRY ID CREATION =====
Countries in master: 241

University master records: 3745
University records with Country_ID: 3056
University records missing Country_ID: 689

Sample Country IDs:
country_id Country Code           Short Name
      C001          ABW                Aruba
      C002          AFG          Afghanistan
      C003          AGO               Angola
      C004          ALB              Albania
      C005          AND              Andorra
      C006          ARB           Arab World
      C007          ARE United Arab Emirates
      C008          ARG            Argentina
      C009          ARM              Armenia
      C010          ASM       American Samoa

In [ ]:
unmatched_countries = (
    university_master[
        university_master["country_id"].isna()
    ]["country_name_std"]
    .value_counts(dropna=False)
)

print("===== UNMATCHED COUNTRY NAMES =====")
print("Number of different unmatched country names:",
      len(unmatched_countries))

print("\nUnmatched country names and record counts:")
print(unmatched_countries.to_string())

===== UNMATCHED COUNTRY NAMES =====
Number of different unmatched country names: 21

Unmatched country names and record counts:
country_name_std
<NA>                               186
Russian Federation                 127
Iran, Islamic Rep.                  82
China (Mainland)                    71
Korea, Rep.                         52
Taiwan                              50
Egypt, Arab Rep.                    42
Slovakia                            12
Venezuela, RB                       11
Iran, Islamic Republic of            9
Viet Nam                             8
Hong Kong SAR                        7
Palestine                            7
Hong Kong                            6
Northern Cyprus                      5
Palestinian Territory, Occupied      3
Kyrgyzstan                           3
Macao                                3
Macau SAR                            2
Brunei Darussalam                    2
North Macedonia                      1

In [ ]:
country_aliases_final = {
    "Russian Federation": "Russian Federation",
    "Iran, Islamic Rep.": "Iran, Islamic Rep.",
    "Iran, Islamic Republic of": "Iran, Islamic Rep.",
    "China (Mainland)": "China",
    "Korea, Rep.": "Korea, Rep.",
    "Taiwan": "Taiwan",
    "Egypt, Arab Rep.": "Egypt, Arab Rep.",
    "Slovakia": "Slovak Republic",
    "Venezuela, RB": "Venezuela, RB",
    "Viet Nam": "Viet Nam",
    "Hong Kong SAR": "Hong Kong SAR, China",
    "Hong Kong": "Hong Kong SAR, China",
    "Palestine": "West Bank and Gaza",
    "Palestinian Territory, Occupied": "West Bank and Gaza",
    "Northern Cyprus": "Northern Cyprus",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Macao": "Macao SAR, China",
    "Macau SAR": "Macao SAR, China",
    "Brunei Darussalam": "Brunei Darussalam",
    "North Macedonia": "North Macedonia"
}

# Apply only explicit mappings
university_master["country_name_std"] = (
    university_master["country_name_std"]
    .map(lambda x: country_aliases_final.get(x, x)
         if pd.notna(x) else pd.NA)
)

# Re-create Country_ID lookup
country_id_lookup = dict(
    zip(
        country_master["Short Name"].str.strip().str.lower(),
        country_master["country_id"]
    )
)

# Assign Country_ID again
university_master["country_id"] = (
    university_master["country_name_std"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map(country_id_lookup)
)

print("===== COUNTRY ID VALIDATION =====")
print("University master records:", len(university_master))
print(
    "Records with Country_ID:",
    university_master["country_id"].notna().sum()
)
print(
    "Records missing Country_ID:",
    university_master["country_id"].isna().sum()
)

print("\nRemaining unmatched country names:")
print(
    university_master[
        university_master["country_id"].isna()
    ]["country_name_std"]
    .value_counts(dropna=False)
    .to_string()
)

===== COUNTRY ID VALIDATION =====
University master records: 3745
Records with Country_ID: 3170
Records missing Country_ID: 575

Remaining unmatched country names:
country_name_std
<NA>                  186
Russian Federation    127
Iran, Islamic Rep.     91
Korea, Rep.            52
Taiwan                 50
Egypt, Arab Rep.       42
Venezuela, RB          11
Viet Nam                8
Northern Cyprus         5
Brunei Darussalam       2
North Macedonia         1

In [ ]:
# Explicit mapping to World Bank country codes
country_code_map = {
    "Russian Federation": "RUS",
    "Iran, Islamic Rep.": "IRN",
    "Korea, Rep.": "KOR",
    "Egypt, Arab Rep.": "EGY",
    "Venezuela, RB": "VEN",
    "Viet Nam": "VNM",
    "Brunei Darussalam": "BRN",
    "North Macedonia": "MKD"
}

# Create Country Code -> Country_ID lookup
code_to_id = dict(
    zip(
        country_master["Country Code"],
        country_master["country_id"]
    )
)

# Start with existing Country_ID values
university_master["country_id"] = (
    university_master["country_id"]
)

# Apply explicit World Bank code mappings
for country_name, country_code in country_code_map.items():
    mask = university_master["country_name_std"] == country_name
    university_master.loc[mask, "country_id"] = code_to_id.get(country_code)

print("===== FINAL COUNTRY ID CHECK =====")
print("Total university records:", len(university_master))
print(
    "Records with Country_ID:",
    university_master["country_id"].notna().sum()
)
print(
    "Records still missing Country_ID:",
    university_master["country_id"].isna().sum()
)

print("\nRemaining unmatched country names:")
print(
    university_master[
        university_master["country_id"].isna()
    ]["country_name_std"]
    .value_counts(dropna=False)
    .to_string()
)

===== FINAL COUNTRY ID CHECK =====
Total university records: 3745
Records with Country_ID: 3504
Records still missing Country_ID: 241

Remaining unmatched country names:
country_name_std
<NA>               186
Taiwan              50
Northern Cyprus      5

In [ ]:
# Add Country_ID from the university master
country_lookup_master = (
    university_master[
        ["university_key", "country_id"]
    ]
    .drop_duplicates("university_key")
)

# Remove old country_id if it exists
for df in [qs_clean, the_clean, wur_clean]:
    if "country_id" in df.columns:
        df.drop(columns=["country_id"], inplace=True)

# Add Country_ID
qs_clean = qs_clean.merge(
    country_lookup_master,
    on="university_key",
    how="left"
)

the_clean = the_clean.merge(
    country_lookup_master,
    on="university_key",
    how="left"
)

wur_clean = wur_clean.merge(
    country_lookup_master,
    on="university_key",
    how="left"
)

print("===== FINALIZED UNIVERSITY DATASETS =====")

for name, df in [
    ("QS 2025", qs_clean),
    ("THE 2024", the_clean),
    ("WUR 2023", wur_clean)
]:
    print(f"\n{name}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("University IDs:", df["university_id"].notna().sum())
    print("Country IDs:", df["country_id"].notna().sum())
    print("Duplicate rows:", df.duplicated().sum())

===== FINALIZED UNIVERSITY DATASETS =====

QS 2025
Rows: 1503
Columns: 33
University IDs: 1503
Country IDs: 1475
Duplicate rows: 0

THE 2024
Rows: 2673
Columns: 34
University IDs: 2673
Country IDs: 2620
Duplicate rows: 0

WUR 2023
Rows: 2311
Columns: 18
University IDs: 2233
Country IDs: 2005
Duplicate rows: 0

In [ ]:
# DIM_UNIVERSITY

dim_university = university_master[
    [
        "university_id",
        "university_name_std",
        "country_id",
        "country_name_std"
    ]
].copy()

# Rename columns to final model names
dim_university.rename(
    columns={
        "university_name_std": "university_name",
        "country_name_std": "country_name"
    },
    inplace=True
)

# Add country region from World Bank reference
region_lookup = dict(
    zip(
        wb_country_info["Short Name"].str.strip().str.lower(),
        wb_country_info["Region"]
    )
)

dim_university["region"] = (
    dim_university["country_name"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map(region_lookup)
)

# -------------------------------
# DIM_COUNTRY
# -------------------------------

dim_country = country_master[
    ["country_id", "Country Code", "Short Name"]
].copy()

dim_country.rename(
    columns={
        "Country Code": "country_code",
        "Short Name": "country_name"
    },
    inplace=True
)

# Add region
dim_country["region"] = (
    dim_country["country_name"]
    .str.strip()
    .str.lower()
    .map(region_lookup)
)

# -------------------------------
# VALIDATION
# -------------------------------

print("===== DIMENSION TABLES =====")

print("\nDIM_UNIVERSITY")
print("Rows:", len(dim_university))
print("Columns:", len(dim_university.columns))
print("Duplicate University IDs:",
      dim_university["university_id"].duplicated().sum())

print("\nDIM_COUNTRY")
print("Rows:", len(dim_country))
print("Columns:", len(dim_country.columns))
print("Duplicate Country IDs:",
      dim_country["country_id"].duplicated().sum())

print("\nSample DIM_UNIVERSITY:")
print(dim_university.head(10).to_string(index=False))

print("\nSample DIM_COUNTRY:")
print(dim_country.head(10).to_string(index=False))

===== DIMENSION TABLES =====

DIM_UNIVERSITY
Rows: 3745
Columns: 5
Duplicate University IDs: 0

DIM_COUNTRY
Rows: 241
Columns: 4
Duplicate Country IDs: 0

Sample DIM_UNIVERSITY:
university_id                                 university_name country_id country_name                     region
       U00001                              aalborg university       C055      Denmark      Europe & Central Asia
       U00002                                aalto university       C070      Finland      Europe & Central Asia
       U00003                               aarhus university       C055      Denmark      Europe & Central Asia
       U00004     abai kazakh national pedagogical university       C109   Kazakhstan      Europe & Central Asia
       U00005          abbes laghrour university of khenchala       C057      Algeria Middle East & North Africa
       U00006 abbottabad university of science and technology       C171     Pakistan                 South Asia
       U00007   abdelhafid boussouf university center of mila       C057      Algeria Middle East & North Africa
       U00008                   abdelmalek essaâdi university       C136      Morocco Middle East & North Africa
       U00009               abdul wali khan university mardan       C171     Pakistan                 South Asia
       U00010                         abdullah gül university       C221       Turkey      Europe & Central Asia

Sample DIM_COUNTRY:
country_id country_code         country_name                     region
      C001          ABW                Aruba  Latin America & Caribbean
      C002          AFG          Afghanistan                 South Asia
      C003          AGO               Angola         Sub-Saharan Africa
      C004          ALB              Albania      Europe & Central Asia
      C005          AND              Andorra      Europe & Central Asia
      C006          ARB           Arab World                        NaN
      C007          ARE United Arab Emirates Middle East & North Africa
      C008          ARG            Argentina  Latin America & Caribbean
      C009          ARM              Armenia      Europe & Central Asia
      C010          ASM       American Samoa        East Asia & Pacific

In [ ]:
# 1. FACT UNIVERSITY PERFORMANCE


fact_university_performance = qs_clean[
    [
        "university_id",
        "RANK_2025",
        "Overall_Score",
        "Academic_Reputation_Score",
        "Employer_Reputation_Score"
    ]
].copy()

fact_university_performance["year"] = 2025

fact_university_performance.rename(
    columns={
        "RANK_2025": "global_rank",
        "Overall_Score": "overall_score",
        "Academic_Reputation_Score": "academic_reputation",
        "Employer_Reputation_Score": "employer_reputation"
    },
    inplace=True
)

fact_university_performance = fact_university_performance[
    [
        "university_id",
        "year",
        "global_rank",
        "overall_score",
        "academic_reputation",
        "employer_reputation"
    ]
]


# ==========================================
# 2. FACT RESEARCH
# ==========================================

fact_research = the_clean[
    [
        "university_id",
        "scores_research",
        "scores_citations"
    ]
].copy()

fact_research["year"] = 2024

fact_research.rename(
    columns={
        "scores_research": "research_score",
        "scores_citations": "citation_score"
    },
    inplace=True
)

# Research productivity is NOT invented here.
# It requires an approved formula according to the mentor guide.
fact_research["research_impact"] = pd.NA
fact_research["research_productivity"] = pd.NA

fact_research = fact_research[
    [
        "university_id",
        "year",
        "research_score",
        "citation_score",
        "research_impact",
        "research_productivity"
    ]
]


# ==========================================
# 3. FACT STUDENT
# ==========================================

fact_student = wur_clean[
    [
        "university_id",
        "No of student",
        "No of student per staff",
        "International Student"
    ]
].copy()

fact_student["year"] = 2023

fact_student.rename(
    columns={
        "No of student": "total_students",
        "No of student per staff": "students_per_staff",
        "International Student": "international_student_percentage"
    },
    inplace=True
)

fact_student["international_students"] = pd.NA

fact_student = fact_student[
    [
        "university_id",
        "year",
        "total_students",
        "students_per_staff",
        "international_students",
        "international_student_percentage"
    ]
]


# ==========================================
# 4. FACT COUNTRY EDUCATION
# ==========================================

fact_country_education = wb_final.copy()

fact_country_education["year"] = pd.NA

fact_country_education = fact_country_education[
    [
        "Country Code",
        "Indicator Name",
        "Indicator Code"
    ]
    + [
        col for col in fact_country_education.columns
        if col.isdigit()
    ]
]

# Convert World Bank wide data into long format
year_columns = [
    col for col in fact_country_education.columns
    if col.isdigit()
]

fact_country_education = fact_country_education.melt(
    id_vars=[
        "Country Code",
        "Indicator Name",
        "Indicator Code"
    ],
    value_vars=year_columns,
    var_name="year",
    value_name="value"
)

fact_country_education.rename(
    columns={
        "Country Code": "country_code",
        "Indicator Name": "indicator",
        "Indicator Code": "indicator_code"
    },
    inplace=True
)

fact_country_education["year"] = fact_country_education["year"].astype(int)


# ==========================================
# VALIDATION
# ==========================================

print("===== FINAL FACT TABLES =====")

print("\nFACT UNIVERSITY PERFORMANCE")
print("Rows:", len(fact_university_performance))
print("Columns:", len(fact_university_performance.columns))
print("Duplicate rows:",
      fact_university_performance.duplicated().sum())

print("\nFACT RESEARCH")
print("Rows:", len(fact_research))
print("Columns:", len(fact_research.columns))
print("Duplicate rows:",
      fact_research.duplicated().sum())

print("\nFACT STUDENT")
print("Rows:", len(fact_student))
print("Columns:", len(fact_student.columns))
print("Duplicate rows:",
      fact_student.duplicated().sum())

print("\nFACT COUNTRY EDUCATION")
print("Rows:", len(fact_country_education))
print("Columns:", len(fact_country_education.columns))
print("Duplicate rows:",
      fact_country_education.duplicated().sum())

print("\nFact tables created successfully!")

===== FINAL FACT TABLES =====

FACT UNIVERSITY PERFORMANCE
Rows: 1503
Columns: 6
Duplicate rows: 0

FACT RESEARCH
Rows: 2673
Columns: 6
Duplicate rows: 0

FACT STUDENT
Rows: 2311
Columns: 6
Duplicate rows: 77

FACT COUNTRY EDUCATION
Rows: 142786
Columns: 5
Duplicate rows: 0

Fact tables created successfully!

In [ ]:
before_rows = len(fact_student)

fact_student = fact_student.drop_duplicates().reset_index(drop=True)

after_rows = len(fact_student)

print("===== FACT STUDENT DUPLICATE CLEANING =====")
print("Rows before:", before_rows)
print("Duplicate rows removed:", before_rows - after_rows)
print("Rows after:", after_rows)
print("Duplicate rows remaining:", fact_student.duplicated().sum())

===== FACT STUDENT DUPLICATE CLEANING =====
Rows before: 2311
Duplicate rows removed: 77
Rows after: 2234
Duplicate rows remaining: 0

In [ ]:
print("=" * 55)
print("       EDUVISION_DV — MILESTONE 1 FINAL VALIDATION")
print("=" * 55)

# -----------------------------------
# DIMENSION TABLES
# -----------------------------------

print("\n--- DIMENSION TABLES ---")

print(
    "dim_university:",
    len(dim_university),
    "rows | Duplicate IDs:",
    dim_university["university_id"].duplicated().sum()
)

print(
    "dim_country:",
    len(dim_country),
    "rows | Duplicate IDs:",
    dim_country["country_id"].duplicated().sum()
)

# -----------------------------------
# FACT TABLES
# -----------------------------------

print("\n--- FACT TABLES ---")

fact_tables = {
    "fact_university_performance": fact_university_performance,
    "fact_research": fact_research,
    "fact_student": fact_student,
    "fact_country_education": fact_country_education
}

for name, df in fact_tables.items():
    print(
        f"{name}: {len(df)} rows | "
        f"{len(df.columns)} columns | "
        f"Duplicate rows: {df.duplicated().sum()}"
    )

# -----------------------------------
# ID VALIDATION
# -----------------------------------

print("\n--- ID VALIDATION ---")

print(
    "University master missing University_ID:",
    university_master["university_id"].isna().sum()
)

print(
    "University master missing Country_ID:",
    university_master["country_id"].isna().sum()
)

print(
    "QS missing University_ID:",
    qs_clean["university_id"].isna().sum()
)

print(
    "THE missing University_ID:",
    the_clean["university_id"].isna().sum()
)

print(
    "WUR missing University_ID:",
    wur_clean["university_id"].isna().sum()
)

# -----------------------------------
# FINAL STATUS
# -----------------------------------

print("\n--- FINAL STATUS ---")

checks = {
    "dim_university exists": len(dim_university) > 0,
    "dim_country exists": len(dim_country) > 0,
    "University IDs unique": dim_university["university_id"].is_unique,
    "Country IDs unique": dim_country["country_id"].is_unique,
    "University performance duplicates = 0":
        fact_university_performance.duplicated().sum() == 0,
    "Research duplicates = 0":
        fact_research.duplicated().sum() == 0,
    "Student duplicates = 0":
        fact_student.duplicated().sum() == 0,
    "Country education duplicates = 0":
        fact_country_education.duplicated().sum() == 0
}

for check, result in checks.items():
    print(("PASS ✓" if result else "FAIL ✗"), "-", check)

print("\n" + "=" * 55)
print("Final validation completed.")
print("=" * 55)

=======================================================
       EDUVISION_DV — MILESTONE 1 FINAL VALIDATION
=======================================================

--- DIMENSION TABLES ---
dim_university: 3745 rows | Duplicate IDs: 0
dim_country: 241 rows | Duplicate IDs: 0

--- FACT TABLES ---
fact_university_performance: 1503 rows | 6 columns | Duplicate rows: 0
fact_research: 2673 rows | 6 columns | Duplicate rows: 0
fact_student: 2234 rows | 6 columns | Duplicate rows: 0
fact_country_education: 142786 rows | 5 columns | Duplicate rows: 0

--- ID VALIDATION ---
University master missing University_ID: 0
University master missing Country_ID: 241
QS missing University_ID: 0
THE missing University_ID: 0
WUR missing University_ID: 78

--- FINAL STATUS ---
PASS ✓ - dim_university exists
PASS ✓ - dim_country exists
PASS ✓ - University IDs unique
PASS ✓ - Country IDs unique
PASS ✓ - University performance duplicates = 0
PASS ✓ - Research duplicates = 0
PASS ✓ - Student duplicates = 0
PASS ✓ - Country education duplicates = 0

=======================================================
Final validation completed.
=======================================================

In [ ]:
print("===== EDUVISION_DV — DRIVE FILE CHECK =====")

for folder in [
    "01_Raw_Data",
    "02_Cleaned_Data",
    "03_Processed_Data",
    "04_Reports"
]:
    folder_path = os.path.join(PROJECT_PATH, folder)

    print(f"\n📁 {folder}")

    if os.path.exists(folder_path):
        files = sorted(os.listdir(folder_path))

        if files:
            for file in files:
                print("   ✓", file)
        else:
            print("   (empty)")
    else:
        print("   ⚠ Folder not found")

===== EDUVISION_DV — DRIVE FILE CHECK =====

📁 01_Raw_Data
   ✓ QS World University Rankings 2025 (Top global universities).csv
   ✓ TIMES_WorldUniversityRankings_2024.csv
   ✓ World University Rankings 2023.csv
   ✓ edstats-csv-zip-32-mb-.zip

📁 02_Cleaned_Data
   ✓ QS_2025_Cleaned.csv
   ✓ THE_2024_Cleaned.csv
   ✓ WUR_2023_Cleaned.csv
   ✓ World_Bank_Tertiary_Education_Cleaned.csv

📁 03_Processed_Data
   (empty)

📁 04_Reports
   ✓ Milestone1_Validation_Summary.csv

In [ ]:
PROCESSED_PATH = os.path.join(
    PROJECT_PATH,
    "03_Processed_Data"
)

os.makedirs(PROCESSED_PATH, exist_ok=True)

# Save dimension tables
dim_university.to_csv(
    os.path.join(PROCESSED_PATH, "dim_university.csv"),
    index=False
)

dim_country.to_csv(
    os.path.join(PROCESSED_PATH, "dim_country.csv"),
    index=False
)

# Save fact tables
fact_university_performance.to_csv(
    os.path.join(
        PROCESSED_PATH,
        "fact_university_performance.csv"
    ),
    index=False
)

fact_research.to_csv(
    os.path.join(
        PROCESSED_PATH,
        "fact_research.csv"
    ),
    index=False
)

fact_student.to_csv(
    os.path.join(
        PROCESSED_PATH,
        "fact_student.csv"
    ),
    index=False
)

fact_country_education.to_csv(
    os.path.join(
        PROCESSED_PATH,
        "fact_country_education.csv"
    ),
    index=False
)

print("===== FINAL DATA MODEL SAVED =====")

for file in sorted(os.listdir(PROCESSED_PATH)):
    print("✓", file)

print("\nLocation:")
print(PROCESSED_PATH)

===== FINAL DATA MODEL SAVED =====
✓ dim_country.csv
✓ dim_university.csv
✓ fact_country_education.csv
✓ fact_research.csv
✓ fact_student.csv
✓ fact_university_performance.csv

Location:
/content/drive/MyDrive/EduVision_DV/03_Processed_Data

In [ ]:
kpi_mapping = pd.DataFrame({
    "KPI_ID": [
        "KPI_1",
        "KPI_2",
        "KPI_3",
        "KPI_4",
        "KPI_5",
        "KPI_6"
    ],

    "KPI_Name": [
        "Global Ranking Score",
        "Research Impact Score",
        "Faculty-to-Student Ratio",
        "International Student Percentage",
        "Academic Reputation Score",
        "Research Productivity Index"
    ],

    "Source_Dataset": [
        "QS 2025",
        "QS 2025",
        "WUR 2023",
        "WUR 2023",
        "QS 2025",
        "THE 2024 + supporting research indicators"
    ],

    "Source_Field": [
        "Overall_Score",
        "Citations_per_Faculty_Score",
        "No of student per staff",
        "International Student",
        "Academic_Reputation_Score",
        "Research Score + Citation Score + research-related indicator(s)"
    ],

    "KPI_Type": [
        "Direct",
        "Direct",
        "Direct",
        "Direct",
        "Direct",
        "Derived"
    ],

    "Unit": [
        "Score",
        "Score",
        "Students per staff",
        "Percentage",
        "Score",
        "Index"
    ],

    "Formula_Status": [
        "Source value",
        "Source value",
        "Source value",
        "Source value",
        "Source value",
        "Requires documented formula and approved weights"
    ]
})

print("===== EDUVISION_DV — KPI MAPPING =====")
print(kpi_mapping.to_string(index=False))

===== EDUVISION_DV — KPI MAPPING =====
KPI_ID                         KPI_Name                            Source_Dataset                                                    Source_Field KPI_Type               Unit                                   Formula_Status
 KPI_1             Global Ranking Score                                   QS 2025                                                   Overall_Score   Direct              Score                                     Source value
 KPI_2            Research Impact Score                                   QS 2025                                     Citations_per_Faculty_Score   Direct              Score                                     Source value
 KPI_3         Faculty-to-Student Ratio                                  WUR 2023                                         No of student per staff   Direct Students per staff                                     Source value
 KPI_4 International Student Percentage                                  WUR 2023                                           International Student   Direct         Percentage                                     Source value
 KPI_5        Academic Reputation Score                                   QS 2025                                       Academic_Reputation_Score   Direct              Score                                     Source value
 KPI_6      Research Productivity Index THE 2024 + supporting research indicators Research Score + Citation Score + research-related indicator(s)  Derived              Index Requires documented formula and approved weights

In [ ]:
import pandas as pd
import os

# Project paths
PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"
CLEANED_PATH = os.path.join(PROJECT_PATH, "02_Cleaned_Data")

# Load the cleaned datasets
qs_clean = pd.read_csv(
    os.path.join(CLEANED_PATH, "QS_2025_Cleaned.csv")
)

wur_clean = pd.read_csv(
    os.path.join(CLEANED_PATH, "WUR_2023_Cleaned.csv")
)

print("===== MILESTONE 2 DATA RESTORED =====")
print("QS 2025:", qs_clean.shape)
print("WUR 2023:", wur_clean.shape)

print("\nRequired KPI source columns:")
print("QS Overall Score:",
      "Overall_Score" in qs_clean.columns)
print("QS Citations per Faculty:",
      "Citations_per_Faculty_Score" in qs_clean.columns)
print("QS Academic Reputation:",
      "Academic_Reputation_Score" in qs_clean.columns)
print("WUR Students per Staff:",
      "No of student per staff" in wur_clean.columns)
print("WUR International Student:",
      "International Student" in wur_clean.columns)

print("\nData restoration successful.")

===== MILESTONE 2 DATA RESTORED =====
QS 2025: (1503, 28)
WUR 2023: (2311, 13)

Required KPI source columns:
QS Overall Score: True
QS Citations per Faculty: True
QS Academic Reputation: True
WUR Students per Staff: True
WUR International Student: True

Data restoration successful.

In [ ]:
# QS provides KPI 1, 2 and 5
kpi_dataset = qs_clean[
    [
        "Institution_Name",
        "Overall_Score",
        "Citations_per_Faculty_Score",
        "Academic_Reputation_Score"
    ]
].copy()

# WUR provides KPI 3 and 4
wur_kpi = wur_clean[
    [
        "Name of University",
        "No of student per staff",
        "International Student"
    ]
].copy()

# Match WUR values to QS universities using cleaned names
kpi_dataset["university_name_std"] = (
    kpi_dataset["Institution_Name"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w\s]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
)

wur_kpi["university_name_std"] = (
    wur_kpi["Name of University"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w\s]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
)

wur_kpi = wur_kpi.drop_duplicates("university_name_std")

kpi_dataset = kpi_dataset.merge(
    wur_kpi[
        [
            "university_name_std",
            "No of student per staff",
            "International Student"
        ]
    ],
    on="university_name_std",
    how="left"
)

# Rename to final KPI names
kpi_dataset.rename(
    columns={
        "Overall_Score": "global_ranking_score",
        "Citations_per_Faculty_Score": "research_impact_score",
        "No of student per staff": "faculty_to_student_ratio",
        "International Student": "international_student_percentage",
        "Academic_Reputation_Score": "academic_reputation_score"
    },
    inplace=True
)

# KPI 6 — pending approved formula
kpi_dataset["research_productivity_index"] = pd.NA

# Keep final KPI columns
kpi_dataset = kpi_dataset[
    [
        "Institution_Name",
        "global_ranking_score",
        "research_impact_score",
        "faculty_to_student_ratio",
        "international_student_percentage",
        "academic_reputation_score",
        "research_productivity_index"
    ]
]

print("===== KPI DATASET CREATED =====")
print("Rows:", len(kpi_dataset))
print("Columns:", len(kpi_dataset.columns))

print("\nKPI columns:")
print(kpi_dataset.columns.tolist())

print("\nSample:")
print(kpi_dataset.head(5).to_string(index=False))

===== KPI DATASET CREATED =====
Rows: 1503
Columns: 7

KPI columns:
['Institution_Name', 'global_ranking_score', 'research_impact_score', 'faculty_to_student_ratio', 'international_student_percentage', 'academic_reputation_score', 'research_productivity_index']

Sample:
                           Institution_Name  global_ranking_score  research_impact_score  faculty_to_student_ratio  international_student_percentage  academic_reputation_score research_productivity_index
Massachusetts Institute of Technology (MIT)                 100.0                  100.0                       NaN                               NaN                      100.0                        <NA>
                    Imperial College London                  98.5                   93.9                      11.2                              61.0                       98.5                        <NA>
                       University of Oxford                  96.9                   84.8                      10.6                              42.0                      100.0                        <NA>
                         Harvard University                  96.8                  100.0                       9.6                              25.0                      100.0                        <NA>
                    University of Cambridge                  96.7                   84.6                      11.3                              39.0                      100.0                        <NA>

In [ ]:
import os
import pandas as pd

PROCESSED_PATH = os.path.join(
    PROJECT_PATH,
    "03_Processed_Data"
)

# Load the final University dimension
dim_university = pd.read_csv(
    os.path.join(PROCESSED_PATH, "dim_university.csv")
)

# Load the final fact tables
performance = pd.read_csv(
    os.path.join(PROCESSED_PATH, "fact_university_performance.csv")
)

student = pd.read_csv(
    os.path.join(PROCESSED_PATH, "fact_student.csv")
)

# Keep one student record per University_ID
student_kpi = student.drop_duplicates("university_id")[
    [
        "university_id",
        "students_per_staff",
        "international_student_percentage"
    ]
]

# Build KPI dataset from University_ID
kpi_dataset = performance[
    [
        "university_id",
        "overall_score",
        "academic_reputation",
        "employer_reputation"
    ]
].copy()

# Add university information
kpi_dataset = kpi_dataset.merge(
    dim_university[
        [
            "university_id",
            "university_name",
            "country_id",
            "country_name",
            "region"
        ]
    ],
    on="university_id",
    how="left"
)

# Add student KPIs
kpi_dataset = kpi_dataset.merge(
    student_kpi,
    on="university_id",
    how="left"
)

# Add Research Impact directly from QS
kpi_dataset = kpi_dataset.merge(
    qs_clean[
        [
            "Institution_Name",
            "Citations_per_Faculty_Score"
        ]
    ],
    left_on="university_name",
    right_on="Institution_Name",
    how="left"
)

kpi_dataset.rename(
    columns={
        "overall_score": "global_ranking_score",
        "academic_reputation": "academic_reputation_score",
        "students_per_staff": "faculty_to_student_ratio",
        "international_student_percentage":
            "international_student_percentage",
        "Citations_per_Faculty_Score":
            "research_impact_score"
    },
    inplace=True
)

# KPI 6 remains pending formula approval
kpi_dataset["research_productivity_index"] = pd.NA

# Final KPI columns
kpi_dataset = kpi_dataset[
    [
        "university_id",
        "university_name",
        "country_id",
        "country_name",
        "region",
        "global_ranking_score",
        "research_impact_score",
        "faculty_to_student_ratio",
        "international_student_percentage",
        "academic_reputation_score",
        "research_productivity_index"
    ]
]

print("===== KPI DATASET — UNIVERSITY ID VERSION =====")
print("Rows:", len(kpi_dataset))
print("Columns:", len(kpi_dataset.columns))
print("Unique University IDs:",
      kpi_dataset["university_id"].nunique())
print("Duplicate rows:", kpi_dataset.duplicated().sum())
print("\nSample:")
print(kpi_dataset.head().to_string(index=False))

===== KPI DATASET — UNIVERSITY ID VERSION =====
Rows: 1503
Columns: 11
Unique University IDs: 1503
Duplicate rows: 0

Sample:
university_id                           university_name country_id   country_name                region  global_ranking_score  research_impact_score  faculty_to_student_ratio  international_student_percentage  academic_reputation_score research_productivity_index
       U01330 massachusetts institute of technology mit       C228  United States         North America                 100.0                    NaN                       NaN                               NaN                      100.0                        <NA>
       U00871                   imperial college london       C076 United Kingdom Europe & Central Asia                  98.5                    NaN                      11.2                              61.0                       98.5                        <NA>
       U03171                      university of oxford       C076 United Kingdom Europe & Central Asia                  96.9                    NaN                      10.6                              42.0                      100.0                        <NA>
       U00790                        harvard university       C228  United States         North America                  96.8                    NaN                       9.6                              25.0                      100.0                        <NA>
       U02820                   university of cambridge       C076 United Kingdom Europe & Central Asia                  96.7                    NaN                      11.3                              39.0                      100.0                        <NA>

In [ ]:
# Use the already-created Milestone 1 performance table
performance_kpi = performance[
    ["university_id", "overall_score"]
].copy()

# Convert Overall Score to numeric
performance_kpi["overall_score"] = pd.to_numeric(
    performance_kpi["overall_score"],
    errors="coerce"
)

# Add KPI 1 to the KPI dataset
kpi_dataset = kpi_dataset.drop(
    columns=["global_ranking_score"],
    errors="ignore"
)

kpi_dataset = kpi_dataset.merge(
    performance_kpi,
    on="university_id",
    how="left"
)

kpi_dataset.rename(
    columns={
        "overall_score": "global_ranking_score"
    },
    inplace=True
)

print("===== KPI 1: GLOBAL RANKING SCORE =====")
print("Total universities:", len(kpi_dataset))
print(
    "Available values:",
    kpi_dataset["global_ranking_score"].notna().sum()
)
print(
    "Missing values:",
    kpi_dataset["global_ranking_score"].isna().sum()
)

print("\nSample:")
print(
    kpi_dataset[
        ["university_id", "university_name", "global_ranking_score"]
    ].head(5).to_string(index=False)
)

===== KPI 1: GLOBAL RANKING SCORE =====
Total universities: 1503
Available values: 600
Missing values: 903

Sample:
university_id                           university_name  global_ranking_score
       U01330 massachusetts institute of technology mit                 100.0
       U00871                   imperial college london                  98.5
       U03171                      university of oxford                  96.9
       U00790                        harvard university                  96.8
       U02820                   university of cambridge                  96.7

In [ ]:
qs_kpi2 = qs_clean[
    ["Institution_Name", "Citations_per_Faculty_Score"]
].copy()

# Standardize names directly
qs_kpi2["university_name"] = (
    qs_kpi2["Institution_Name"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w\s]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
)

qs_kpi2 = qs_kpi2.drop_duplicates("university_name")

# Remove old column if it exists
kpi_dataset = kpi_dataset.drop(
    columns=["research_impact_score"],
    errors="ignore"
)

# Match QS score to existing University IDs
qs_id_score = dim_university[
    ["university_id", "university_name"]
].merge(
    qs_kpi2[
        ["university_name", "Citations_per_Faculty_Score"]
    ],
    on="university_name",
    how="left"
)

kpi_dataset = kpi_dataset.merge(
    qs_id_score[
        ["university_id", "Citations_per_Faculty_Score"]
    ],
    on="university_id",
    how="left"
)

kpi_dataset.rename(
    columns={
        "Citations_per_Faculty_Score":
            "research_impact_score"
    },
    inplace=True
)

print("===== KPI 2: RESEARCH IMPACT SCORE =====")
print(
    "Available values:",
    kpi_dataset["research_impact_score"].notna().sum()
)
print(
    "Missing values:",
    kpi_dataset["research_impact_score"].isna().sum()
)

print("\nSample:")
print(
    kpi_dataset[
        [
            "university_id",
            "university_name",
            "research_impact_score"
        ]
    ].head(5).to_string(index=False)
)

===== KPI 2: RESEARCH IMPACT SCORE =====
Available values: 1297
Missing values: 206

Sample:
university_id                           university_name  research_impact_score
       U01330 massachusetts institute of technology mit                  100.0
       U00871                   imperial college london                   93.9
       U03171                      university of oxford                   84.8
       U00790                        harvard university                  100.0
       U02820                   university of cambridge                   84.6

In [ ]:
import os
import pandas as pd

# Project paths
PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"
PROCESSED_PATH = os.path.join(PROJECT_PATH, "03_Processed_Data")

# Load saved Milestone 1 tables
dim_university = pd.read_csv(
    os.path.join(PROCESSED_PATH, "dim_university.csv")
)

fact_student = pd.read_csv(
    os.path.join(PROCESSED_PATH, "fact_student.csv")
)

# Select required KPI field
student_kpi3 = fact_student[
    ["university_id", "students_per_staff"]
].copy()

# Remove exact duplicate records
student_kpi3 = student_kpi3.drop_duplicates()

# Start KPI dataset from university master
kpi_dataset = dim_university[
    ["university_id", "university_name"]
].copy()

# Add KPI 3
kpi_dataset = kpi_dataset.merge(
    student_kpi3,
    on="university_id",
    how="left"
)

# Rename field according to KPI definition
kpi_dataset.rename(
    columns={
        "students_per_staff": "faculty_to_student_ratio"
    },
    inplace=True
)

print("===== KPI 3: FACULTY-TO-STUDENT RATIO =====")
print("Total universities:", len(kpi_dataset))
print(
    "Available values:",
    kpi_dataset["faculty_to_student_ratio"].notna().sum()
)
print(
    "Missing values:",
    kpi_dataset["faculty_to_student_ratio"].isna().sum()
)

print("\nSample:")
print(
    kpi_dataset[
        [
            "university_id",
            "university_name",
            "faculty_to_student_ratio"
        ]
    ].head(5).to_string(index=False)
)

===== KPI 3: FACULTY-TO-STUDENT RATIO =====
Total universities: 3745
Available values: 2208
Missing values: 1537

Sample:
university_id                             university_name  faculty_to_student_ratio
       U00001                          aalborg university                      14.7
       U00002                            aalto university                      19.7
       U00003                           aarhus university                      13.5
       U00004 abai kazakh national pedagogical university                       NaN
       U00005      abbes laghrour university of khenchala                       NaN

In [ ]:
import os
import pandas as pd

# Project paths
PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"
PROCESSED_PATH = os.path.join(PROJECT_PATH, "03_Processed_Data")

# Load saved Milestone 1 table
dim_university = pd.read_csv(
    os.path.join(PROCESSED_PATH, "dim_university.csv")
)

fact_student = pd.read_csv(
    os.path.join(PROCESSED_PATH, "fact_student.csv")
)

# Select required KPI field
student_kpi4 = fact_student[
    ["university_id", "international_student_percentage"]
].copy()

student_kpi4 = student_kpi4.drop_duplicates()

# Start KPI dataset from University Master
kpi_dataset = dim_university[
    ["university_id", "university_name"]
].copy()

# Add KPI 4
kpi_dataset = kpi_dataset.merge(
    student_kpi4,
    on="university_id",
    how="left"
)

print("===== KPI 4: INTERNATIONAL STUDENT PERCENTAGE =====")
print("Total universities:", len(kpi_dataset))
print(
    "Available values:",
    kpi_dataset[
        "international_student_percentage"
    ].notna().sum()
)
print(
    "Missing values:",
    kpi_dataset[
        "international_student_percentage"
    ].isna().sum()
)

print("\nSample:")
print(
    kpi_dataset[
        [
            "university_id",
            "university_name",
            "international_student_percentage"
        ]
    ].head(5).to_string(index=False)
)

===== KPI 4: INTERNATIONAL STUDENT PERCENTAGE =====
Total universities: 3745
Available values: 2206
Missing values: 1539

Sample:
university_id                             university_name  international_student_percentage
       U00001                          aalborg university                              14.0
       U00002                            aalto university                              21.0
       U00003                           aarhus university                              10.0
       U00004 abai kazakh national pedagogical university                               NaN
       U00005      abbes laghrour university of khenchala                               NaN

In [ ]:
import os
import pandas as pd

# Project paths
PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"
CLEANED_PATH = os.path.join(PROJECT_PATH, "02_Cleaned_Data")
PROCESSED_PATH = os.path.join(PROJECT_PATH, "03_Processed_Data")

# Load saved Milestone 1 tables
dim_university = pd.read_csv(
    os.path.join(PROCESSED_PATH, "dim_university.csv")
)

qs_clean = pd.read_csv(
    os.path.join(CLEANED_PATH, "QS_2025_Cleaned.csv"),
    encoding="latin1"
)

# Standardize QS university names
qs_kpi5 = qs_clean[
    ["Institution_Name", "Academic_Reputation_Score"]
].copy()

qs_kpi5["university_name"] = (
    qs_kpi5["Institution_Name"]
    .astype("string")
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w\s]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
)

qs_kpi5 = qs_kpi5.drop_duplicates("university_name")

# Match with existing University IDs
kpi5 = dim_university[
    ["university_id", "university_name"]
].merge(
    qs_kpi5[
        ["university_name", "Academic_Reputation_Score"]
    ],
    on="university_name",
    how="left"
)

kpi5.rename(
    columns={
        "Academic_Reputation_Score":
            "academic_reputation_score"
    },
    inplace=True
)

print("===== KPI 5: ACADEMIC REPUTATION SCORE =====")
print("Total universities:", len(kpi5))
print(
    "Available values:",
    kpi5["academic_reputation_score"].notna().sum()
)
print(
    "Missing values:",
    kpi5["academic_reputation_score"].isna().sum()
)

print("\nSample:")
print(
    kpi5[
        [
            "university_id",
            "university_name",
            "academic_reputation_score"
        ]
    ].head(5).to_string(index=False)
)

===== KPI 5: ACADEMIC REPUTATION SCORE =====
Total universities: 3745
Available values: 1453
Missing values: 2292

Sample:
university_id                             university_name  academic_reputation_score
       U00001                          aalborg university                       19.9
       U00002                            aalto university                       45.7
       U00003                           aarhus university                       54.7
       U00004 abai kazakh national pedagogical university                       26.5
       U00005      abbes laghrour university of khenchala                        NaN

In [ ]:
import pandas as pd
import os
import re

PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"
CLEANED_PATH = os.path.join(PROJECT_PATH, "02_Cleaned_Data")
PROCESSED_PATH = os.path.join(PROJECT_PATH, "03_Processed_Data")

# Load required files
dim_university = pd.read_csv(
    os.path.join(PROCESSED_PATH, "dim_university.csv")
)

the = pd.read_csv(
    os.path.join(CLEANED_PATH, "THE_2024_Cleaned.csv")
)

# Standardize university names for matching
def standardize_name(series):
    return (
        series.astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"[^\w\s]", "", regex=True)
        .str.replace(r"\s+", " ", regex=True)
    )

dim_university["name_std"] = standardize_name(
    dim_university["university_name"]
)

the["name_std"] = standardize_name(
    the["name"]
)

# Convert KPI source fields to numeric
the["scores_research"] = pd.to_numeric(
    the["scores_research"], errors="coerce"
)

the["scores_citations"] = pd.to_numeric(
    the["scores_citations"], errors="coerce"
)

the["scores_international_outlook"] = pd.to_numeric(
    the["scores_international_outlook"], errors="coerce"
)

# Keep one record per standardized university name
the_kpi6 = the[
    [
        "name_std",
        "scores_research",
        "scores_citations",
        "scores_international_outlook"
    ]
].drop_duplicates(subset=["name_std"])

# Merge with university master
kpi6 = dim_university[
    ["university_id", "university_name", "country_id", "country_name", "region", "name_std"]
].merge(
    the_kpi6,
    on="name_std",
    how="left"
)

# Calculate Research Productivity Index
# Formula approved by the team:
# 50% Research + 30% Citations + 20% International Outlook

kpi6["research_productivity_index"] = (
    0.50 * kpi6["scores_research"]
    + 0.30 * kpi6["scores_citations"]
    + 0.20 * kpi6["scores_international_outlook"]
)

# Keep required columns
kpi6 = kpi6[
    [
        "university_id",
        "research_productivity_index"
    ]
]

# Validation
print("KPI 6 corrected successfully!")
print("Total universities:", len(kpi6))
print(
    "Available KPI 6:",
    kpi6["research_productivity_index"].notna().sum()
)
print(
    "Missing KPI 6:",
    kpi6["research_productivity_index"].isna().sum()
)

print("\nSample:")
print(kpi6.head(10))

KPI 6 corrected successfully!
Total universities: 3745
Available KPI 6: 2128
Missing KPI 6: 1617

Sample:
  university_id  research_productivity_index
0        U00001                        61.88
1        U00002                        61.82
2        U00003                        70.65
3        U00004                          NaN
4        U00005                          NaN
5        U00006                          NaN
6        U00007                          NaN
7        U00008                        19.76
8        U00009                        40.22
9        U00010                          NaN

In [ ]:
import os
import pandas as pd
import numpy as np

# ============================================================
# PATHS
# ============================================================

PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"
CLEANED_PATH = os.path.join(PROJECT_PATH, "02_Cleaned_Data")
PROCESSED_PATH = os.path.join(PROJECT_PATH, "03_Processed_Data")

# ============================================================
# LOAD SAVED DATA
# ============================================================

dim_university = pd.read_csv(
    os.path.join(PROCESSED_PATH, "dim_university.csv")
)

performance = pd.read_csv(
    os.path.join(PROCESSED_PATH, "fact_university_performance.csv")
)

student = pd.read_csv(
    os.path.join(PROCESSED_PATH, "fact_student.csv")
)

qs = pd.read_csv(
    os.path.join(CLEANED_PATH, "QS_2025_Cleaned.csv")
)

the = pd.read_csv(
    os.path.join(CLEANED_PATH, "THE_2024_Cleaned.csv")
)

# ============================================================
# BASE DATASET
# ============================================================

final_df = dim_university[
    [
        "university_id",
        "university_name",
        "country_id",
        "country_name",
        "region"
    ]
].copy()

# ============================================================
# KPI 1 + KPI 5
# QS 2025
# ============================================================

performance_kpi = performance[
    [
        "university_id",
        "overall_score",
        "academic_reputation"
    ]
].copy()

performance_kpi["overall_score"] = pd.to_numeric(
    performance_kpi["overall_score"],
    errors="coerce"
)

performance_kpi["academic_reputation"] = pd.to_numeric(
    performance_kpi["academic_reputation"],
    errors="coerce"
)

performance_kpi = performance_kpi.drop_duplicates(
    "university_id"
)

final_df = final_df.merge(
    performance_kpi,
    on="university_id",
    how="left"
)

final_df.rename(
    columns={
        "overall_score": "global_ranking_score",
        "academic_reputation": "academic_reputation_score"
    },
    inplace=True
)

# ============================================================
# KPI 2
# QS Citations per Faculty
# ============================================================

def standardize_name(series):
    return (
        series.astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"[^\w\s]", "", regex=True)
        .str.replace(r"\s+", " ", regex=True)
    )

dim_match = dim_university[
    ["university_id", "university_name"]
].copy()

dim_match["name_std"] = standardize_name(
    dim_match["university_name"]
)

qs["name_std"] = standardize_name(
    qs["Institution_Name"]
)

qs_kpi2 = qs[
    [
        "name_std",
        "Citations_per_Faculty_Score"
    ]
].copy()

qs_kpi2["Citations_per_Faculty_Score"] = pd.to_numeric(
    qs_kpi2["Citations_per_Faculty_Score"],
    errors="coerce"
)

qs_kpi2 = qs_kpi2.drop_duplicates("name_std")

qs_kpi2 = dim_match.merge(
    qs_kpi2,
    on="name_std",
    how="left"
)

qs_kpi2 = qs_kpi2[
    [
        "university_id",
        "Citations_per_Faculty_Score"
    ]
]

final_df = final_df.merge(
    qs_kpi2,
    on="university_id",
    how="left"
)

final_df.rename(
    columns={
        "Citations_per_Faculty_Score": "research_impact_score"
    },
    inplace=True
)

# ============================================================
# KPI 3 + KPI 4
# WUR 2023
# ============================================================

student_kpi = student[
    [
        "university_id",
        "students_per_staff",
        "international_student_percentage"
    ]
].copy()

student_kpi["students_per_staff"] = pd.to_numeric(
    student_kpi["students_per_staff"],
    errors="coerce"
)

student_kpi["international_student_percentage"] = pd.to_numeric(
    student_kpi["international_student_percentage"],
    errors="coerce"
)

student_kpi = student_kpi.drop_duplicates(
    "university_id"
)

final_df = final_df.merge(
    student_kpi,
    on="university_id",
    how="left"
)

final_df.rename(
    columns={
        "students_per_staff": "faculty_to_student_ratio"
    },
    inplace=True
)

# ============================================================
# KPI 6
# THE 2024
# 50% Research + 30% Citations + 20% International Outlook
# ============================================================

the["name_std"] = standardize_name(
    the["name"]
)

the_kpi6 = the[
    [
        "name_std",
        "scores_research",
        "scores_citations",
        "scores_international_outlook"
    ]
].copy()

for column in [
    "scores_research",
    "scores_citations",
    "scores_international_outlook"
]:
    the_kpi6[column] = pd.to_numeric(
        the_kpi6[column],
        errors="coerce"
    )

the_kpi6 = the_kpi6.drop_duplicates(
    "name_std"
)

the_kpi6 = dim_match.merge(
    the_kpi6,
    on="name_std",
    how="left"
)

the_kpi6["research_productivity_index"] = (
    0.50 * the_kpi6["scores_research"]
    + 0.30 * the_kpi6["scores_citations"]
    + 0.20 * the_kpi6["scores_international_outlook"]
)

kpi6_final = the_kpi6[
    [
        "university_id",
        "research_productivity_index"
    ]
]

final_df = final_df.merge(
    kpi6_final,
    on="university_id",
    how="left"
)

# ============================================================
# SOURCE + YEAR INFORMATION
# ============================================================

final_df["overview_year"] = 2025
final_df["research_year"] = 2024
final_df["student_year"] = 2023

final_df["global_ranking_score_source"] = "QS 2025 Overall Score"
final_df["research_impact_score_source"] = (
    "QS 2025 Citations per Faculty Score"
)
final_df["faculty_to_student_ratio_source"] = (
    "WUR 2023 Students per Staff"
)
final_df["international_student_percentage_source"] = (
    "WUR 2023 International Student Percentage"
)
final_df["academic_reputation_score_source"] = (
    "QS 2025 Academic Reputation Score"
)
final_df["research_productivity_index_source"] = (
    "THE 2024: 50% Research + 30% Citations + 20% International Outlook"
)

# ============================================================
# ROUND KPI VALUES
# ============================================================

kpi_columns = [
    "global_ranking_score",
    "research_impact_score",
    "faculty_to_student_ratio",
    "international_student_percentage",
    "academic_reputation_score",
    "research_productivity_index"
]

for column in kpi_columns:
    final_df[column] = pd.to_numeric(
        final_df[column],
        errors="coerce"
    ).round(2)

# ============================================================
# REMOVE INVALID INFINITE VALUES
# ============================================================

final_df = final_df.replace(
    [np.inf, -np.inf],
    np.nan
)

# ============================================================
# FINAL COLUMN ORDER
# ============================================================

final_df = final_df[
    [
        "university_id",
        "university_name",
        "country_id",
        "country_name",
        "region",

        "overview_year",
        "research_year",
        "student_year",

        "global_ranking_score",
        "global_ranking_score_source",

        "research_impact_score",
        "research_impact_score_source",

        "faculty_to_student_ratio",
        "faculty_to_student_ratio_source",

        "international_student_percentage",
        "international_student_percentage_source",

        "academic_reputation_score",
        "academic_reputation_score_source",

        "research_productivity_index",
        "research_productivity_index_source"
    ]
]

# ============================================================
# VALIDATION
# ============================================================

print("===== FINAL EDUCATION KPI DATASET =====")
print("Total universities:", len(final_df))
print("Total columns:", len(final_df.columns))
print("Duplicate University IDs:",
      final_df["university_id"].duplicated().sum())

print("\nKPI availability:")

for column in kpi_columns:
    print(
        column, ":",
        final_df[column].notna().sum(),
        "available /",
        final_df[column].isna().sum(),
        "missing"
    )

# ============================================================
# SAVE TO EXCEL
# ============================================================

output_file = os.path.join(
    PROCESSED_PATH,
    "university_final_dataset.xlsx"
)

final_df.to_excel(
    output_file,
    index=False
)

print("\nSaved successfully:")
print(output_file)

print("\nSample:")
print(final_df.head(5).to_string(index=False))

===== FINAL EDUCATION KPI DATASET =====
Total universities: 3745
Total columns: 20
Duplicate University IDs: 0

KPI availability:
global_ranking_score : 600 available / 3145 missing
research_impact_score : 1661 available / 2084 missing
faculty_to_student_ratio : 2208 available / 1537 missing
international_student_percentage : 2206 available / 1539 missing
academic_reputation_score : 1503 available / 2242 missing
research_productivity_index : 2128 available / 1617 missing

Saved successfully:
/content/drive/MyDrive/EduVision_DV/03_Processed_Data/university_final_dataset.xlsx

Sample:
university_id                             university_name country_id country_name                     region  overview_year  research_year  student_year  global_ranking_score global_ranking_score_source  research_impact_score        research_impact_score_source  faculty_to_student_ratio faculty_to_student_ratio_source  international_student_percentage   international_student_percentage_source  academic_reputation_score  academic_reputation_score_source  research_productivity_index                                 research_productivity_index_source
       U00001                          aalborg university       C055      Denmark      Europe & Central Asia           2025           2024          2023                  35.7       QS 2025 Overall Score                   53.2 QS 2025 Citations per Faculty Score                      14.7     WUR 2023 Students per Staff                              14.0 WUR 2023 International Student Percentage                       19.9 QS 2025 Academic Reputation Score                        61.88 THE 2024: 50% Research + 30% Citations + 20% International Outlook
       U00002                            aalto university       C070      Finland      Europe & Central Asia           2025           2024          2023                  57.9       QS 2025 Overall Score                   73.6 QS 2025 Citations per Faculty Score                      19.7     WUR 2023 Students per Staff                              21.0 WUR 2023 International Student Percentage                       45.7 QS 2025 Academic Reputation Score                        61.82 THE 2024: 50% Research + 30% Citations + 20% International Outlook
       U00003                           aarhus university       C055      Denmark      Europe & Central Asia           2025           2024          2023                  53.3       QS 2025 Overall Score                   63.8 QS 2025 Citations per Faculty Score                      13.5     WUR 2023 Students per Staff                              10.0 WUR 2023 International Student Percentage                       54.7 QS 2025 Academic Reputation Score                        70.65 THE 2024: 50% Research + 30% Citations + 20% International Outlook
       U00004 abai kazakh national pedagogical university       C109   Kazakhstan      Europe & Central Asia           2025           2024          2023                   NaN       QS 2025 Overall Score                    1.1 QS 2025 Citations per Faculty Score                       NaN     WUR 2023 Students per Staff                               NaN WUR 2023 International Student Percentage                       26.5 QS 2025 Academic Reputation Score                          NaN THE 2024: 50% Research + 30% Citations + 20% International Outlook
       U00005      abbes laghrour university of khenchala       C057      Algeria Middle East & North Africa           2025           2024          2023                   NaN       QS 2025 Overall Score                    NaN QS 2025 Citations per Faculty Score                       NaN     WUR 2023 Students per Staff                               NaN WUR 2023 International Student Percentage                        NaN QS 2025 Academic Reputation Score                          NaN THE 2024: 50% Research + 30% Citations + 20% International Outlook

In [ ]:
import os

PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"
PROCESSED_PATH = os.path.join(PROJECT_PATH, "03_Processed_Data")

script = r'''
import os
import pandas as pd
import numpy as np

PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"
CLEANED_PATH = os.path.join(PROJECT_PATH, "02_Cleaned_Data")
PROCESSED_PATH = os.path.join(PROJECT_PATH, "03_Processed_Data")

# Load Milestone 1 data
dim_university = pd.read_csv(
    os.path.join(PROCESSED_PATH, "dim_university.csv")
)

performance = pd.read_csv(
    os.path.join(PROCESSED_PATH, "fact_university_performance.csv")
)

student = pd.read_csv(
    os.path.join(PROCESSED_PATH, "fact_student.csv")
)

qs = pd.read_csv(
    os.path.join(CLEANED_PATH, "QS_2025_Cleaned.csv")
)

the = pd.read_csv(
    os.path.join(CLEANED_PATH, "THE_2024_Cleaned.csv")
)

# Base university dataset
final_df = dim_university[
    [
        "university_id",
        "university_name",
        "country_id",
        "country_name",
        "region"
    ]
].copy()

# ------------------------------------------------------------
# KPI 1: Global Ranking Score
# Source: QS 2025 Overall Score
# ------------------------------------------------------------

performance_kpi = performance[
    [
        "university_id",
        "overall_score",
        "academic_reputation"
    ]
].copy()

performance_kpi["overall_score"] = pd.to_numeric(
    performance_kpi["overall_score"],
    errors="coerce"
)

performance_kpi["academic_reputation"] = pd.to_numeric(
    performance_kpi["academic_reputation"],
    errors="coerce"
)

performance_kpi = performance_kpi.drop_duplicates("university_id")

final_df = final_df.merge(
    performance_kpi,
    on="university_id",
    how="left"
)

final_df.rename(
    columns={
        "overall_score": "global_ranking_score",
        "academic_reputation": "academic_reputation_score"
    },
    inplace=True
)

# ------------------------------------------------------------
# Standardize names for QS and THE matching
# ------------------------------------------------------------

def standardize_name(series):
    return (
        series.astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"[^\w\s]", "", regex=True)
        .str.replace(r"\s+", " ", regex=True)
    )

dim_match = dim_university[
    ["university_id", "university_name"]
].copy()

dim_match["name_std"] = standardize_name(
    dim_match["university_name"]
)

# ------------------------------------------------------------
# KPI 2: Research Impact Score
# Source: QS 2025 Citations per Faculty Score
# ------------------------------------------------------------

qs["name_std"] = standardize_name(qs["Institution_Name"])

qs_kpi2 = qs[
    [
        "name_std",
        "Citations_per_Faculty_Score"
    ]
].copy()

qs_kpi2["Citations_per_Faculty_Score"] = pd.to_numeric(
    qs_kpi2["Citations_per_Faculty_Score"],
    errors="coerce"
)

qs_kpi2 = qs_kpi2.drop_duplicates("name_std")

qs_kpi2 = dim_match.merge(
    qs_kpi2,
    on="name_std",
    how="left"
)

final_df = final_df.merge(
    qs_kpi2[
        [
            "university_id",
            "Citations_per_Faculty_Score"
        ]
    ],
    on="university_id",
    how="left"
)

final_df.rename(
    columns={
        "Citations_per_Faculty_Score":
        "research_impact_score"
    },
    inplace=True
)

# ------------------------------------------------------------
# KPI 3 + KPI 4
# Source: WUR 2023
# ------------------------------------------------------------

student_kpi = student[
    [
        "university_id",
        "students_per_staff",
        "international_student_percentage"
    ]
].copy()

student_kpi["students_per_staff"] = pd.to_numeric(
    student_kpi["students_per_staff"],
    errors="coerce"
)

student_kpi["international_student_percentage"] = pd.to_numeric(
    student_kpi["international_student_percentage"],
    errors="coerce"
)

student_kpi = student_kpi.drop_duplicates("university_id")

final_df = final_df.merge(
    student_kpi,
    on="university_id",
    how="left"
)

final_df.rename(
    columns={
        "students_per_staff":
        "faculty_to_student_ratio"
    },
    inplace=True
)

# ------------------------------------------------------------
# KPI 6: Research Productivity Index
# Source: THE 2024
#
# Formula:
# 50% Research Score
# + 30% Citations Score
# + 20% International Outlook Score
# ------------------------------------------------------------

the["name_std"] = standardize_name(the["name"])

the_kpi6 = the[
    [
        "name_std",
        "scores_research",
        "scores_citations",
        "scores_international_outlook"
    ]
].copy()

for column in [
    "scores_research",
    "scores_citations",
    "scores_international_outlook"
]:
    the_kpi6[column] = pd.to_numeric(
        the_kpi6[column],
        errors="coerce"
    )

the_kpi6 = the_kpi6.drop_duplicates("name_std")

the_kpi6 = dim_match.merge(
    the_kpi6,
    on="name_std",
    how="left"
)

the_kpi6["research_productivity_index"] = (
    0.50 * the_kpi6["scores_research"]
    + 0.30 * the_kpi6["scores_citations"]
    + 0.20 * the_kpi6["scores_international_outlook"]
)

final_df = final_df.merge(
    the_kpi6[
        [
            "university_id",
            "research_productivity_index"
        ]
    ],
    on="university_id",
    how="left"
)

# ------------------------------------------------------------
# Years
# ------------------------------------------------------------

final_df["overview_year"] = 2025
final_df["research_year"] = 2024
final_df["student_year"] = 2023

# ------------------------------------------------------------
# Round KPI values
# ------------------------------------------------------------

kpi_columns = [
    "global_ranking_score",
    "research_impact_score",
    "faculty_to_student_ratio",
    "international_student_percentage",
    "academic_reputation_score",
    "research_productivity_index"
]

for column in kpi_columns:
    final_df[column] = pd.to_numeric(
        final_df[column],
        errors="coerce"
    ).round(2)

final_df = final_df.replace(
    [np.inf, -np.inf],
    np.nan
)

# ------------------------------------------------------------
# Save final KPI dataset
# ------------------------------------------------------------

output_file = os.path.join(
    PROCESSED_PATH,
    "university_final_dataset.xlsx"
)

final_df.to_excel(
    output_file,
    index=False
)

print("Education KPI dataset generated successfully.")
print("Universities:", len(final_df))
print("KPIs:", len(kpi_columns))
print("Output:", output_file)
'''

script_file = os.path.join(
    PROCESSED_PATH,
    "generate_education_kpis.py"
)

with open(script_file, "w", encoding="utf-8") as f:
    f.write(script)

print("===== PYTHON SCRIPT CREATED =====")
print("File:", script_file)
print("Exists:", os.path.exists(script_file))

===== PYTHON SCRIPT CREATED =====
File: /content/drive/MyDrive/EduVision_DV/03_Processed_Data/generate_education_kpis.py
Exists: True

In [ ]:
!pip install reportlab

Collecting reportlab
  Downloading reportlab-5.0.1-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.13/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.13/dist-packages (from reportlab) (3.4.9)
Downloading reportlab-5.0.1-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 25.9 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-5.0.1

In [ ]:
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
import os

PROJECT_PATH = "/content/drive/MyDrive/EduVision_DV"
REPORT_PATH = os.path.join(PROJECT_PATH, "04_Reports")

os.makedirs(REPORT_PATH, exist_ok=True)

output_file = os.path.join(
    REPORT_PATH,
    "dashboard_storyboard.pdf"
)

# Styles
styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    "TitleCustom",
    parent=styles["Title"],
    alignment=TA_CENTER,
    fontSize=20,
    spaceAfter=20
)

heading_style = ParagraphStyle(
    "HeadingCustom",
    parent=styles["Heading1"],
    fontSize=15,
    spaceBefore=10,
    spaceAfter=10
)

body_style = ParagraphStyle(
    "BodyCustom",
    parent=styles["BodyText"],
    fontSize=10,
    leading=14
)

# Document
doc = SimpleDocTemplate(
    output_file,
    pagesize=A4,
    rightMargin=40,
    leftMargin=40,
    topMargin=40,
    bottomMargin=40
)

story = []

# Title
story.append(
    Paragraph(
        "EduVision_DV – Dashboard Storyboard",
        title_style
    )
)

story.append(
    Paragraph(
        "Higher Education Intelligence System",
        ParagraphStyle(
            "subtitle",
            parent=body_style,
            alignment=TA_CENTER,
            fontSize=12,
            spaceAfter=20
        )
    )
)

story.append(
    Paragraph(
        "<b>Purpose:</b> Plan the four interlinked Tableau dashboards "
        "for university, research, student and country-level analysis.",
        body_style
    )
)

story.append(Spacer(1, 15))

# Dashboard 1
story.append(
    Paragraph(
        "1. University Overview Dashboard",
        heading_style
    )
)

data1 = [
    ["Component", "Planned Design"],
    ["KPIs", "Global Ranking Score, Academic Reputation Score"],
    ["Charts", "University ranking comparison, KPI comparison"],
    ["Filters", "University, Country, Region, Year"],
    ["Navigation", "Overview → Research / Student / Country"],
    ["Actions", "Select university to filter related views"],
    ["Purpose", "Provide a high-level view of university performance"]
]

table = Table(data1, colWidths=[130, 360])
table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("VALIGN", (0,0), (-1,-1), "TOP"),
    ("FONTSIZE", (0,0), (-1,-1), 9),
    ("LEFTPADDING", (0,0), (-1,-1), 6),
    ("RIGHTPADDING", (0,0), (-1,-1), 6)
]))
story.append(table)
story.append(Spacer(1, 20))

# Dashboard 2
story.append(
    Paragraph(
        "2. Research Analytics Dashboard",
        heading_style
    )
)

data2 = [
    ["Component", "Planned Design"],
    ["KPIs", "Research Impact Score, Research Productivity Index"],
    ["Charts", "Research performance comparison, research KPI distribution"],
    ["Filters", "University, Country, Region"],
    ["Navigation", "Overview ↔ Research ↔ Student ↔ Country"],
    ["Actions", "University selection and cross-dashboard filtering"],
    ["Purpose", "Analyze research strength and productivity"]
]

table = Table(data2, colWidths=[130, 360])
table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("VALIGN", (0,0), (-1,-1), "TOP"),
    ("FONTSIZE", (0,0), (-1,-1), 9),
    ("LEFTPADDING", (0,0), (-1,-1), 6),
    ("RIGHTPADDING", (0,0), (-1,-1), 6)
]))
story.append(table)
story.append(Spacer(1, 20))

# Dashboard 3
story.append(
    Paragraph(
        "3. Student Analytics Dashboard",
        heading_style
    )
)

data3 = [
    ["Component", "Planned Design"],
    ["KPIs", "Faculty-to-Student Ratio, International Student Percentage"],
    ["Charts", "Student ratio comparison, international student comparison"],
    ["Filters", "University, Country, Region"],
    ["Navigation", "Overview ↔ Research ↔ Student ↔ Country"],
    ["Actions", "University and country selection"],
    ["Purpose", "Understand student population and internationalization"]
]

table = Table(data3, colWidths=[130, 360])
table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("VALIGN", (0,0), (-1,-1), "TOP"),
    ("FONTSIZE", (0,0), (-1,-1), 9),
    ("LEFTPADDING", (0,0), (-1,-1), 6),
    ("RIGHTPADDING", (0,0), (-1,-1), 6)
]))
story.append(table)
story.append(Spacer(1, 20))

# Dashboard 4
story.append(
    Paragraph(
        "4. Country Comparison Dashboard",
        heading_style
    )
)

data4 = [
    ["Component", "Planned Design"],
    ["KPIs", "Country-level education indicators and university KPI summaries"],
    ["Charts", "Country comparison, regional comparison"],
    ["Filters", "Country, Region, Year, Education Indicator"],
    ["Navigation", "Overview ↔ Research ↔ Student ↔ Country"],
    ["Actions", "Country selection filters university-level analysis"],
    ["Purpose", "Compare higher-education characteristics across countries"]
]

table = Table(data4, colWidths=[130, 360])
table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("VALIGN", (0,0), (-1,-1), "TOP"),
    ("FONTSIZE", (0,0), (-1,-1), 9),
    ("LEFTPADDING", (0,0), (-1,-1), 6),
    ("RIGHTPADDING", (0,0), (-1,-1), 6)
]))
story.append(table)
story.append(Spacer(1, 20))

# Interlinking plan
story.append(
    Paragraph(
        "5. Interlinking and Navigation Plan",
        heading_style
    )
)

interlink_text = """
<b>Navigation:</b> A navigation menu will connect all four dashboards.<br/>
<b>University Selection:</b> Selecting a university will filter related analytical views.<br/>
<b>Country Selection:</b> Selecting a country will filter university and country-level views.<br/>
<b>Common Identifiers:</b> University_ID, Country_ID and Year will support consistent connections.<br/>
<b>Interactive Comparison:</b> Users will be able to compare universities, countries and regions using dashboard filters and actions.
"""

story.append(
    Paragraph(interlink_text, body_style)
)

story.append(Spacer(1, 15))

story.append(
    Paragraph(
        "<b>Prototype objective:</b> Verify dashboard layout, filters, navigation "
        "and interlinking before final Tableau dashboard development.",
        body_style
    )
)

# Build PDF
doc.build(story)

print("===== DASHBOARD STORYBOARD CREATED =====")
print("File:", output_file)
print("Exists:", os.path.exists(output_file))

===== DASHBOARD STORYBOARD CREATED =====
File: /content/drive/MyDrive/EduVision_DV/04_Reports/dashboard_storyboard.pdf
Exists: True